### ISSUE TITLE
Feature Request: seperate focus/soft/hard defer options for upgrades.

### ISSUE THREAD

**Issue by wakco** [Macjutsu/super#102]
This can be v4, v5, or even v6, as it's mostly a wish list item.

Essentially while we want updates to be fairly rapid, upgrades for most of us, due to their longer install times we want to allow longer timeframes. And due to that should probably be either exempt from `--reset-super`, or `--reset-super` should have an option to exclude resetting upgrade deferral times/counts (when not using dates as per my example below).

Essentially for upgrades, I'd like to allow staff plenty of time to perform upgrades when they are ready, usually over a 6 month period (October to March), so in my case I'd be looking at using dates, such as `--focus-upgrade-date=2023-12-31`, `--soft-upgrade-date=2024-03-31`, `--hard-upgrade-date=2024-04-30`, and maybe add a new option `--allow-upgrade-after=2023-09-30`. Possible even a `--menu-upgrade-defer=<days>` to allow users to select longer deferrals for upgrades inline with us allowing users to take longer to upgrade.

I do not expect everyones going to want to set it up with as long a window as my example above, but I do suspect that most of us are probably working with a week or less for updates, and probably wanting a month for upgrades. And I do realise this will mean dialogs will need to identify the difference between updates and upgrades during the window and allow for performing updates while an upgrade is deferred.

I'll hope you'll consider this for a future super version.

**Comment by wakco** [comment]
It dawns on me to realise that as super prepares everything before presenting any dialogs, this idea would also need something to establish which to prioritise for preparation. This could mean having a setting that decides an automatic preference, or another defer like setting to decide how far into the deferrals it should switch from preparing one to preparing the other. This would potentially simplify the defer menu dialog to simply stating that the other is also available and have an additional button to let the user switch from one to the other. Just a thought.

**Comment by Macjutsu** [comment]
So eventually in `super` there will be a concept of "scheduling", as opposed to just deferring until a deadline.

I think this will provide a more logical framework for having different "timings" for features like this.
