### ISSUE TITLE
Superman is failing to Update our OS Versions. 12.6.6 and Ventura 13.4.0 to the latest version. 

### ISSUE THREAD

**Issue by MacEngineer70** [Macjutsu/super#106]
We are running into this error message while trying to your your script in production. We have an issue in which the script is not updating our endpoints to 12.6.7 of Monterey. In addition to Ventura 13.4.1.  Please feel free to reach out to me at 571-639-6143. Jon DeBerry
![Screenshot 2023-07-12 at 12 52 01 PM](https://github.com/Macjutsu/super/assets/139150956/b60a3c2a-d904-44ff-93ad-c54c5fc0e789)

Executing Policy SUPERMAN Run_PRODUCTION MASTER
--
Running script Run Superman...
Script exit code: 1
Script result: sudo: super: command not found
Error running script: return code was 1.

**Comment by Macjutsu** [comment]
This is not an issue with `super`'s code, this is a problem with your implementation.

If you want support for using `super` please reach out to the [Mac Admins Foundation Slack](https://www.macadmins.org) in channel [#super](https://macadmins.slack.com/archives/C03LKQ8EN2C).
