### ISSUE TITLE
How to suppress IBM Notifier: Opening Install now up to date notification

### ISSUE THREAD

**Issue by yinfante356** [Macjutsu/super#109]
While trying to use the Install Now functionality i would like to make it seamless for unattended installs.  One issue identified is that after all updates install, IBM notifier shows a final message stating "Apple System software is already up to date or is the latest version allowed by management.   Looking for ways to suppress this message or make it go away on its own.  currently requires end user to hit OK for it to go away.   The super.log shows it as  "IBM Notifier: Opening Install now up to date notification"

**Comment by yinfante356** [comment]
A few scenarios of the above also keeps a window of "Apple Software Update Starting" that never quits.  again this is after it has installed all updates and performs the last reboot.  only way to get rid of the "Update starting" window is to kill the IBM Notifier app from Activity Monitor.

**Comment by wakco** [comment]
[`--install-now`](https://github.com/Macjutsu/super/wiki/User-Initiated-Workflows#install-macos-updates-now) is intended for Self Service situations, where you do want those extra dialogs. If you do not want them, do not use [`--install-now`](https://github.com/Macjutsu/super/wiki/User-Initiated-Workflows#install-macos-updates-now).

See [https://github.com/Macjutsu/super/wiki/User-Initiated-Workflows#install-macos-updates-now](https://github.com/Macjutsu/super/wiki/User-Initiated-Workflows#install-macos-updates-now) for more information.

**Comment by Macjutsu** [comment]
@wacko is correct regarding the purpose and design for `--install-now`. However, the default for `super` (if a user is logged in) is to prompt the user for a restart. Thus if @yinfante356 want's to start the workflow without asking, you actually want to use a hard deadline that has passed. For example, use `--hard-count=0`.

Given that there is a solution in `super` to accomplish the actual goal of installing while unattended. I'm closing this issue.

**Comment by yinfante356** [comment]
Thank you for the feedback @wakco and @Macjutsu . i appreciate the fast response on this matter.
