### ISSUE TITLE
Feature Request: Jamf EA with "Deferral available until"

### ISSUE THREAD

**Issue by vonderboi** [Macjutsu/super#110]
I think this would be helpful to determine why a computer might not be updated yet.

**Comment by vonderboi** [comment]
Yes, I use the Hard Days as a deadline so depending on when the Jamf policy executes we will have different deadlines.  I don't like to use a hard date because if say someone just came back from vacation I don't want them powering on their computer at 8:50 AM expecting to join a 9:00 AM  meeting and have it automatically start any updating process.

**Comment by vonderboi** [comment]
I guess I could just use the ZeroDayAuto date and time from the plist and mentally do the math.

**Comment by Macjutsu** [comment]
Yes... but this is a good idea.

**Comment by Macjutsu** [comment]
I plan to have this out by the v5.0.0 final release.

**Comment by Macjutsu** [comment]
I forgot to close this two weeks ago when I posted v5.0.0-rc1. At any case there are now a bunch of new EAs that cover this.

https://github.com/Macjutsu/super/tree/5.0.0-rc1/Super-Friends
