### ISSUE TITLE
Error: Unable to reach Apple Software Update server, trying again in 3600 seconds.

### ISSUE THREAD

**Issue by bigSteve2001** [Macjutsu/super#112]
We are currently rolling out the latest rsr for 13.4.1 and I am seeing a fair number of systems reporting an error that they cannot reach the update server.

When I dig into the super.log super sees that the update is available, downloads it, then restarts the software update daemons,  then fails

Below is the excerpt that I am referencing.

I looked in the config options but do not see anything to prevent the script from restarting the daemon before continuing.

Any ideas?

I immediately run a softwareupdate -l and the succeeds.

Fri Jul 21 13:52:30 XLTJ2KKQP9F2P super[47386]: Verbose Mode: Function downloadMacOSSoftwareUpdate: workflowCompletePERCENT is: 8

Fri Jul 21 13:52:30 XLTJ2KKQP9F2P super[47386]: Verbose Mode: Function downloadMacOSSoftwareUpdate: workflowCompletePERCENT is: 9

Fri Jul 21 13:52:30 XLTJ2KKQP9F2P super[47386]: Verbose Mode: Function downloadMacOSSoftwareUpdate: workflowCompletePERCENT is: 100

Fri Jul 21 13:52:30 XLTJ2KKQP9F2P super[47386]: Not Logged: macOS Security Response 13.4.1 (c) download progress: 100%

Fri Jul 21 13:52:30 XLTJ2KKQP9F2P super[47386]: softwareupdate: macOS Security Response 13.4.1 (c) download complete, now preparing...

Fri Jul 21 13:52:30 XLTJ2KKQP9F2P super[47386]: Status: Restarting various softwareupdate daemon processes...

Fri Jul 21 13:52:35 XLTJ2KKQP9F2P super[47386]: Error: Unable to reach Apple Software Update server, trying again in 3600 seconds.

Fri Jul 21 13:52:35 XLTJ2KKQP9F2P super[47386]: Status: Removing previous LaunchDaemon com.macjutsu.super.plist.

Fri Jul 21 13:52:36 XLTJ2KKQP9F2P super[47386]: Verbose Mode: Function makeLaunchDaemonCalendar: deferSECONDS is: 3600

**Comment by Macjutsu** [comment]
A few things:
- Check the asu.log... as noted earlier in the super.log and documented here: https://github.com/Macjutsu/super/wiki/Troubleshooting#understanding-sub-process-logs
- Just because `softwareupdate` can return a list (which is often just a local cache) doesn't mean it can download and prepare an update/upgrade.
- Anytime `super` detects an error it always bounces `softwareupdated`... again check the asu.log for the specific error.

**Comment by kaaablume** [comment]
I am seeing similar behavior - when I check the log I see the following build compatibility error.  Expected with 13.4.1 but not with 13.4.1c (or so I thought). 


```
Fri Jul 21 09:08:09 LAX-CSO-MBP super[34019]: **** S.U.P.E.R.M.A.N. 3.0b12 DOWNLOAD macOS Security Response 13.4.1 (c) SOFTWAREUPDATE START ****
Software Update Tool

Finding available software
Downloading macOS Security Response 13.4.1 (c)

Downloading: 0.10%
Downloading: 1.00%
Downloading: 1.90%
Downloading: 3.00%
Downloading: 3.90%
Downloading: 4.00%
Fri Jul 21 09:08:20 LAX-CSO-MBP super[34019]: **** TIMESTAMP ****

Downloading: 6.90%
Downloading: 7.00%
Downloading: 7.00%
Downloading: 7.00%
Downloading: 7.00%
Downloading: 8.90%
Downloading: 9.00%
Downloading: 100.00%
Failed to download & prepare update: Error Domain=SUOSUErrorDomain Code=201 "The base build is not compatible for this install method." UserInfo={NSLocalizedRecoverySuggestion=An error occurred while downloading the selected updates. Please check your internet connection and try again., NSLocalizedDescription=The base build is not compatible for this install method., NSUnderlyingError=0x6000036c89c0 {Error Domain=com.apple.BuildInfo.preflight.error Code=12 "The base build is not compatible for this install method." UserInfo={BIPreflightAlternateInstallerRecommended=true, NSLocalizedFailureReason=The base build is not compatible for this install method., NSLocalizedDescription=The base build is not compatible for this install method.}}}

Fri Jul 21 09:08:24 MacBook super[34019]: **** TIMESTAMP ****

Fri Jul 21 09:08:24 MacBook super[34019]: **** S.U.P.E.R.M.A.N. 3.0b12 DOWNLOAD SOFTWAREUPDATE FAILED ****

Fri Jul 21 09:08:29 MacBook super[34019]: Error: Unable to reach Apple Software Update server, trying again in 120 seconds.
```

**Comment by Macjutsu** [comment]
Any line in the asu.log that doesn't contain the word "super" is generated directly by the built-in macOS `softwareupdate` process. In other words, that "Failed to download error..." is generated by `softwareupdate` and is not an issue with `super` itself.

`super` can't "fix" Apple's software update service errors... all it can do is try again later.

**Comment by Macjutsu** [comment]
Please try to replicate in https://github.com/Macjutsu/super/releases/tag/v4.0.0-rc1.

If you can't replicate this by the release of v4.0.0 later this week, I'll be closing this issue.

**Comment by Macjutsu** [comment]
https://github.com/Macjutsu/super/releases/tag/v4.0.0
