### ISSUE TITLE
Question: Jamf Pro 10.48

### ISSUE THREAD

**Issue by RLNY88** [Macjutsu/super#113]
Hello All,

I apologize in advance if this is not the place to post this message. Have anyone tested Super in Jamf Pro version 10.48? If Super is not supported in this version, do we have an ETA? Again, thanks so much for all your help!

Best Regards,
RL

**Comment by master-vodawagner** [comment]
It works on my 10.48 but I've not enabled the new beta software update workflow that was released in 10.48.  If you enable that workflow then super won't work until @Macjutsu introduces the new API endpoints into super.

**Comment by RLNY88** [comment]
@master-vodawagner Thanks for the quick reply! Much appreciated.
