### ISSUE TITLE
Defer time is not working

### ISSUE THREAD

**Issue by unknown-027** [Macjutsu/super#114]
I have configured Superman script and have set defer time to 5min and 10min, but once the notification pops up for defer and if I select 5min time its not showing up anything after 5min its just directly comes on next day.
what could be the reason

**Comment by Macjutsu** [comment]
Sorry for loosing this one in the mix... please check the local computers super.log for details.

**Comment by unknown-027** [comment]
Thanks for the update,
Will check the same

**Comment by Macjutsu** [comment]
Please try to replicate in https://github.com/Macjutsu/super/releases/tag/v4.0.0-rc1.

If you can't replicate this by the release of v4.0.0 later this week, I'll be closing this issue.

**Comment by Macjutsu** [comment]
https://github.com/Macjutsu/super/releases/tag/v4.0.0
