### ISSUE TITLE
Add failover method for when local admin fails just like the failover in place for MDM failures

### ISSUE THREAD

**Issue by yinfante356** [Macjutsu/super#115]
Macjutsu - 

Although the use of local credentials works great, i am running into a few issues with certain devices that may not have a matching password on the local Admin account.  I would like to have the flexibility to present the end user with Creds when local admin account fails to verify.

Credential Error: The provided password for account "TestAdminUser" is not valid.
Warning: Automatic macOS update/upgrade enforcement on Apple Silicon computers requires authentication credentials
Exit: Startup validation failed.

I tried using the --user-auth-mdm-failover= options but these does not seem to work as they appear to be strictly for the Jamf API workflow. 

End goal, "as a failover" allow end user to Authenticate and for the update to proceed (given they have Secure Token rights of course)

**Comment by yinfante356** [comment]
Thank you very much

**Comment by peter1122999** [comment]
+1 for this feature

**Comment by Macjutsu** [comment]
https://github.com/Macjutsu/super/releases/tag/v4.0.0-beta1
