### ISSUE TITLE
Superman unable to use passwords not in the ASCII range of characters

### ISSUE THREAD

**Issue by bdresher** [Macjutsu/super#116]
## Summary
When an account password is not in the ASCII range, `security find-generic-password` returns a string that is an ASCII representation of the UTF-8 encoding of the string which does not match the actual UTF-8 encoded string of the password.

`security find-generic-password -w -a "_superServiceAccount" -s "Super Local Account"`

## Steps to reproduce the issue
As root run the following in a terminal window.

**add a service account**
`sysadminctl -addUser "_superServiceAccount" -UID 243 -password "ᴌ⟸ჷ⒅ƴ≾⢪〓Ⲻ꧅᠗ꭽ⎛⒀õ♶꛵㏪Შ႔⠕ґ꧁↕▽ṈᎵҌ⫦▒სⲌ༽⊍⍝Ⓓ᭛⮂" -roleAccount`

**give the service account a secureToken**
`sysadminctl -secureTokenOn _superServiceAccount -password 'ᴌ⟸ჷ⒅ƴ≾⢪〓Ⲻ꧅᠗ꭽ⎛⒀õ♶꛵㏪Შ႔⠕ґ꧁↕▽ṈᎵҌ⫦▒სⲌ༽⊍⍝Ⓓ᭛⮂' -adminUser YOURADMINUSERNAMEgoesHere -adminPassword -`

**start super with the Service Account created**
`super --local-account='_superServiceAccount' --local-password='ᴌ⟸ჷ⒅ƴ≾⢪〓Ⲻ꧅᠗ꭽ⎛⒀õ♶꛵㏪Შ႔⠕ґ꧁↕▽ṈᎵҌ⫦▒სⲌ༽⊍⍝Ⓓ᭛⮂'`

## Sample of possible fix (base64 encode/decode the super account password string)
**super line 2132-2133 - base64 encode the password string when adding the account's keychain entry**
```
security add-generic-password -a "$localACCOUNT" -s "Super Local Account" -w $(echo "$localPASSWORD" | base64) -T /usr/bin/security /Library/Keychains/System.keychain
localKEYCHAIN="`security find-generic-password -w -a "$localACCOUNT" -s "Super Local Account" /Library/Keychains/System.keychain 2> /dev/null | base64 --decode`"
```

**super line 2234 - base64 decode the password retrieved from the keychain**
```
localKEYCHAIN="`security find-generic-password -w -a "$localACCOUNT" -s "Super Local Account" /Library/Keychains/System.keychain 2> /dev/null | base64 --decode`"
```

**Comment by Macjutsu** [comment]
Great suggestion and timing.

I'm literally auditing that code this week for a variety of other reasons.

This also further obfuscates the secrets from "novice" prying eyes.

**Comment by Macjutsu** [comment]
https://github.com/Macjutsu/super/releases/tag/v4.0.0-beta1
