### ISSUE TITLE
Feature Request: Increase deferral options by more than 1 day

### ISSUE THREAD

**Issue by nlecchi** [Macjutsu/super#117]
It would be nice to increase the number of deferral days, 2 or 5 days, or add a calendar for choosing days.
![Image 29-08-23 at 12 01](https://github.com/Macjutsu/super/assets/82441389/df6aa50d-0b5f-41cf-b6c2-d737fefff5e0)

**Comment by Luke-From-IT** [comment]
Might be worth noting this is was a feature request with IBM Notifier as well, I guess once that's done it could be implemented into Super?

https://github.com/IBM/mac-ibm-notifications/issues/119

**Comment by Macjutsu** [comment]
I'm aware... the issue is that there is (currently) still no way in IBM Notifier to limit which calendar days are allowed for selection.

**Comment by Macjutsu** [comment]
https://github.com/Macjutsu/super/releases/tag/v4.0.0-beta1
