### ISSUE TITLE
API Account failures

### ISSUE THREAD

**Issue by PezzaD84** [Macjutsu/super#118]
Hi,

I manage a few different JAMF tenants and on some of them I am seeing API account failures on random devices. There seems to be no difference in OS version, super version, or what update it's trying to push. We only want to push updates via MDM command and do not want to use the local admin failover.

The error is as follows:
`Tue Aug 22 09:10:31 TRAMS-1R26JX super[12383]: Error: Failed to send MDM install update/upgrade request. Verify that the Jamf Pro API account "superman_api" has the privileges "Jamf Pro Server Objects > Computers > Create & Read" and "Jamf Pro Server Actions > Send Computer Remote Command to Download and Install macOS Update".
Tue Aug 22 09:10:31 TRAMS-1R26JX super[12383]: **** S.U.P.E.R.M.A.N. 3.0 UPDATE/UPGRADE MACOS MDM PUSH FAILED ****`

The API account works fine on other devices and can also access JAMF fine so there is nothing wrong with the permissions as the error is stating.
Has anyone else run into this issue and is there a fix?
Thanks!

**Comment by rrouleau** [comment]
I just recently saw this issue in my installation. Same issue and error.
Looking forward to helping resolve in any way I can help.

**Comment by Macjutsu** [comment]
Please try to replicate in https://github.com/Macjutsu/super/releases/tag/v4.0.0-rc1.

If you can't replicate this by the release of v4.0.0 later this week, I'll be closing this issue.

**Comment by Macjutsu** [comment]
https://github.com/Macjutsu/super/releases/tag/v4.0.0
