### ISSUE TITLE
Add to Jamf Marketplace?

### ISSUE THREAD

**Issue by motionbug** [Macjutsu/super#12]
Thank you for making this, love it and have implemented it a couple times.

Would be good to add to the jamf marketplace, then I can send my customers there as well looking for this amazing solution!

**Comment by Macjutsu** [comment]
[This was finally posted](https://marketplace.jamf.com/details/s-u-p-e-r-m-a-n) to the Jamf Marketplace... not sure what's wrong with the screenshots though... oh well... better late than never!
