### ISSUE TITLE
Upgrading IBM Notifier?

### ISSUE THREAD

**Issue by jelockwood** [Macjutsu/super#123]
When SUPER is first installed it downloads and installs it's own private copy of IBM Notifier in to -

/Library/Management/super/IBM Notifier.app

As far as I can see whilst this is in a non-standard location it is a standard copy of this app.

I have therefore been perhaps too clever and worked on an AutoPkg recipe for Munki which downloads the latest IBM Notifier from the IBM GitHub repo, wraps it in an installer pkg which installs this latest copy in to the special location used by the SUPER script. I then have Munki check this location for what version is currently there and if needed runs my installer pkg to update it.

My installer pkg does work and does update this locations copy.

However it looks like something else is periodically _downgrading_ it back to version 2.9.1 of IBM Notifier. (The current version at the time I write this is actually 3.0.3.)

Is the SUPER script installing a specific now out of date version each time it runs?
Answer - yes it is!

I tested and confirmed this by running the super-starter script and watched it replace version 3.0.3 with 2.9.1 of IBM Notifier.

Is there any particular reason why SUPER wants to use an out of date version?

**Comment by jelockwood** [comment]
Yes as I mentioned I had deliberately built a process using AutoPkg and Munki to upgrade your copy of IBM Notifier and then saw your system was downgrading it back. 🥲 

I have now turned mine off since as things stand it is pointless.

**Comment by Macjutsu** [comment]
FWIF... `super` v3 should work with the latest versions of IBM Notifier. I'm just not going to test further for `super` v3.

**Comment by Macjutsu** [comment]
https://github.com/Macjutsu/super/releases/tag/v4.0.0-beta1
