### ISSUE TITLE
4.0b1 - display-hide-background stops working if user enters wrong password

### ISSUE THREAD

**Issue by TechTrekkie** [Macjutsu/super#124]
I was doing some testing with 4.0b1 and noticed if a user is prompted to enter a password with `display-hide-background` enabled and enters an incorrect password, the background is no longer blurred when the user is re-prompted to enter the correct password. I haven't had a chance to dig through the code but was curious if it's possible for display-hide-background to be enabled if the user has to be prompted a second or more times for a correct password. 

Steps to reproduce:
1. Run super with `display-hide-background` and `auth-ask-user-to-save-password` enabled
2. Restart/Defer dialog displays, click restart to continue workflow
3. User auth password prompt displays with `display-hide-background` enabled, enter wrong password and press restart
4. User auth password prompt displays again with `display-hide-background` disabled

**Comment by Macjutsu** [comment]
What is your specific `--display-hide-background` type? "ALWAYS" or something else?

**Comment by TechTrekkie** [comment]
It was set to `USERAUTH`

**Comment by Macjutsu** [comment]
Thank you!

**Comment by Macjutsu** [comment]
https://github.com/Macjutsu/super/releases/tag/v4.0.0-beta2
