### ISSUE TITLE
V4.0b1 - AUTHMDMFailoverToUser - Not a valid identifier

### ISSUE THREAD

**Issue by master-vodawagner** [Macjutsu/super#125]
I've got this set in the config profile via Jamf, looks like its picked up in Super V4 but the output of the local pref files doesn't show it.

<key>AuthMDMFailoverToUser</key>
<string>ALWAYS</string>

Wed Sep 20 09:59:52 Lewis super[3451]: Verbose Mode: Function manage_parameter_options: auth_credential_failover_to_user_option is: FALSE
/Library/Management/super/super: line 2041: local: `auth-mdm-failover-to-user-array': not a valid identifier
/Library/Management/super/super: line 2042: read: `auth-mdm-failover-to-user-array': not a valid identifier
Wed Sep 20 09:59:52 Lewis super[3451]: Parameter Error: Unrecognized --auth-mdm-failover-to-user value of: mdm-failover-to-user-array[@]. You can specify any of the following types separated by commas (no spaces); ALWAYS,SOFT,HARD,INSTALLNOW,BOOTSTRAP.

**Comment by croaker-1** [comment]
Changing `auth-mdm-failover-to-user-array` to `auth_mdm_failover_to_user_array` seems to fix it.

**Comment by master-vodawagner** [comment]
Yep, confirmed as working with that change.

**Comment by Macjutsu** [comment]
Now that's a weird typo! Thank you for finding it!

**Comment by Macjutsu** [comment]
https://github.com/Macjutsu/super/releases/tag/v4.0.0-beta2
