### ISSUE TITLE
V4.0b1 - Failed conversion of ``Mon Sep 4 12:08:00'' using format ``%b %d %H:%M:%S'' date: illegal time format

### ISSUE THREAD

**Issue by master-vodawagner** [Macjutsu/super#126]
Getting this error on each run of super

Wed Sep 20 09:55:18 Lewis Super-v4.0b1[2420]: Verbose Mode: Function workflow_startup: Uptime is:  9:55  up 15 days, 21:47, 2 users, load averages: 2.85 3.62 4.18
Failed conversion of ``Mon Sep 4 12:08:00'' using format ``%b %d %H:%M:%S''
date: illegal time format
usage: date [-jnRu] [-I[date|hours|minutes|seconds]] [-f input_fmt]
            [-r filename|seconds] [-v[+|-]val[y|m|w|d|H|M|S]]
            [[[[mm]dd]HH]MM[[cc]yy][.SS] | new_date] [+output_fmt]

**Comment by Macjutsu** [comment]
Hey thanks for this bug... but I have a question.

I found the line that generates that error... it's actually in the `check_system()` function and it's trying to figure out the last system startup and converting the date/time to the format that is used in the rest of `super`.

Can you please test the following for me on your system? `last -1 reboot | cut -c 41- | xargs` Here is what it looks like on my system:

`❯ last -1 reboot | cut -c 41- | xargs`
`Sep 17 15:07`

**Comment by master-vodawagner** [comment]
I'lll try to replicate it, had to factory reset the laptop used

**Comment by master-vodawagner** [comment]
Annoyingly its not showing up on my fresh laptop :(

**Comment by TechTrekkie** [comment]
I just ran that command on mine and here's the result. Includes the day of the week just before the month.

❯ last -1 reboot | cut -c 41- | xargs
Tue Sep 19 06:52

**Comment by thevoices** [comment]
I am getting the same error, and the output of last is 
Fri Sep 15 11:46

**Comment by Macjutsu** [comment]
Indeed I have found this bug and dealt with it in the next release... soon.

**Comment by Macjutsu** [comment]
https://github.com/Macjutsu/super/releases/tag/v4.0.0-beta2
