### ISSUE TITLE
V4.0b1 - icon.png permissions too strict to display in IBM notifer

### ISSUE THREAD

**Issue by master-vodawagner** [Macjutsu/super#127]
I think the icon.png file in /Library/Management/super that super creates when pulling the image from an online source has permissions that are too tight for standard user accounts to view when its placed into an IBM Notifier prompt.

I got the icon of IBM Notifier displayed, when I changed the file permission to 777 and triggered super again it then displayed the correct file

**Comment by master-vodawagner** [comment]
Guessing the SIP process is running as root and creates the $DISPLAY_ICON_FILE_CACHE with root permissions only.  Prob just needs to change the permissions to read only for everyone?

**Comment by Macjutsu** [comment]
Thanks for finding this one!

**Comment by Macjutsu** [comment]
While I can't replicate the behavior, I'll still add this line just in case...

`chmod a+r "${DISPLAY_ICON_FILE_CACHE}"`

**Comment by Macjutsu** [comment]
https://github.com/Macjutsu/super/releases/tag/v4.0.0-beta2

**Comment by master-vodawagner** [comment]
Re-opening, icon file is still showing permissions of 600, unless the reset argument doesn't clear out the cached icon?

**Comment by remusache** [comment]
Same here! 
V4-beta3

**Comment by Macjutsu** [comment]
If you're referring to `--reset-super` then yes it does reset the cached icon.

Here is the code change... I mean... literally chmod all can read.... so I'm not sure why the resulting cached icon for you has those permissions.

```
log_super "Status: Copying requested --display-icon-file from: ${display_icon_file_option}"
sips_response=$(sips --setProperty format png "${display_icon_file_option}" --out "${DISPLAY_ICON_FILE_CACHE}" 2>&1)
chmod a+r "${DISPLAY_ICON_FILE_CACHE}"
```

And unsurprisingly my result is acceptable... I can't replicate this issue...

```
❯ ls -la /Library/Management/super/icon.png
-rw-r--r--  1 root  wheel  783521 Sep 29 18:02 /Library/Management/super/icon.png
```

**Comment by master-vodawagner** [comment]
Ah yes, can see the icon deleting itself but it just re-appears with 600

❯ ls -la /Library/Management/super/icon.png
-rw-------  1 root  wheel  783521 2 Oct 15:30 /Library/Management/super/icon.png

**Comment by master-vodawagner** [comment]
That works fine, wondering does that chmod need to also exist on LN1807?

**Comment by Macjutsu** [comment]
Doh! and also probably ~LN1827... basically after every `sips_response...`

Try that and lemme know how it works.

**Comment by master-vodawagner** [comment]
Yep, worked on my test device adding chmod a+r "${DISPLAY_ICON_FILE_CACHE}" to LN1807, didn't add to the additional line you just commented on

**Comment by Macjutsu** [comment]
https://github.com/Macjutsu/super/releases/tag/v4.0.0-beta4
