### ISSUE TITLE
Required - API Role - Minimum Privileges Required

### ISSUE THREAD

**Issue by blakeusblade** [Macjutsu/super#128]
It would be good to have published the minimum privileges required in jamf pro for (API Roles and Clients).
Currently, I've just enabled "Send Computer Remote Command to Download and Install OS X Update"

**Comment by blakeusblade** [comment]
Additionally, with v4beta1... Based on the WARNING I got in the logs... I removed the below installation parameters (soon to be deprecated I assume).

--auth-jamf-account=AccountName
--auth-jamf-password=Password

and setup an "API Role and Client" (Mentioned above in the main post)

Added the below into my installation parameters
--auth-jamf-client=ClientID
--auth-jamf-secret=ClientSecret

In doing so, I get the following in the super logs when super attempts installation.
Error: Unable to validate Jamf Pro API software update workflow type. Verify that the provided Jamf Pro credentials has appropriate privledges: 
Error: Failed to validate Jamf Pro API configuration

**Comment by master-vodawagner** [comment]
Yep, I was going to say the permissions were in the wiki, you just needed to add each component into the Roles and client section individually

**Comment by Macjutsu** [comment]
A few things here....
- I haven't had time to update the Wiki for v4, but it's a priority.
- Until then the [Changelog](https://github.com/Macjutsu/super/blob/4.0.0-beta1/CHANGELOG.md) documentation is accurate.
- In the Changelog you'll find the required API permissions.
