### ISSUE TITLE
Can't Reset Super using --reset-super after applying --auth-ask-user-to-save-password

### ISSUE THREAD

**Issue by blakeusblade** [Macjutsu/super#129]
Using --auth-ask-user-to-save-password makes super forever use this and cannot be reset using --reset-super. Deleting the super directory and redeploying was the only way I could switch it back to using anything else...

**Comment by Macjutsu** [comment]
`--reset-super` never resets any authentication settings.

If you use `super --usage` you'll see there are two options that will disable this setting, specifically:
`--auth-ask-user-to-save-password-off`
`--auth-delete-all`

**Comment by blakeusblade** [comment]
I did try --auth-delete-all however didnt try --auth-ask-user-to-save-password-off... Good to know... Thanks heaps

**Comment by Macjutsu** [comment]
Reopening... there is a bug here... `--auth-delete-all` didn't clear the user authentication option as it should have.

**Comment by Macjutsu** [comment]
https://github.com/Macjutsu/super/releases/tag/v4.0.0-beta2
