### ISSUE TITLE
Feature Request : User input for Deferral 

### ISSUE THREAD

**Issue by Rustbolt** [Macjutsu/super#130]
Some users find only having the option to defer after a certain number of hours annoying. 

Would it be possible to add a user input option for the deferral? So the user can select one of the menu deferrals or enter an exact time in the day like defer until such as 5:30pm. Most users prefer to do it at the end of the day.

**Comment by Macjutsu** [comment]
This is "effectively" implemented via the new `--scheduled-install-user-choice` option in https://github.com/Macjutsu/super/releases/tag/v5.0.0-beta2

It would be entirely too complicated to have multiple simultaneous workflows... instead you can override your default workflow with a temporary workflow until complete.
