### ISSUE TITLE
Allow optional centring UI for notifications

### ISSUE THREAD

**Issue by khronokernel** [Macjutsu/super#132]
When using the blur option in super, all focus is placed on super's UI. For notification items, this can be a bit confusing for end users as the prior UI for deferral/install is centred due to being a dialog. Option to configure that all UI elements be centred would be much appreciated.

![Screenshot 2023-09-22 at 3 45 39 PM](https://github.com/Macjutsu/super/assets/48863253/a22295f2-824c-479d-a3df-41c3d0d5b0fc)

**Comment by Macjutsu** [comment]
Good idea... I'll need to think about how to express the feature in the settings without making it too complicated.

Ideally, all UI element locations would be selectable.... but then the options can get complicated quickly as there are obviously several locations on the screen times the different types of dialog/notifcations drawn by `super`.

**Comment by Macjutsu** [comment]
https://github.com/Macjutsu/super/releases/tag/v4.0.0-beta6
