### ISSUE TITLE
v4 Jamf sample schema 'Soft Days' key is incorrect

### ISSUE THREAD

**Issue by cfatechsupport** [Macjutsu/super#137]
v4 Jamf sample schema 'Soft Days' key is incorrect- currently 'DeadlineSoftDays' but should be 'DeadlineDaysSoft'

https://github.com/Macjutsu/super/blob/4.0.0-beta1/Example-MDM/Jamf-Pro-External-Application-Custom-Schema-com.macjutsu.super-v4.0.0.json

**Comment by Macjutsu** [comment]
https://github.com/Macjutsu/super/releases/tag/v4.0.0-beta2
