### ISSUE TITLE
SUPER failing when both Ventura update and Sonoma upgrade available

### ISSUE THREAD

**Issue by jelockwood** [Macjutsu/super#141]
I have some Macs running e.g. macOS Ventura 13.5.2 and therefore currently have from Apple an update to 13.6 listed and an _upgrade_ to macOS Sonoma 14.0 also listed.

The SUPER script is supposed to be able to cope with this and has preference keys to if desired _only_ do updates but I have enabled both updates and upgrades.

I can see some of my companies Macs have successfully upgraded to Sonoma and based on what I am seeing so far I would feel these Macs were _already_ on macOS 13.6 and hence would only have today been offered Sonoma 14.0 and not both a Ventura and Sonoma option.

Here is the SUPER log

[super.log](https://github.com/Macjutsu/super/files/12741235/super.log)

**Comment by jelockwood** [comment]
I have just done a further test, this time by deliberately setting my Jamf pushed preferences to _disable_ upgrades to SUPER only does updates. This does appear to be successfully downloading the Ventura 13.6 update.

This does seem to confirm there is a script problem working with both available updates and an available upgrade.

**Comment by Macjutsu** [comment]
Please use the new versions of `super`... I know they are beta but they are superior to v3... and I don't plan to ever fix issues in v3 now that I'm working on v4.

https://github.com/Macjutsu/super/releases

**Comment by Macjutsu** [comment]
Also to clarify... I'm certain this issues is resolved by `super` v4.x
