### ISSUE TITLE
wrong readonly?

### ISSUE THREAD

**Issue by marcelpogorzelski** [Macjutsu/super#143]
https://github.com/Macjutsu/super/blob/2c1184e6950cf95025322a7e7c514ff1552502b5/super#L308

I think this should be:
`readonly MIST_CLI_TARGET_VERSION`

**Comment by Macjutsu** [comment]
Good find! ... 

More good news is that it's not really a problem for the script as the `readonly`s are more for saftey/style than they are actually needed for operation.

**Comment by Macjutsu** [comment]
https://github.com/Macjutsu/super/releases/tag/v4.0.0-beta4
