### ISSUE TITLE
Fix --Error-defer to --error-defer in Wiki

### ISSUE THREAD

**Issue by dxdlazarev** [Macjutsu/super#144]
Subj
Not sure if it's possible to create a PR for Wiki in this repo.
https://github.com/Macjutsu/super/wiki/Deferral-Behavior
At least for command option, didn't test it with a profile
With capital E I was getting `Unrecognized Options: --Error-defer=120`
super was running from Jamf Pro 10.50, --Error-defer=120 was one of a policy script Parameter Values

**Comment by Macjutsu** [comment]
I can do that... FYI... that's the v3 wiki... working on a v4 beta wiki as we speak.
