### ISSUE TITLE
Your grep regex is not capturing 11.7.10 in macOSSoftwareUpdateVERSION

### ISSUE THREAD

**Issue by gzilla13** [Macjutsu/super#145]
Your regex is not designed to pickup two digits at the major.minor.patch version for macOS 11 (11.7.10)
macOSSoftwareUpdateVERSION=$(echo "$macOSSoftwareUpdateLABEL" | grep -o '11.[0-9].[0-9]')

Amend to 11.[0-9].[0-9][0-9]?

**Comment by macdsl** [comment]
Agreed, noticing same thing.. :-)

**Comment by Macjutsu** [comment]
what version of `super`?

**Comment by macdsl** [comment]
Hey, Robert Humphreys from SONY Imageworks here :-)..  Version 3.0

**Comment by macdsl** [comment]
If it helps, the error i get is:
Thu Sep 28 13:38:20 spamacd-2218 super[80542]: Not Logged: macOS Big Sur
11.7.10 preparing progress: 100%
Thu Sep 28 13:38:20 spamacd-2218 super[80542]: softwareupdate: macOS Big
Sur 11.7.10 download and preparation complete.
Thu Sep 28 13:38:20 spamacd-2218 super[80542]: Error: Downloaded macOS
update version of 11.7.10 doesn't match expected version 11.7.1, trying
again in 3600 seconds.

**Comment by jffgrumpy** [comment]
Confirmed, also seeing this issue in v3.0.

**Comment by Macjutsu** [comment]
This is fixed in v4-betas. I have no plans to fix this in v3.0.
