### ISSUE TITLE
Question - SUPER 4.0 command line options

### ISSUE THREAD

**Issue by jelockwood** [Macjutsu/super#146]
@Macjutsu 
I can see you have a [table](https://github.com/Macjutsu/super/blob/4.0.0-beta3/Super-Friends/super-3to4-migration-managed-preferences.tsv) mapping the old v3.0 preferences to their v4.0 equivalents. Thanks for that.

However I could not find anything similar that showed the mapping between v3.0 command line options and v4.0 equivalents. Having had a quick look at the v4.0 code in the SUPER script it does look like as I expected these have had similar changes.

In particular I need to know what the following v3.0 command line options would now be for v4.0

```
--jamf-account=
--jamf-password=
--admin-account=
--admin-password=
```

**Comment by Macjutsu** [comment]
Credentials can't be used in a config profile managed preference (the document you linked to in your question)... they have never been there.

There is a different document for command line options: https://github.com/Macjutsu/super/blob/4.0.0-beta3/Super-Friends/super-3to4-migration-options.tsv

**Comment by jelockwood** [comment]
@Macjutsu 
Thanks, yes I was expecting a different table but could not find the wood for the trees 😄 

Thanks for the pointer
