### ISSUE TITLE
Error: Unable to find compatible macOS installers

### ISSUE THREAD

**Issue by yinfante356** [Macjutsu/super#147]
Since the release of Sonoma,  SUPER 3.0 is failing to continue to update devices to latest 13.  I understand that you want us to use SUPER 4.0 for upgrades to Sonoma but 3.0 is failing to continue to update 13.x.  See below. 

Mon Oct 02 15:49:17 TestDevice01 super[24580]: **** S.U.P.E.R.M.A.N. 3.0 STARTUP ****
Mon Oct 02 15:49:18 TestDevice01 super[24580]: Startup: Removing previous LaunchDaemon com.macjutsu.super.plist.
Mon Oct 02 15:49:18 TestDevice01 super[24580]: Status: Current GUI user name is "TestUser".
Mon Oct 02 15:49:18 TestDevice01 super[24580]: Startup: Deleting local preference for display accessory.
Mon Oct 02 15:49:18 TestDevice01 super[24580]: Startup: Deleting local preference for display accessory user authentication content.
Mon Oct 02 15:49:19 TestDevice01 super[24580]: Startup: Found saved credentials for local account "TestAdmin".
Mon Oct 02 15:49:19 TestDevice01 super[24580]: Startup: Validated saved credentials for local account "TestAdmin".
Mon Oct 02 15:49:19 TestDevice01 super[24580]: Startup: Apple Silicon Mac computer running macOS 13.4-22F66.
Mon Oct 02 15:49:19 TestDevice01 super[24580]: Startup: Last macOS startup was Mon Jul 24 09:48.
Mon Oct 02 15:49:19 TestDevice01 super[24580]: Startup: macOS update/upgrade workflows authenticated via local account.
Mon Oct 02 15:49:20 TestDevice01 super[24580]: Startup: Computer is currently managed by Jamf Pro version 10.50.
Mon Oct 02 15:49:20 TestDevice01 super[24580]: Startup: Creating fail-safe startup LaunchDaemon.
Mon Oct 02 15:49:20 TestDevice01 super[24580]: Status: LaunchDaemon com.macjutsu.super.plist is scheduled at next startup.
Mon Oct 02 15:49:20 TestDevice01 super[24580]: **** S.U.P.E.R.M.A.N. 3.0 CHECK SOFTWARE UPDATES/UPGRADE ****
Mon Oct 02 15:49:20 TestDevice01 super[24580]: Status: Last automatic software update check is older than 6 hours, full update/upgrade check required.
Mon Oct 02 15:49:20 TestDevice01 super[24580]: Status: Starting full check for software updates...
Mon Oct 02 15:49:28 TestDevice01 super[24580]: softwareupdate: Waiting for update list...
Mon Oct 02 15:49:28 TestDevice01 super[24580]: Status: 2 macOS versions available via softwareupdate.
Mon Oct 02 15:49:28 TestDevice01 super[24580]: Status: macOS update 1: macOS Sonoma 14.0-23A344
Mon Oct 02 15:49:28 TestDevice01 super[24580]: Status: macOS update 2: macOS Ventura 13.6-22G120
Mon Oct 02 15:49:28 TestDevice01 super[24580]: Status: macOS update available: macOS Ventura 13.6-22G120
Mon Oct 02 15:49:28 TestDevice01 super[24580]: Status: 1 available recommended (non-system) update(s).
Mon Oct 02 15:49:28 TestDevice01 super[24580]: Status: Recommended (non-system) update 1: Safari17.0VenturaAuto-17.0
Mon Oct 02 15:49:28 TestDevice01 super[24580]: Status: Starting full check for macOS upgrades...
Mon Oct 02 15:49:28 TestDevice01 super[24580]: mdmclient: Waiting for macOS upgrade list...
Mon Oct 02 15:49:32 TestDevice01 super[24580]: Error: Unable to find compatible macOS installers, trying again in 86400 seconds.
Mon Oct 02 15:49:32 TestDevice01 super[24580]: Status: Removing previous LaunchDaemon com.macjutsu.super.plist.
Mon Oct 02 15:49:33 TestDevice01 super[24580]: Exit: LaunchDaemon com.macjutsu.super.plist is scheduled to start at 15:49 on 10/3.
Mon Oct 02 15:49:33 TestDevice01 super[24580]: **** S.U.P.E.R.M.A.N. 3.0 EXIT ****

**Comment by Macjutsu** [comment]
This is a failure of v3 attempting to find new installers because you have the `--allow-upgrade` option enabled.

If you're unwilling to move to v4-betas then you need to disable the `--allow-upgrade` option.

I will not be updating/maintaining v3 going forward.

**Comment by yinfante356** [comment]
As i read, v4 has changed all settings. due to time constrains, is there an easy way to translate all the options i currently use on v3 to be repurposed for v4 ? additionally, when do you believe v4 will be official

**Comment by Macjutsu** [comment]
v4.0.0 (no beta) will drop as soon as I can test production macOS 14.1... also...

https://github.com/Macjutsu/super/blob/4.0.0-beta3/Super-Friends/super-3to4-migration-options.tsv
https://github.com/Macjutsu/super/blob/4.0.0-beta3/Super-Friends/super-3to4-migration-managed-preferences.tsv
