### ISSUE TITLE
Updated Jamf-Pro-External-Application-Custom-Schema

### ISSUE THREAD

**Issue by yinfante356** [Macjutsu/super#149]
Can we please get an updated Jamf-Pro-External-Application-Custom-Schema ? 

I cant seem to find neither of these two options in the most current schema "Jamf-Pro-External-Application-Custom-Schema-com.macjutsu.super-v4.0.0-beta2.json"

--auth-ask-user-to-save-password
--workflow-disable-relaunch

a workaround would also be appreciated. 

Thanks,

**Comment by yinfante356** [comment]
Basically Ive noticed v4 has a default schedule to automatically relaunch itself on an schedule. This is new to v4 so need a way to make SUPER stop starting after it has confirmed no more updates are available.

**Comment by Macjutsu** [comment]
Both this new behavior and the method to stop it are already documented in the Changelog: https://github.com/Macjutsu/super/blob/4.0.0-beta3/CHANGELOG.md

- New default behavior if no updates/upgrades are available (or allowed), `super` now automatically checks for new updates/upgrades on a reoccurring basis. Thus, the `--recheck-defer` option has been replaced by this default behavior.
...
- New `--deferral-timer-workflow-relaunch=minutes` option allows you to override the default check for new updates/upgrades deferral interval time of six hours (360 minutes).
- New `--workflow-disable-relaunch` option prevents `super` from checking for new updates/upgrades on a reoccurring basis.

**Comment by yinfante356** [comment]
do you mind explaining how i can use the --workflow-disable-relaunch from the configuration profile in Jamf ?  the --deferral-timer-workflow-relaunch is present in the schema so i can certainly use that short term but trying to figure out how to enforce the --workflow-disable-relaunch in my deployment. Thx

**Comment by Macjutsu** [comment]
All the options and managed preferences have always been available via `super --usage`. Also all options follow the same name schema:

Command option name -> managed preference name
`--super-option-name` -> `SuperOptionName`

**Comment by yinfante356** [comment]
Update.  I was able to get Super not to reschedule itself by manually adding a custom property named to the configuration profile in Jamf called  "WorkflowDisableRelaunch" and choosing Boolean set to True.
