### ISSUE TITLE
V4.0b3 - WorkflowAutomaticZeroDate reset after Last Apple software update check was more than 6 hours ago

### ISSUE THREAD

**Issue by master-vodawagner** [Macjutsu/super#150]
Noticing a possible bug whereby Super is resetting the WorkflowAutomaticZeroDate if the last check from Apple Software Update binary was more than 6 hours ago and the software update title hasn't changed. 

I started the process on Monday 2nd October at 1538BST, left the Mac offline over the night and powered on Tuesday 3rd October at 17:18 hoping to trigger a forced restart but super brought up a new dialog with a new WorkflowAutomaticZeroDate value.
 
Logging attached, this Mac did not see 14.1b2 which was later dropped so that wasn't the cause of the values resetting......

[super.log](https://github.com/Macjutsu/super/files/12795776/super.log)

**Comment by croaker-1** [comment]
In `main()` at line 7741
```
	if [[ "${test_mode_option}" != "TRUE" ]]; then
		log_super "**** S.U.P.E.R.M.A.N. ${SUPER_VERSION} - CHECK SOFTWARE UPDATES/UPGRADE ****"
		[[ "${workflow_software_full_check_required}" != "TRUE" ]] && check_software_stauts_caches
		workflow_check_asu
```
`check_software_stauts_caches()` sets `workflow_software_full_check_required` to `TRUE` if the last check is over 6 hours at line 3912

```
if [[ "${asu_last_sccessful_epoch}" -lt $(($(date "+%s")-21600)) ]]; then
	log_super "Status: Last Apple software update check was more than 6 hours ago, full update/upgrade check required."
	workflow_software_full_check_required="TRUE"
	return 0
fi
```

Then in workflow_check_asu(), if  `workflow_software_full_check_required` to 'TRUE` it resets the counters/zero date at line 4164

```
if [[ "${workflow_software_full_check_required}" == "TRUE" ]]; then
	log_super "Status: Starting full check for all available system software..."
	restart_deadline_counters
	restart_workflow_automatic_zero_date
	reset_software_status_caches
```

There is nothing in the `Check Apple software update cache` (line 3933) that would set `workflow_software_full_check_required` to 'FALSE` if the cache is unchanged. Not sure this would do the trick though. I've only had a chance to skim though the code and haven't had time to dig any deeper. Some other mechanism might be needed to enable a re-check without resetting the counters.

**Comment by croaker-1** [comment]
Looking at the code for v3.0 the behavior is similar except I don't see any explicit code to reset counters in the equivalent `checkSoftwareUpdates()` line 3755
```
if [[ "$fullCheckREQUIRED" == "TRUE" ]]; then
    sendToLog "Status: Starting full check for software updates..."
    listSoftwareUpdates
```
