### ISSUE TITLE
Can't Validate Erase-Install

### ISSUE THREAD

**Issue by djemaan** [Macjutsu/super#153]
Github is blocked for our users and the script is trying to validate erase-install as well as trying to download IBM Notifier from github. 

I deployed these through via Jamf Pro policy, and tried to by pass the validation with now luck. Keep getting error code:2
Would this script be able to be modified to allow for IBM notifier and Erase-install to be installed elsewhere instead of github?

a variable at the top to tell the script to look for the installs in github or to tell the script they are already installed?

**Comment by Macjutsu** [comment]
Your referencing v3 of `super` which has no support for macOS Sonoma.

If you plan to use or upgrade to Sonoma then you need to be using v4 which leverages `mist-cli`.

In either case, yes there are variables in the script that allow you to change the location and expected version of the helper apps.
