### ISSUE TITLE
V4.0b7 - MDM workflow failed but didn't prompt for user password - Failover set to Always

### ISSUE THREAD

**Issue by master-vodawagner** [Macjutsu/super#158]
Not sure why the failover to user password didn't occur, I've got it set to this in the config profile

<key>AuthMDMFailoverToUser</key>
<string>ALWAYS</string>

Output from the super.log from the last few lines before it stopped.

Sun Oct 22 21:47:03 super[2330]: Verbose Mode: Function install_macos_mdm: jamf_api_update_json is: { "devices": [ { "objectType": "COMPUTER",  "deviceId": "88" } ], "config": { "updateAction": "DOWNLOAD_INSTALL_RESTART", "versionType": "SPECIFIC_VERSION", "specificVersion": "14.1" } }
Sun Oct 22 21:47:04 super[2330]: Verbose Mode: Function install_macos_mdm: curl_response is:
201
Sun Oct 22 21:47:04 super[2330]: MDM: Successful macOS update/upgrade command request.
Sun Oct 22 21:47:04 super[2330]: Verbose Mode: Function install_macos_mdm: install_macos_mdm_api_error is: FALSE
Sun Oct 22 21:52:05 super[2330]: Verbose Mode: Function install_macos_mdm: install_macos_mdm_start_error is: TRUE
Sun Oct 22 21:52:05 super[2330]: Verbose Mode: Function install_macos_mdm: install_macos_mdm_start_error is: TRUE
Sun Oct 22 21:52:05 super[2330]: Verbose Mode: Function install_macos_mdm: install_macos_mdm_start_timeout is: 
Sun Oct 22 21:52:05 super[2330]: Verbose Mode: Function install_macos_mdm: install_macos_mdm_timeout_error is: 
Sun Oct 22 21:52:05 super[2330]: Verbose Mode: Function install_macos_mdm: install_macos_mdm_phase is: 
Sun Oct 22 21:52:05 super[2330]: Error: Push workflow for macOS update/upgrade via MDM failed.
Sun Oct 22 21:52:05 super[2330]: Error: Installation of macOS update/upgrade via MDM failed, trying again in 60 minutes.
Sun Oct 22 21:52:05 super[2330]: Verbose Mode: Function set_display_strings_language: display_string_workflow_title is: macOS Sonoma 14.1 Minor Update
Sun Oct 22 21:52:05 super[2330]: IBM Notifier: Failure notification.
Sun Oct 22 21:52:05 super[2330]: Verbose Mode: Function notification_failed: ibm_notifier_array is:
-type popup -bar_title macOS Sonoma 14.1 Minor Update Failed -subtitle The macOS Sonoma 14.1 Minor Update failed to complete.

The computer will not restart right now, but you will be notified later when the software update is attempted again. -icon_path /Library/Management/super/icon.png -icon_width 100 -icon_height 100 -main_button_label Defer 1 Hour
Sun Oct 22 21:52:05 super[2330]: Verbose Mode: Function set_auto_launch_deferral: deferral_timer_minutes is: 60
Sun Oct 22 21:52:05 super[2330]: Exit: super is scheduled to automatically relaunch at: 2023-10-22:22:52:00

**Comment by Macjutsu** [comment]
Thanks for the output from the super.log... can you please confirm earlier in the same log if the managed setting is in fact enabled? At the top of every `super` run in verbose mode it prints out the settings files.

**Comment by master-vodawagner** [comment]
Hello,

Yes it’s been picked up from /Library/Managed Preferences/com.macjutsu.super

AuthMDMFailoverToUser = ALWAYS;

**Comment by Macjutsu** [comment]
https://github.com/Macjutsu/super/releases/tag/v4.0.0-rc1
