### ISSUE TITLE
v4.0 - line 2322: sendToLog: command not found

### ISSUE THREAD

**Issue by blakeusblade** [Macjutsu/super#162]
Just after an IBM notifier update is attempted, the logs show "line 2322: sendToLog: command not found"

see below an example... Please note I've removed identifing things in the log

`Script result: Mon Oct 30 13:06:50 HOSTNAME GNU_SUPERMAN_4.0.sh[73915]: **** S.U.P.E.R.M.A.N. 4.0.0 - SUPER INSTALLATION WORKFLOW ****
Mon Oct 30 13:06:50 HOSTNAME GNU_SUPERMAN_4.0.sh[73915]: Installation: Copying super to: /Library/Management/super/super
Mon Oct 30 13:06:50 HOSTNAME GNU_SUPERMAN_4.0.sh[73915]: Installation: Creating super search path link: /usr/local/bin/super
Mon Oct 30 13:06:50 HOSTNAME GNU_SUPERMAN_4.0.sh[73915]: Installation: Creating super LaunchDaemon helper: /Library/Management/super/super-starter
Mon Oct 30 13:06:50 HOSTNAME GNU_SUPERMAN_4.0.sh[73915]: Installation: Removing previous super LaunchDaemon: /Library/LaunchDaemons/com.macjutsu.super.plist
Mon Oct 30 13:06:50 HOSTNAME GNU_SUPERMAN_4.0.sh[73915]: Installation: Creating super LaunchDaemon: /Library/LaunchDaemons/com.macjutsu.super.plist.
Mon Oct 30 13:06:50 HOSTNAME GNU_SUPERMAN_4.0.sh[73915]: Installation: Setting permissions for installed super items.
Mon Oct 30 13:06:50 HOSTNAME GNU_SUPERMAN_4.0.sh[73915]: Status: Archiving legacy super logs to: /Library/Management/super/logs-archive/2023-10-30.13-06-50.legacy.zip
Mon Oct 30 13:06:51 HOSTNAME GNU_SUPERMAN_4.0.sh[73915]: **** S.U.P.E.R.M.A.N. 4.0.0 - SUPER STARTUP WORKFLOW ****
Mon Oct 30 13:06:51 HOSTNAME GNU_SUPERMAN_4.0.sh[73915]: Status: Mac computer with Apple silicon running: macOS Ventura 13.6-22G120
Mon Oct 30 13:06:51 HOSTNAME GNU_SUPERMAN_4.0.sh[73915]: Status: Last macOS startup was: 2023-10-09:08:34:00
Mon Oct 30 13:06:51 HOSTNAME GNU_SUPERMAN_4.0.sh[73915]: Status: Current GUI user name: 
Mon Oct 30 13:06:51 HOSTNAME GNU_SUPERMAN_4.0.sh[73915]: Status: Deleting all local (non-authentication) preferences.
Mon Oct 30 13:06:52 HOSTNAME GNU_SUPERMAN_4.0.sh[73915]: Status: System is managed by Jamf Pro 11.0.1 hosted at:
Mon Oct 30 13:06:52 HOSTNAME GNU_SUPERMAN_4.0.sh[73915]: Status: No --display-icon-file icon found, copying default display icon from: /System/Library/PrivateFrameworks/SoftwareUpdate.framework/Versions/A/Resources/SoftwareUpdate.icns
Mon Oct 30 13:06:52 HOSTNAME GNU_SUPERMAN_4.0.sh[73915]: Warning: IBM Notifier at path: /Library/Management/super/IBM Notifier.app is version 2.9.1, this does not match target version 3.0.2.
Mon Oct 30 13:06:52 HOSTNAME GNU_SUPERMAN_4.0.sh[73915]: Status: Removing previously installed IBM Notifier.app.
Mon Oct 30 13:06:52 HOSTNAME GNU_SUPERMAN_4.0.sh[73915]: Status: Attempting to download and install IBM Notifier.app...
/Library/Application Support/JAMF/tmp/GNU_SUPERMAN_4.0.sh: line 2322: sendToLog: command not found
Mon Oct 30 13:06:53 HOSTNAME GNU_SUPERMAN_4.0.sh[73915]: Status: Validating new --auth-jamf-client credentials...
Mon Oct 30 13:06:55 HOSTNAME GNU_SUPERMAN_4.0.sh[73915]: Status: Saved new credentials for the --auth-jamf-client option.
Mon Oct 30 13:06:55 HOSTNAME GNU_SUPERMAN_4.0.sh[73915]: Status: macOS update/upgrade workflows automatically authenticated via Jamf Pro API with --auth-mdm-failover-to-user=ALWAYS.
Mon Oct 30 13:06:55 HOSTNAME GNU_SUPERMAN_4.0.sh[73915]: Status: Found that Jamf is installing or is the parent process, restarting via super LaunchDaemon...
Mon Oct 30 13:06:55 HOSTNAME GNU_SUPERMAN_4.0.sh[73915]: **** S.U.P.E.R.M.A.N. 4.0.0 - CLEAN EXIT ****`

**Comment by Macjutsu** [comment]
Thanks! Not sure how this one got past my first round of Find/Replace AND Shellcheck!

**Comment by Macjutsu** [comment]
https://github.com/Macjutsu/super/releases/tag/v4.0.1
