### ISSUE TITLE
Downloads Fail on Some Clients with sudo Usage Error

### ISSUE THREAD

**Issue by mjb-araymond** [Macjutsu/super#164]
I've seen this on a few clients, at first I thought it was related to 13.5, but I have found some 13.5 clients without this issue. I have yet to find a common link between affected clients.

The asu-workflow.log shows what appears to be a sudo usage error:
```
Tue Oct 31 08:51:41 MD-######## super[14040]: **** S.U.P.E.R.M.A.N. 4.0.0 - DOWNLOAD macOS Ventura 13.6.1 VIA SOFTWAREUPDATE START ****
usage: sudo -h | -K | -k | -V
usage: sudo -v [-AknS] [-g group] [-h host] [-p prompt] [-u user]
usage: sudo -l [-AknS] [-g group] [-h host] [-p prompt] [-U user] [-u user]
            [command]
usage: sudo [-AbEHknPS] [-C num] [-D directory] [-g group] [-h host] [-p
            prompt] [-R directory] [-T timeout] [-u user] [VAR=value] [-i|-s]
            [<command>]
usage: sudo -e [-AknS] [-C num] [-D directory] [-g group] [-h host] [-p prompt]
            [-R directory] [-T timeout] [-u user] file ...

Tue Oct 31 08:53:42 MD-######## super[14040]: Error: Download of macOS update/upgrade via softwareupdate failed to start after waiting for 120 seconds.
```

We are using super v4 with Jamf Pro 11.0.1 (cloud) with the new software update experience enabled. super is using Jamf API for authentication.

**Comment by Macjutsu** [comment]
Was the affected system at the login window?

**Comment by mjb-araymond** [comment]
Looks like that's the case. Spot checking a few more and seems no user logged in is the common thread.

**Comment by Macjutsu** [comment]
Thank you... you're not the first to find this...

**Comment by mjb-araymond** [comment]
Thanks for confirming it's not my config!

**Comment by Macjutsu** [comment]
https://github.com/Macjutsu/super/releases/tag/v4.0.1
