### ISSUE TITLE
Download macOS update/upgrade workflow failed, trying again in 60 minutes

### ISSUE THREAD

**Issue by Mitch260488** [Macjutsu/super#165]
happening on multiple Macs

**Comment by Macjutsu** [comment]
Closing this issue because you provided exactly zero evidence of the issue.

**Comment by Mitch260488** [comment]
What evidence do you need? 
![Screenshot 2023-10-31 at 14 14 58](https://github.com/Macjutsu/super/assets/135486972/2c1bc0ae-d084-4dfa-b73e-354544390b4d)

**Comment by Macjutsu** [comment]
Local super.log provides details required to troubleshoot.... but this is likely also a duplicate.
https://github.com/Macjutsu/super/issues/164

**Comment by Mitch260488** [comment]
t 31 11:25:45 LONPRO44 super[78178]: Status: A macOS major upgrade is available: macOS Sonoma 14.1
Tue Oct 31 11:25:45 LONPRO44 super[78178]: Status: A macOS major upgrade is available via Apple software update: macOS Sonoma 14.1-23B74
Tue Oct 31 11:25:45 LONPRO44 super[78178]: **** S.U.P.E.R.M.A.N. 4.0.0 - MACOS 14.1 MAJOR UPGRADE VIA SOFTWAREUPDATE ****
Tue Oct 31 11:25:45 LONPRO44 super[78178]: softwareupdate: Starting macOS Sonoma 14.1 download workflow, check /Library/Management/super/logs/asu-workflow.log for more detail.
Tue Oct 31 11:25:57 LONPRO44 super[78178]: Error: Unable to reach Apple software update servers.
Tue Oct 31 11:25:57 LONPRO44 super[78178]: Status: Restarting various softwareupdate daemon processes...
Tue Oct 31 11:26:02 LONPRO44 super[78178]: Error: Download macOS update/upgrade workflow failed, trying again in 60 minutes.
Tue Oct 31 11:26:02 LONPRO44 super[78178]: Exit: super is scheduled to automatically relaunch at: 2023-10-31:12:26:00
Tue Oct 31 11:26:02 LONPRO44 super[78178]: **** S.U.P.E.R.M.A.N. 4.0.0 - CLEAN EXIT ****
Tue Oct 31 12:35:54 LONPRO44 super-starter[80000]: **** S.U.P.E.R.M.A.N. 4.0.0 - LAUNCHDAEMON ****
Tue Oct 31 12:35:54 LONPRO44 super[80013]: **** S.U.P.E.R.M.A.N. 4.0.0 - SUPER STARTUP WORKFLOW ****
Tue Oct 31 12:35:54 LONPRO44 super[80013]: Status: Mac computer with Apple silicon running: macOS Ventura 13.6-22G120
Tue Oct 31 12:35:54 LONPRO44 super[80013]: Status: Last macOS startup was: 2023-09-30:10:43:00
Tue Oct 31 12:35:54 LONPRO44 super[80013]: Status: Current GUI user name: car
Tue Oct 31 12:35:56 LONPRO44 super[80013]: Status: System is managed by Jamf Pro 11.0.1 hosted at: https://consulum.tramscloud.co.uk/
Tue Oct 31 12:35:56 LONPRO44 super[80013]: Status: macOS update/upgrade workflows automatically authenticated via Jamf Pro API with --auth-mdm-failover-to-user=ALWAYS.
Tue Oct 31 12:35:56 LONPRO44 super[80013]: **** S.U.P.E.R.M.A.N. 4.0.0 - CHECK SOFTWARE UPDATES/UPGRADE ****
Tue Oct 31 12:35:56 LONPRO44 super[80013]: Status: Cached Apple software update list does not match the current list, full update/upgrade check required.
Tue Oct 31 12:35:57 LONPRO44 super[80013]: Status: Starting full check for all available system software...
Tue Oct 31 12:35:57 LONPRO44 super[80013]: softwareupdate: Waiting for available Apple software updates...
Tue Oct 31 12:36:11 LONPRO44 super[80013]: Status: 2 macOS versions available via Apple software update.
Tue Oct 31 12:36:11 LONPRO44 super[80013]: Status: macOS update/upgrade 1: macOS Sonoma 14.1-23B74
Tue Oct 31 12:36:11 LONPRO44 super[80013]: Status: macOS update/upgrade 2: macOS Ventura 13.6.1-22G313
Tue Oct 31 12:36:11 LONPRO44 super[80013]: Status: A macOS minor update is available: macOS Ventura 13.6.1-22G313
Tue Oct 31 12:36:11 LONPRO44 super[80013]: Status: 1 available non-system update(s).
Tue Oct 31 12:36:11 LONPRO44 super[80013]: Status: Recommended (non-system) update 1: Safari17.1VenturaAuto-17.1
Tue Oct 31 12:36:11 LONPRO44 super[80013]: mdmclient: Waiting for available macOS major upgrades...
Tue Oct 31 12:36:17 LONPRO44 super[80013]: Status: A macOS major upgrade is available: macOS Sonoma 14.1
Tue Oct 31 12:36:17 LONPRO44 super[80013]: Status: A macOS major upgrade is available via Apple software update: macOS Sonoma 14.1-23B74
Tue Oct 31 12:36:17 LONPRO44 super[80013]: **** S.U.P.E.R.M.A.N. 4.0.0 - MACOS 14.1 MAJOR UPGRADE VIA SOFTWAREUPDATE ****
Tue Oct 31 12:36:17 LONPRO44 super[80013]: softwareupdate: Starting macOS Sonoma 14.1 download workflow, check /Library/Management/super/logs/asu-workflow.log for more detail.
Tue Oct 31 12:36:28 LONPRO44 super[80013]: Error: Unable to reach Apple software update servers.
Tue Oct 31 12:36:28 LONPRO44 super[80013]: Status: Restarting various softwareupdate daemon processes...
Tue Oct 31 12:36:28 LONPRO44 super[80013]: Error: Download macOS update/upgrade workflow failed, trying again in 60 minutes.
Tue Oct 31 12:36:28 LONPRO44 super[80013]: Exit: super is scheduled to automatically relaunch at: 2023-10-31:13:36:00
Tue Oct 31 12:36:28 LONPRO44 super[80013]: **** S.U.P.E.R.M.A.N. 4.0.0 - CLEAN EXIT ****
Tue Oct 31 13:50:02 LONPRO44 super-starter[88687]: **** S.U.P.E.R.M.A.N. 4.0.0 - LAUNCHDAEMON ****
Tue Oct 31 13:50:02 LONPRO44 super[88701]: **** S.U.P.E.R.M.A.N. 4.0.0 - SUPER STARTUP WORKFLOW ****
Tue Oct 31 13:50:02 LONPRO44 super[88701]: Status: Mac computer with Apple silicon running: macOS Ventura 13.6-22G120
Tue Oct 31 13:50:02 LONPRO44 super[88701]: Status: Last macOS startup was: 2023-09-30:10:43:00
Tue Oct 31 13:50:02 LONPRO44 super[88701]: Status: Current GUI user name: car
Tue Oct 31 13:50:04 LONPRO44 super[88701]: Status: System is managed by Jamf Pro 11.0.1 hosted at: https://consulum.tramscloud.co.uk/
Tue Oct 31 13:50:04 LONPRO44 super[88701]: Status: macOS update/upgrade workflows automatically authenticated via Jamf Pro API with --auth-mdm-failover-to-user=ALWAYS.
Tue Oct 31 13:50:04 LONPRO44 super[88701]: **** S.U.P.E.R.M.A.N. 4.0.0 - CHECK SOFTWARE UPDATES/UPGRADE ****
Tue Oct 31 13:50:04 LONPRO44 super[88701]: Status: 2 macOS versions available via Apple software update.
Tue Oct 31 13:50:04 LONPRO44 super[88701]: Status: macOS update/upgrade 1: macOS Sonoma 14.1-23B74
Tue Oct 31 13:50:04 LONPRO44 super[88701]: Status: macOS update/upgrade 2: macOS Ventura 13.6.1-22G313
Tue Oct 31 13:50:04 LONPRO44 super[88701]: Status: A macOS minor update is available: macOS Ventura 13.6.1-22G313
Tue Oct 31 13:50:04 LONPRO44 super[88701]: Status: 1 available non-system update(s).
Tue Oct 31 13:50:04 LONPRO44 super[88701]: Status: Recommended (non-system) update 1: Safari17.1VenturaAuto-17.1
Tue Oct 31 13:50:04 LONPRO44 super[88701]: Status: A macOS major upgrade is available: macOS Sonoma 14.1
Tue Oct 31 13:50:04 LONPRO44 super[88701]: Status: A macOS major upgrade is available via Apple software update: macOS Sonoma 14.1-23B74
Tue Oct 31 13:50:04 LONPRO44 super[88701]: **** S.U.P.E.R.M.A.N. 4.0.0 - MACOS 14.1 MAJOR UPGRADE VIA SOFTWAREUPDATE ****
Tue Oct 31 13:50:04 LONPRO44 super[88701]: softwareupdate: Starting macOS Sonoma 14.1 download workflow, check /Library/Management/super/logs/asu-workflow.log for more detail.
Tue Oct 31 14:34:06 LONPRO44 super[88701]: Error: Unable to reach Apple software update servers.
Tue Oct 31 14:34:06 LONPRO44 super[88701]: Status: Restarting various softwareupdate daemon processes...
Tue Oct 31 14:34:06 LONPRO44 super[88701]: Error: Download macOS update/upgrade workflow failed, trying again in 60 minutes.
Tue Oct 31 14:34:06 LONPRO44 super[88701]: Exit: super is scheduled to automatically relaunch at: 2023-10-31:15:34:00
Tue Oct 31 14:34:06 LONPRO44 super[88701]: **** S.U.P.E.R.M.A.N. 4.0.0 - CLEAN EXIT ****

**Comment by Mitch260488** [comment]
Tue Oct 31 13:50:02 LONPRO44 super[88701]: **** S.U.P.E.R.M.A.N. 4.0.0 - SUPER STARTUP WORKFLOW ****
Tue Oct 31 13:50:02 LONPRO44 super[88701]: Status: Mac computer with Apple silicon running: macOS Ventura 13.6-22G120
Tue Oct 31 13:50:02 LONPRO44 super[88701]: Status: Last macOS startup was: 2023-09-30:10:43:00
Tue Oct 31 13:50:02 LONPRO44 super[88701]: Status: Current GUI user name: car
Tue Oct 31 13:50:04 LONPRO44 super[88701]: Status: System is
Tue Oct 31 13:50:04 LONPRO44 super[88701]: Status: macOS update/upgrade workflows automatically authenticated via Jamf Pro API with --auth-mdm-failover-to-user=ALWAYS.
Tue Oct 31 13:50:04 LONPRO44 super[88701]: **** S.U.P.E.R.M.A.N. 4.0.0 - CHECK SOFTWARE UPDATES/UPGRADE ****
Tue Oct 31 13:50:04 LONPRO44 super[88701]: Status: 2 macOS versions available via Apple software update.
Tue Oct 31 13:50:04 LONPRO44 super[88701]: Status: macOS update/upgrade 1: macOS Sonoma 14.1-23B74
Tue Oct 31 13:50:04 LONPRO44 super[88701]: Status: macOS update/upgrade 2: macOS Ventura 13.6.1-22G313
Tue Oct 31 13:50:04 LONPRO44 super[88701]: Status: A macOS minor update is available: macOS Ventura 13.6.1-22G313
Tue Oct 31 13:50:04 LONPRO44 super[88701]: Status: 1 available non-system update(s).
Tue Oct 31 13:50:04 LONPRO44 super[88701]: Status: Recommended (non-system) update 1: Safari17.1VenturaAuto-17.1
Tue Oct 31 13:50:04 LONPRO44 super[88701]: Status: A macOS major upgrade is available: macOS Sonoma 14.1
Tue Oct 31 13:50:04 LONPRO44 super[88701]: Status: A macOS major upgrade is available via Apple software update: macOS Sonoma 14.1-23B74
Tue Oct 31 13:50:04 LONPRO44 super[88701]: **** S.U.P.E.R.M.A.N. 4.0.0 - MACOS 14.1 MAJOR UPGRADE VIA SOFTWAREUPDATE ****
Tue Oct 31 13:50:04 LONPRO44 super[88701]: softwareupdate: Starting macOS Sonoma 14.1 download workflow, check /Library/Management/super/logs/asu-workflow.log for more detail.
Tue Oct 31 14:34:06 LONPRO44 super[88701]: Error: Unable to reach Apple software update servers.
Tue Oct 31 14:34:06 LONPRO44 super[88701]: Status: Restarting various softwareupdate daemon processes...
Tue Oct 31 14:34:06 LONPRO44 super[88701]: Error: Download macOS update/upgrade workflow failed, trying again in 60 minutes.
Tue Oct 31 14:34:06 LONPRO44 super[88701]: Exit: super is scheduled to automatically relaunch at: 2023-10-31:15:34:00
Tue Oct 31 14:34:06 LONPRO44 super[88701]: **** S.U.P.E.R.M.A.N. 4.0.0 - CLEAN EXIT **** (edited)
