### ISSUE TITLE
Support: Process for turning on Jamf Software Updates (beta)

### ISSUE THREAD

**Issue by blakeusblade** [Macjutsu/super#166]
What is the process for turning on software updates in jamf (in beta)... 

1. Does it affect any super workflows? 
2. The GUI says "Enabling this feature will cancel all x in flight upgrades (Does this mean it will cancel all the MDM commands in progress?) Will these affect any existing super workflows in progress?
3. How does super 4 work with jamf software updates (beta) ?

**Comment by Macjutsu** [comment]
1 and 3. Yes... `super` behaves identically except for the different permissions that are required if you enable the new method in Jamf Pro... as documented here: https://github.com/Macjutsu/super/wiki/Apple-Silicon-Jamf-Pro-API-Credentials#jamf-pro-api-required-privileges
2. Yes... as both stated in the Jamf GUI and documented here: https://learn.jamf.com/bundle/jamf-pro-documentation-current/page/Updating_macOS_Groups_Using_Beta_Managed_Software_Updates.html
