### ISSUE TITLE
Push workflow for macOS update/upgrade via MDM failed

### ISSUE THREAD

**Issue by mjb-araymond** [Macjutsu/super#167]
I seem to be having an issue where the MDM workflow is failing on all clients I spot check (macOS 13.5, 13.6, 14.0). Failover to user authentication is working as expected.
We are using super 4.0.1 and Jamf Pro 11.0.1 with the new software update experience. I've attached a (slightly sanitized) verbose super.log and TXT of our configuration profile. I'm at a loss at the moment, so any guidance/help is greatly appreciated.
[super.log](https://github.com/Macjutsu/super/files/13241216/super.log)
[super.txt](https://github.com/Macjutsu/super/files/13241274/super.txt)

**Comment by mjb-araymond** [comment]
Unfortunately Slack isn't an option for me while at work, but I completely understand. I'll review what you sent and will see if I can get help elsewhere.

**Comment by mjb-araymond** [comment]
Saw this was re-opened, so I'll share this update. I set up a new API role for the legacy SU and reverted back to the old SU in Jamf. super is now working without issue. We will likely wait for the new SU to lose the Beta tag before trying it again.

**Comment by Macjutsu** [comment]
As long as you plan on using `super` for your updates/upgrades, there is no benefit for using the new Beta method.
