### ISSUE TITLE
How can i remove initial screen. it's stuck for user's screen for long.

### ISSUE THREAD

**Issue by alavudeenrawther** [Macjutsu/super#168]
How can i remove initial screen. it's stuck for user's screen for long.

i want to avoid installing screen. Only need restart prompts to show to user. 

![sasi](https://github.com/Macjutsu/super/assets/59414585/dfc81dee-7570-47ef-8bc4-8c42e30c3905)

**Comment by Macjutsu** [comment]
That particular screen is from this feature... you can disable it.

https://github.com/Macjutsu/super/wiki/Updates-and-Upgrades#install-non-system-updates-without-restarting
