### ISSUE TITLE
Build Up of Log Files

### ISSUE THREAD

**Issue by dazrand** [Macjutsu/super#169]
As the documentation notes 'The super workflow never deletes any log file or log archive.'  This is causing issues on machines with smaller drives since these logs compound and quickly fill them. Suggest a profile setting to allow archive logs to either backup off machine, or automatically delete when either certain size thresholds or even date thresholds are met.

**Comment by Macjutsu** [comment]
The `super` log files shouldn't be that large... are you deploying with `--verbose-mode` enabled?

**Comment by dazrand** [comment]
I expect our IT team has verbose mode set and I have queried them to check. In this particular instance the archived log files are 114 GB.

**Comment by Macjutsu** [comment]
What a fun experiment they decided to run!  So yeah... the `--verbose-mode` option is for troubleshooting and should not be deployed.

**Comment by master-vodawagner** [comment]
I think the issue is the archive feature is zipping up previous compressed archives each time its used

**Comment by master-vodawagner** [comment]
Is it worth just putting a bit of code to delete excess archives for now? 100-200GB is a bit much lol

**Comment by Macjutsu** [comment]
I found the bug... it was a small typo... but the `zip` command is surprisingly aggressive! If you tell the `zip` command to compress a specific file... but it can't find it... it does the whole directory. That is why it's grabbing all the previous zips.

Also there is no such thing as "a bit of code to delete" when you are writing a script with root privileges. There is A LOT that your code can do wrong with that combination that you need to test the hell out of. In other words, short term I will fix the archive bug... but it will be a long-term feature to delete old archives.

**Comment by master-vodawagner** [comment]
Of course, you put a lot of effort into Super with the 8K lines of code :)

**Comment by Macjutsu** [comment]
https://github.com/Macjutsu/super/releases/tag/v4.0.2
