### ISSUE TITLE
/Library/Management/super/super-starter doesnt exist in v2

### ISSUE THREAD

**Issue by tkimpton** [Macjutsu/super#17]
/Library/Management/super/super-starter doesnt exist in v2 and so the launch daemon after the deferral does nothing.

**Comment by Macjutsu** [comment]
Not sure what your talking about here... as long as you follow the directions to let the script run on it's own (and don't try to install it via package) it will create all it's necessary assets as part of the script.

**Comment by tkimpton** [comment]
Problem as described. There are no instructions to say run the script as is and it will install the required components!

**Comment by Macjutsu** [comment]
It's documented right here: https://github.com/Macjutsu/super#installation

**Comment by tkimpton** [comment]
Thanks
