### ISSUE TITLE
Failure when running Non-System Apple Software Updates

### ISSUE THREAD

**Issue by reuven-cohen** [Macjutsu/super#171]
I have tried to run Non-System Apple Software Updates on both Super v3.0 and v4.0 yet it appears to keep failing.

Logs show failure\retry\failure then the "Installing Apple Software Updates" popup stays on screen and will not quit.

Aside from fixing the Non-System Apple Software Updates deployment, it's odd that the popup doesn't terminate and show an "Update Failed" prompt.

**LOGS:**
**asu-workflow.log**
Wed Nov 08 19:45:38 [SCRUBBED] super[88882]: **** S.U.P.E.R.M.A.N. 4.0.0 - INSTALL NON-SYSTEM UPDATES VIA SOFTWAREUPDATE START ****

Wed Nov 08 19:47:39 [SCRUBBED] super[88882]: **** S.U.P.E.R.M.A.N. 4.0.0 - INSTALL NON-SYSTEM UPDATES VIA SOFTWAREUPDATE FAILED ****

Wed Nov 08 19:47:39 [SCRUBBED] super[88882]: Error: Installation of non-system Apple software updates failed to start after waiting for 120 seconds.

Wed Nov 08 19:47:58 [SCRUBBED] super[88882]: **** S.U.P.E.R.M.A.N. 4.0.0 - INSTALL NON-SYSTEM UPDATES VIA SOFTWAREUPDATE START ****

Wed Nov 08 19:49:59 [SCRUBBED] super[88882]: **** S.U.P.E.R.M.A.N. 4.0.0 - INSTALL NON-SYSTEM UPDATES VIA SOFTWAREUPDATE FAILED ****

Wed Nov 08 19:49:59 [SCRUBBED] super[88882]: Error: Installation of non-system Apple software updates failed to start after waiting for 120 seconds.

**super.log**
Wed Nov 08 19:45:26 [SCRUBBED] super-starter[88834]: **** S.U.P.E.R.M.A.N. 4.0.0 - LAUNCHDAEMON ****
Wed Nov 08 19:45:28 [SCRUBBED] super[88882]: **** S.U.P.E.R.M.A.N. 4.0.0 - SUPER STARTUP WORKFLOW ****
Wed Nov 08 19:45:31 [SCRUBBED] super[88882]: Status: Mac computer with Apple silicon running: macOS Ventura 13.6-22G313
Wed Nov 08 19:45:31 [SCRUBBED] super[88882]: Status: Last macOS startup was: 2023-10-25:15:57:00
Wed Nov 08 19:45:31 [SCRUBBED] super[88882]: Status: Current GUI user name: [SCRUBBED]
Wed Nov 08 19:45:37 [SCRUBBED] super[88882]: Status: System is managed by Jamf Pro [SCRUBBED].[SCRUBBED].0 hosted at: https://[SCRUBBED].[SCRUBBED].[SCRUBBED]:[SCRUBBED]/
Wed Nov 08 19:45:37 [SCRUBBED] super[88882]: Status: macOS update/upgrade workflows automatically authenticated via Jamf Pro API with --auth-mdm-failover-to-user=NOSERVICE,SOFT,HARD,BOOTSTRAP.
Wed Nov 08 19:45:38 [SCRUBBED] super[88882]: **** S.U.P.E.R.M.A.N. 4.0.0 - CHECK SOFTWARE UPDATES/UPGRADE ****
Wed Nov 08 19:45:38 [SCRUBBED] super[88882]: Status: No available macOS minor updates or they may be deferred via configuration profile.
Wed Nov 08 19:45:38 [SCRUBBED] super[88882]: Status: 1 available non-system update(s).
Wed Nov 08 19:45:38 [SCRUBBED] super[88882]: Status: Recommended (non-system) update 1: Safari17.1VenturaAuto-17.1
Wed Nov 08 19:45:38 [SCRUBBED] super[88882]: Status: A macOS major upgrade is available: macOS Sonoma 14.1.1
Wed Nov 08 19:45:38 [SCRUBBED] super[88882]: Warning: To install macOS major upgrades you must enable the --install-macos-major-upgrades option.
Wed Nov 08 19:45:38 [SCRUBBED] super[88882]: Status: Restarting workflow automatic zero date.
Wed Nov 08 19:45:38 [SCRUBBED] super[88882]: Status: Restarting all deadline counters.
Wed Nov 08 19:45:38 [SCRUBBED] super[88882]: **** S.U.P.E.R.M.A.N. 4.0.0 - NON-SYSTEM SOFTWARE UPDATE ****
Wed Nov 08 19:45:38 [SCRUBBED] super[88882]: IBM Notifier: Installing non-system Apple software updates notification.
Wed Nov 08 19:45:38 [SCRUBBED] super[88882]: softwareupdate: Starting non-system Apple software updates installation workflow, check /Library/Management/super/logs/asu-workflow.log for more detail.
Wed Nov 08 19:47:39 [SCRUBBED] super[88882]: Error: Installation of non-system Apple software updates failed to start after waiting for 120 seconds.
Wed Nov 08 19:47:39 [SCRUBBED] super[88882]: Status: Restarting various softwareupdate daemon processes...
Wed Nov 08 19:47:41 [SCRUBBED] super[88882]: Status: Starting full check for all available system software...
Wed Nov 08 19:47:41 [SCRUBBED] super[88882]: softwareupdate: Waiting for available Apple software updates...
Wed Nov 08 19:47:54 [SCRUBBED] super[88882]: Status: No available macOS minor updates or they may be deferred via configuration profile.
Wed Nov 08 19:47:54 [SCRUBBED] super[88882]: Status: 1 available non-system update(s).
Wed Nov 08 19:47:54 [SCRUBBED] super[88882]: Status: Recommended (non-system) update 1: Safari17.1VenturaAuto-17.1
Wed Nov 08 19:47:54 [SCRUBBED] super[88882]: mdmclient: Waiting for available macOS major upgrades...
Wed Nov 08 19:47:58 [SCRUBBED] super[88882]: Status: A macOS major upgrade is available: macOS Sonoma 14.1.1
Wed Nov 08 19:47:58 [SCRUBBED] super[88882]: Warning: To install macOS major upgrades you must enable the --install-macos-major-upgrades option.
Wed Nov 08 19:47:58 [SCRUBBED] super[88882]: Warning: Failed to install all non-system Apple software updates.
Wed Nov 08 19:47:58 [SCRUBBED] super[88882]: softwareupdate: Starting non-system Apple software updates installation workflow, check /Library/Management/super/logs/asu-workflow.log for more detail.
Wed Nov 08 19:49:59 [SCRUBBED] super[88882]: Error: Installation of non-system Apple software updates failed to start after waiting for 120 seconds.
Wed Nov 08 19:49:59 [SCRUBBED] super[88882]: Status: Restarting various softwareupdate daemon processes...
Wed Nov 08 19:49:59 [SCRUBBED] super[88882]: Warning: Failed to install all non-system Apple software updates after multiple attempts, trying again in 60 minutes.
Wed Nov 08 19:49:59 [SCRUBBED] super[88882]: Exit: super is scheduled to automatically relaunch at: 2023-11-08:20:49:00
Wed Nov 08 19:49:59 [SCRUBBED] super[88882]: **** S.U.P.E.R.M.A.N. 4.0.0 - CLEAN EXIT ****

**Comment by Macjutsu** [comment]
Use v4.0.1...  and try again please.

**Comment by reuven-cohen** [comment]
Tested with v4.0.1. No luck.

    ASUListCache =     (
        "Safari17.1VenturaAuto",
        "MSU_UPDATE_23B81_patch_14.1.1_major"
    );
    AuthJamfClient = 1;
    AuthJamfComputerID = [Scrubbed];
    AuthMDMFailoverToUser = "NOSERVICE,SOFT,HARD,BOOTSTRAP";
    DeadlineCountFocus = 3;
    DeadlineCountSoft = 3;
    DeadlineDaysHard = 3;
    DeferralTimerMenu = "60,180,300,480,1440";
    DisplayHelpButtonString = "[Scrubbed]";
    DisplayIconFileCachedOrigin = "/System/Library/PrivateFrameworks/SoftwareUpdate.framework/Versions/A/Resources/SoftwareUpdate.icns";
    DisplayWarningButtonString = "https://support.apple.com/en-us/HT201222";
    InstallNonSystemUpdatesWithoutRestarting = 1;
    InstallRapidSecurityResponses = 1;
    MacLastStartup = "2023-10-25:15:57:00";
    NextAutoLaunch = "2023-11-09:16:17:00";
    SuperStatus = "Thu Nov 09 15:17:22: Pending: Failed to install all non-system Apple software updates after multiple attempts, trying again in 60 minutes.";
    SuperVersion = "4.0.1";
    VerboseMode = 1;
    macOSBetaProgramCache = 0;
    macOSNewestMarketingNameCache = "macOS Sonoma";
    macOSNewestVersionCache = "14.1.1";

**Comment by Macjutsu** [comment]
What does the asu-workflow.log show?

**Comment by reuven-cohen** [comment]
Same as before, and this is the output with Verbose logging enabled.

Thu Nov 09 15:13:01 [SCRUBBED] super[73962]: **** S.U.P.E.R.M.A.N. 4.0.1 - INSTALL NON-SYSTEM UPDATES VIA SOFTWAREUPDATE START ****

Thu Nov 09 15:15:01 [SCRUBBED] super[73962]: **** S.U.P.E.R.M.A.N. 4.0.1 - INSTALL NON-SYSTEM UPDATES VIA SOFTWAREUPDATE FAILED ****

Thu Nov 09 15:15:02 [SCRUBBED] super[73962]: Error: Installation of non-system Apple software updates failed to start after waiting for 120 seconds.

Thu Nov 09 15:15:22 [SCRUBBED] super[73962]: **** S.U.P.E.R.M.A.N. 4.0.1 - INSTALL NON-SYSTEM UPDATES VIA SOFTWAREUPDATE START ****

Thu Nov 09 15:17:22 [SCRUBBED] super[73962]: **** S.U.P.E.R.M.A.N. 4.0.1 - INSTALL NON-SYSTEM UPDATES VIA SOFTWAREUPDATE FAILED ****

Thu Nov 09 15:17:22 [SCRUBBED] super[73962]: Error: Installation of non-system Apple software updates failed to start after waiting for 120 seconds.

**Comment by Macjutsu** [comment]
What about the asu-list.log? It's strange because there's zero feedback from `softwareupdate` in that asu-workflow.log... not something I've ever seen.

**Comment by reuven-cohen** [comment]
asu-list.log

2023-11-09 15:40:05.797 softwareupdate[83052:41571858] XType: Using static font registry.
Software Update Tool

Finding available software
Software Update found the following new or updated software:
* Label: Safari17.1VenturaAuto-17.1
	Title: Safari, Version: 17.1, Size: 162063KiB, Recommended: YES,

**Comment by MatimusPrime** [comment]
Im seeing the same thing we had to turn off Non system updates and have folks do the 17.1  Safari update manually on 13.6.1

**Comment by Macjutsu** [comment]
So while I can't replicate non-macOS updates failing (they always seem to work for me)... there are improvements in the non-macOS update workflow that should prevent the notifications from "hanging".

https://github.com/Macjutsu/super/releases/tag/v4.0.2
