### ISSUE TITLE
WiKi Documentation update for Free Storage Space Testing Overrides

### ISSUE THREAD

**Issue by mauriciope** [Macjutsu/super#173]
The documentation at https://github.com/Macjutsu/super/wiki/Testing-and-Validation#free-storage-space-testing-overrides

Referes to 

Command option example for macOS upgrades:
`--free-space-upgrade=1000`

It should read 
Command option example for macOS upgrades:
`--test-storage-upgrade=1000`

**Comment by Macjutsu** [comment]
Thanks... it's fixed!

**Comment by mauriciope** [comment]
@Macjutsu 
Sorry, the WiKi has:
Command option example for macOS upgrades:
--test-space-upgrade=1000

The script is 
--test-storage-upgrade=gigabytes

**Comment by Macjutsu** [comment]
ok... now it's fixed... caffeine had not hit yet.

**Comment by mauriciope** [comment]
I know exactly that feeling. Apologies for the pingsThank you Regards




On Wednesday, November 15, 2023, 2:38 pm, Kevin M. White ***@***.***> wrote:




ok... now it's fixed... caffeine had not hit yet.
