### ISSUE TITLE
macOS Version # incorrect in logs

### ISSUE THREAD

**Issue by TechTrekkie** [Macjutsu/super#178]
I just stumbled across this in the logs and noticed the full version number isn't populating in the logs
I'm running macOS 14.1.1 build 23B81, however the log just shows 14.1
It doesn't appear to be negatively affecting how super runs

I've attached my super.log, you can see the example on line 3 where the version number is missing the last ".1"

[super.log](https://github.com/Macjutsu/super/files/13537457/super.log)

**Comment by Macjutsu** [comment]
https://github.com/Macjutsu/super/releases/tag/v4.0.3
