### ISSUE TITLE
MacOS/ SUPER claims that device is on the latest software version

### ISSUE THREAD

**Issue by Shabiboo** [Macjutsu/super#182]
We aim to have at least 95% of our devices updated to the latest minor version of MacOS by the end of this year. We deployed the super script on most of our users' machines.

We are seeing some increases in the sates of computers getting the latest software version. However, over 400 devices claim that they're on the newest version of MacOS, although they're not, and the following software checking is scheduled for the next day, which most often fails again.

Sometimes, I have been able to trigger the installation of an update by running "super --workflow-install-now" from the terminal. However, in most cases, it seems that the computer itself is unable to find any available MacOS updates because of a system failure and not something that's related to the super script. This issue is affecting our productivity, and I would like to know if there are any workarounds that can be deployed through MDM commands instead of having to contact each user individually.

**Comment by Shabiboo** [comment]
Here is another example of a computer that started downloading the minor version, but failed to complete it and super rested the deadline date twice. Is there any way to avoid this behavior?

Please see the attached screenshot, and log file.
![IMG_0976](https://github.com/Macjutsu/super/assets/153450600/ff226f6a-2df9-4913-9f45-362c37766ab3)
![IMG_0975](https://github.com/Macjutsu/super/assets/153450600/a5ac50b1-1b1b-4e0e-b2fd-a85708a1967b)
![IMG_0974](https://github.com/Macjutsu/super/assets/153450600/f1e59c90-3c41-4acc-b520-4c5c3c1bd557)

**Comment by Macjutsu** [comment]
As a reminder... `super` is asking the system `softwareupdate` service to download... if it can't download... the only thing `super` can do is try again later... you need to troubleshoot why the downloads are failing in the first place.

https://github.com/Macjutsu/super/wiki/Troubleshooting#understanding-sub-process-logs

**Comment by Macjutsu** [comment]
Please try the latest release of `super` as it may resolve this issue: https://github.com/Macjutsu/super/releases/tag/v4.1.0-beta1

**Comment by Macjutsu** [comment]
There are many updates in https://github.com/Macjutsu/super/releases/tag/v5.0.0-beta2 that may resolve this behavior. Please try it out.

**Comment by Macjutsu** [comment]
There have been so many changes to the latest version of `super` that I'm closing this issue.

https://github.com/Macjutsu/super/releases/tag/v5.0.0-beta3

If you find it persists with the latest builds of `super` please open a new issue.
