### ISSUE TITLE
Restart validation workflow may be running prematurely - OS 14.2.1 Super 4.0.3

### ISSUE THREAD

**Issue by KUSU2** [Macjutsu/super#185]
During the OS 14.2.1 rollout I'm seeing some odd logs involving the Restart Validation workflow that is supposed to submit inventory to Jamf after the install/reboot.  It looks like it is now kicking off before the OS finishes updating so it still thinks an update is there and errors out.

Super log

`Tue Dec 19 16:44:35 Test-User's Test-Mac1 super-starter[5083]: **** S.U.P.E.R.M.A.N. 4.0.3 - LAUNCHDAEMON ****
Tue Dec 19 16:44:35 Test-User's Test-Mac1 super[5096]: **** S.U.P.E.R.M.A.N. 4.0.3 - SUPER STARTUP WORKFLOW ****
Tue Dec 19 16:44:35 Test-User's Test-Mac1 super[5096]: Status: Mac computer with Apple silicon running: macOS Sonoma 14.2-23C64
Tue Dec 19 16:44:35 Test-User's Test-Mac1 super[5096]: Status: Last macOS startup was: 2023-12-19:15:27:00
Tue Dec 19 16:44:35 Test-User's Test-Mac1 super[5096]: Status: Current active GUI user is: Test-User (501)
Tue Dec 19 16:44:37 Test-User's Test-Mac1 super[5096]: Status: System is managed by Jamf Pro 11.1.3 hosted at: https://.jamfcloud.com/
Tue Dec 19 16:44:38 Test-User's Test-Mac1 super[5096]: Status: macOS update/upgrade workflows automatically authenticated via saved password for current user: Test-User
Tue Dec 19 16:44:38 Test-User's Test-Mac1 super[5096]: **** S.U.P.E.R.M.A.N. 4.0.3 - CHECK SOFTWARE UPDATES/UPGRADE ****
Tue Dec 19 16:44:38 Test-User's Test-Mac1 super[5096]: Status: No macOS beta program status cache, full update/upgrade check required.
Tue Dec 19 16:44:39 Test-User's Test-Mac1 super[5096]: Status: Starting full check for all available system software...
Tue Dec 19 16:44:39 Test-User's Test-Mac1 super[5096]: softwareupdate: Waiting for available Apple software updates...
Tue Dec 19 16:44:46 Test-User's Test-Mac1 super[5096]: Status: A macOS minor update is available: macOS Sonoma 14.2.1-23C71
Tue Dec 19 16:44:46 Test-User's Test-Mac1 super[5096]: Status: No available non-system Apple software updates or they may be deferred via configuration profile.
Tue Dec 19 16:44:46 Test-User's Test-Mac1 super[5096]: mdmclient: Waiting for available macOS major upgrades...
Tue Dec 19 16:44:48 Test-User's Test-Mac1 super[5096]: Status: No available macOS major upgrades or they may be deferred via configuration profile.
Tue Dec 19 16:44:48 Test-User's Test-Mac1 super[5096]: **** S.U.P.E.R.M.A.N. 4.0.3 - MACOS 14.2.1 MINOR UPDATE ****
Tue Dec 19 16:44:48 Test-User's Test-Mac1 super[5096]: softwareupdate: Starting macOS Sonoma 14.2.1 download workflow, check /Library/Management/super/logs/asu-workflow.log for more detail.
Tue Dec 19 16:44:58 Test-User's Test-Mac1 super[5096]: softwareupdate: macOS Sonoma 14.2.1 is downloading...
Tue Dec 19 16:45:35 Test-User's Test-Mac1 super[5096]: softwareupdate: macOS Sonoma 14.2.1 download complete, now preparing...
Tue Dec 19 16:50:29 Test-User's Test-Mac1 super[5096]: softwareupdate: macOS Sonoma 14.2.1 download and preparation complete.
Tue Dec 19 16:50:29 Test-User's Test-Mac1 super[5096]: Status: Setting new automatic zero date of: 2023-12-19:16:50.
Tue Dec 19 16:50:29 Test-User's Test-Mac1 super[5096]: Status: Restarting all deadline counters.
Tue Dec 19 16:50:29 Test-User's Test-Mac1 super[5096]: IBM Notifier: Restart or defer dialog with no timeout.
Tue Dec 19 16:50:35 Test-User's Test-Mac1 super[5096]: Status: User chose to restart now.
Tue Dec 19 16:50:36 Test-User's Test-Mac1 super[5096]: Status: Validated saved credentials for the current user: Test-User
Tue Dec 19 16:50:36 Test-User's Test-Mac1 super[5096]: IBM Notifier: Restart default notification.
Tue Dec 19 16:50:36 Test-User's Test-Mac1 super[5096]: softwareupdate: Starting macOS Sonoma 14.2.1-23C71 update workflow, check /Library/Management/super/logs/asu-workflow.log for more detail.
Tue Dec 19 16:50:54 Test-User's Test-Mac1 super[5096]: softwareupdate: macOS Sonoma 14.2.1 is downloading...
Tue Dec 19 16:50:54 Test-User's Test-Mac1 super[5096]: softwareupdate: macOS update/upgrade is prepared and ready for restart!
Tue Dec 19 16:50:54 Test-User's Test-Mac1 super[5096]: Exit: Full super workflow complete! macOS update/upgrade restart is imminent and the super restart validation workflow is scheduled to automatically relaunch at next startup.
Tue Dec 19 16:50:54 Test-User's Test-Mac1 super[5096]: **** S.U.P.E.R.M.A.N. 4.0.3 - CLEAN EXIT ****
Tue Dec 19 16:51:35 Test-User's Test-Mac1 super-starter[19354]: **** S.U.P.E.R.M.A.N. 4.0.3 - LAUNCHDAEMON ****
Tue Dec 19 16:51:35 Test-User's Test-Mac1 super[19376]: **** S.U.P.E.R.M.A.N. 4.0.3 - SUPER STARTUP WORKFLOW ****
Tue Dec 19 16:51:36 Test-User's Test-Mac1 super[19376]: Status: Mac computer with Apple silicon running: macOS Sonoma 14.2-23C64
Tue Dec 19 16:51:36 Test-User's Test-Mac1 super[19376]: Status: Last macOS startup was: 2023-12-19:15:27:00
Tue Dec 19 16:51:36 Test-User's Test-Mac1 super[19376]: Status: No GUI user currently logged in.
Tue Dec 19 16:51:38 Test-User's Test-Mac1 super[19376]: Status: System is managed by Jamf Pro 11.1.3 hosted at: https://.jamfcloud.com/
Tue Dec 19 16:51:38 Test-User's Test-Mac1 super[19376]: Warning: No currently logged in user, unable to the check status of the --auth-ask-user-to-save-password option.
Tue Dec 19 16:51:38 Test-User's Test-Mac1 super[19376]: Warning: Automatic macOS update/upgrade enforcement on Apple Silicon computers requires authentication credentials.
Tue Dec 19 16:51:38 Test-User's Test-Mac1 super[19376]: Auth Error: No current active user to provide local authentication.
Tue Dec 19 16:51:38 Test-User's Test-Mac1 super[19376]: Warning: Configured authentication workflow can not currently install macOS updates/upgrades.
Tue Dec 19 16:51:38 Test-User's Test-Mac1 super[19376]: **** S.U.P.E.R.M.A.N. 4.0.3 - RESTART VALIDATION WORKFLOW ****
Tue Dec 19 16:51:39 Test-User's Test-Mac1 super[19376]: Status: Starting full check for all available system software...
Tue Dec 19 16:51:39 Test-User's Test-Mac1 super[19376]: softwareupdate: Waiting for available Apple software updates...
Tue Dec 19 16:51:43 Test-User's Test-Mac1 super[19376]: Status: A macOS minor update is available: macOS Sonoma 14.2.1-23C71
Tue Dec 19 16:51:43 Test-User's Test-Mac1 super[19376]: Status: No available non-system Apple software updates or they may be deferred via configuration profile.
Tue Dec 19 16:51:43 Test-User's Test-Mac1 super[19376]: mdmclient: Waiting for available macOS major upgrades...
Tue Dec 19 16:51:48 Test-User's Test-Mac1 super[19376]: Status: No available macOS major upgrades or they may be deferred via configuration profile.
Tue Dec 19 16:51:48 Test-User's Test-Mac1 super[19376]: Warning: Some Apple software updates/upgrades did not complete after last restart, continuing workflow.
Tue Dec 19 16:51:48 Test-User's Test-Mac1 super[19376]: Status: Submitting updated inventory to Jamf Pro. Use --verbose-mode or check /var/log/jamf.log for more detail...
Tue Dec 19 16:52:10 Test-User's Test-Mac1 super[19376]: Status: Running Jamf Pro check-in policies. Use --verbose-mode or check /var/log/jamf.log for more detail...
Tue Dec 19 16:52:14 Test-User's Test-Mac1 super[19376]: Workflow Error: Configured authentication workflow is not currently possible, trying again in 60 minutes.
Tue Dec 19 16:52:14 Test-User's Test-Mac1 super[19376]: Exit: super is scheduled to automatically relaunch at: 2023-12-19:17:52:00
Tue Dec 19 16:52:14 Test-User's Test-Mac1 super[19376]: **** S.U.P.E.R.M.A.N. 4.0.3 - CLEAN EXIT ****`

Apple Install log

`2023-12-19 16:50:55-07 Test-User's Test-Mac1 Installer Progress[19303]: Progress app is running…
2023-12-19 16:51:38-07 Test-User's Test-Mac1 softwareupdated[333]: Adding client SUUpdateServiceClient pid=19819, uid=0, installAuth=NO rights=(), transactions=0 (/usr/libexec/mdmclient)
2023-12-19 16:51:38-07 Test-User's Test-Mac1 softwareupdated[333]: SoftwareUpdate: Fired early. Next check=12/20/23, 12:06‚ÄØAM (interval=86280.000000, A/C=YES)
2023-12-19 16:51:38-07 Test-User's Test-Mac1 softwareupdated[333]: SoftwareUpdate: Fired early. Next check=12/20/23, 12:06‚ÄØAM (interval=86280.000000, A/C=YES)
2023-12-19 16:51:39-07 Test-User's Test-Mac1 softwareupdate[19845]: Starting softwareupdate CLI tool
2023-12-19 16:51:39-07 Test-User's Test-Mac1 softwareupdate[19845]: CLI invoked by parent pid 19842 (/usr/bin/sudo) with arguments: (
	    "/usr/sbin/softwareupdate",
	    "--list"
	)
2023-12-19 16:51:43-07 Test-User's Test-Mac1 softwareupdate[19845]: CLI scan returned: (
	    "<SUOSUProduct: MSU_UPDATE_23C71_patch_14.2.1_minor>"
	)
2023-12-19 16:51:50-07 Test-User's Test-Mac1 softwareupdate[20089]: CLI invoked by parent pid 20057 (/usr/local/jamf/bin/jamf) with arguments: (
	    "/usr/sbin/softwareupdate",
	    "-l"
	)
2023-12-19 16:51:52-07 Test-User's Test-Mac1 softwareupdated[333]: SUOSUServiceDaemon: availableMobileSoftwareUpdates = (
	    "<SUOSUProduct: MSU_UPDATE_23C71_patch_14.2.1_minor>"
	)
2023-12-19 16:51:52-07 Test-User's Test-Mac1 softwareupdated[333]: SUOSUServiceDaemon: Setting availableMobileSoftwareUpdates = (
	    "<SUOSUProduct: MSU_UPDATE_23C71_patch_14.2.1_minor>"
	)
2023-12-19 16:52:31-07 Test-User's Test-Mac1 softwareupdated[333]: SUUpdateServiceDaemon: Rebooting (success = 1, nightInstall = 0, displayAsleep = 0, shutdown = 0)
Dec 19 23:53:47 Test-User's Test-Mac1 Installer Progress[64]: IASGetCurrentInstallPhase: Current phase name is "Software Update Post Logout"
2023-12-19 16:54:26-07 Test-User's Test-Mac1 softwareupdated[739]: softwareupdated: Starting with build 14.2.1 (23C71)
2023-12-19 16:54:33-07 Test-User's Test-Mac1 softwareupdated[739]: Previous System Version : 14.2 (23C64), Current System Version : 14.2.1 (23C71)`

It looks like the restart validation tried to kick-off while 14.2.1 was still installing which would cause it to detect the 14.2.1 update still available.  The Jamf inventory upload task completes with 14.2 prematurely and then it goes into workflow error because no user is available to authenticate (starting the one hour error-defer).  This basically puts super back into an update workflow until a user logs in again (it thinks it did not complete an update).  The Mac Logs switch to universal time during the last part of the OS update for some reason.

Super Workflow Error

`Tue Dec 19 17:54:33 Test-User's Test-Mac1 super[1866]: Status: Mac computer with Apple silicon running: macOS Sonoma 14.2.1-23C71
Tue Dec 19 17:54:35 Test-User's Test-Mac1 super[1866]: Workflow Error: Configured authentication workflow is not currently possible, trying again in 60 minutes.
Tue Dec 19 17:54:35 Test-User's Test-Mac1 super[1866]: Exit: super is scheduled to automatically relaunch at: 2023-12-19:18:54:00
Tue Dec 19 19:18:11 Test-User's Test-Mac1 super[2729]: Exit: super is scheduled to automatically relaunch at: 2023-12-19:20:18:00
Wed Dec 20 09:13:08 Test-User's Test-Mac1 super[11980]: **** S.U.P.E.R.M.A.N. 4.0.3 - CHECK SOFTWARE UPDATES/UPGRADE ****
Wed Dec 20 09:13:08 Test-User's Test-Mac1 super[11980]: **** S.U.P.E.R.M.A.N. 4.0.3 - CLEAN EXIT ****`

Since the OS update completed after the premature restart workflow there is no new update to install so no Jamf inventory task to run.

**Comment by Macjutsu** [comment]
These logs are unreadable because how you posted them removed all the line returns... can you please resubmit by either attaching the logs themselves as text files or using the code block format.

```
This is an example of a code block.
Multiple lines forming a single bock of code/log output.
```

`Instead of individual lines of code.`
`This is not useable when there are large amounts of text to review. `

**Comment by KUSU2** [comment]
Fixed logs.  I was able to get a log from an Intel Mac and the restart validation workflow did complete correctly after the update finished, so this may be limited to apple silicon.

It looks like the restart validation workflow tried to run at 16:51 but the update did not finish until 16:54.  Super went into standby mode after the user logged in the next day at 9:13.

```
Super log

Tue Dec 19 16:44:35 Test-User's Test-Mac1 super-starter[5083]: **** S.U.P.E.R.M.A.N. 4.0.3 - LAUNCHDAEMON ****
Tue Dec 19 16:44:35 Test-User's Test-Mac1 super[5096]: **** S.U.P.E.R.M.A.N. 4.0.3 - SUPER STARTUP WORKFLOW ****
Tue Dec 19 16:44:35 Test-User's Test-Mac1 super[5096]: Status: Mac computer with Apple silicon running: macOS Sonoma 14.2-23C64
Tue Dec 19 16:44:35 Test-User's Test-Mac1 super[5096]: Status: Last macOS startup was: 2023-12-19:15:27:00
Tue Dec 19 16:44:35 Test-User's Test-Mac1 super[5096]: Status: Current active GUI user is: Test-User (501)
Tue Dec 19 16:44:37 Test-User's Test-Mac1 super[5096]: Status: System is managed by Jamf Pro 11.1.3 hosted at: https://.jamfcloud.com/
Tue Dec 19 16:44:38 Test-User's Test-Mac1 super[5096]: Status: macOS update/upgrade workflows automatically authenticated via saved password for current user: Test-User
Tue Dec 19 16:44:38 Test-User's Test-Mac1 super[5096]: **** S.U.P.E.R.M.A.N. 4.0.3 - CHECK SOFTWARE UPDATES/UPGRADE ****
Tue Dec 19 16:44:38 Test-User's Test-Mac1 super[5096]: Status: No macOS beta program status cache, full update/upgrade check required.
Tue Dec 19 16:44:39 Test-User's Test-Mac1 super[5096]: Status: Starting full check for all available system software...
Tue Dec 19 16:44:39 Test-User's Test-Mac1 super[5096]: softwareupdate: Waiting for available Apple software updates...
Tue Dec 19 16:44:46 Test-User's Test-Mac1 super[5096]: Status: A macOS minor update is available: macOS Sonoma 14.2.1-23C71
Tue Dec 19 16:44:46 Test-User's Test-Mac1 super[5096]: Status: No available non-system Apple software updates or they may be deferred via configuration profile.
Tue Dec 19 16:44:46 Test-User's Test-Mac1 super[5096]: mdmclient: Waiting for available macOS major upgrades...
Tue Dec 19 16:44:48 Test-User's Test-Mac1 super[5096]: Status: No available macOS major upgrades or they may be deferred via configuration profile.
Tue Dec 19 16:44:48 Test-User's Test-Mac1 super[5096]: **** S.U.P.E.R.M.A.N. 4.0.3 - MACOS 14.2.1 MINOR UPDATE ****
Tue Dec 19 16:44:48 Test-User's Test-Mac1 super[5096]: softwareupdate: Starting macOS Sonoma 14.2.1 download workflow, check /Library/Management/super/logs/asu-workflow.log for more detail.
Tue Dec 19 16:44:58 Test-User's Test-Mac1 super[5096]: softwareupdate: macOS Sonoma 14.2.1 is downloading...
Tue Dec 19 16:45:35 Test-User's Test-Mac1 super[5096]: softwareupdate: macOS Sonoma 14.2.1 download complete, now preparing...
Tue Dec 19 16:50:29 Test-User's Test-Mac1 super[5096]: softwareupdate: macOS Sonoma 14.2.1 download and preparation complete.
Tue Dec 19 16:50:29 Test-User's Test-Mac1 super[5096]: Status: Setting new automatic zero date of: 2023-12-19:16:50.
Tue Dec 19 16:50:29 Test-User's Test-Mac1 super[5096]: Status: Restarting all deadline counters.
Tue Dec 19 16:50:29 Test-User's Test-Mac1 super[5096]: IBM Notifier: Restart or defer dialog with no timeout.
Tue Dec 19 16:50:35 Test-User's Test-Mac1 super[5096]: Status: User chose to restart now.
Tue Dec 19 16:50:36 Test-User's Test-Mac1 super[5096]: Status: Validated saved credentials for the current user: Test-User
Tue Dec 19 16:50:36 Test-User's Test-Mac1 super[5096]: IBM Notifier: Restart default notification.
Tue Dec 19 16:50:36 Test-User's Test-Mac1 super[5096]: softwareupdate: Starting macOS Sonoma 14.2.1-23C71 update workflow, check /Library/Management/super/logs/asu-workflow.log for more detail.
Tue Dec 19 16:50:54 Test-User's Test-Mac1 super[5096]: softwareupdate: macOS Sonoma 14.2.1 is downloading...
Tue Dec 19 16:50:54 Test-User's Test-Mac1 super[5096]: softwareupdate: macOS update/upgrade is prepared and ready for restart!
Tue Dec 19 16:50:54 Test-User's Test-Mac1 super[5096]: Exit: Full super workflow complete! macOS update/upgrade restart is imminent and the super restart validation workflow is scheduled to automatically relaunch at next startup.
Tue Dec 19 16:50:54 Test-User's Test-Mac1 super[5096]: **** S.U.P.E.R.M.A.N. 4.0.3 - CLEAN EXIT ****
Tue Dec 19 16:51:35 Test-User's Test-Mac1 super-starter[19354]: **** S.U.P.E.R.M.A.N. 4.0.3 - LAUNCHDAEMON ****
Tue Dec 19 16:51:35 Test-User's Test-Mac1 super[19376]: **** S.U.P.E.R.M.A.N. 4.0.3 - SUPER STARTUP WORKFLOW ****
Tue Dec 19 16:51:36 Test-User's Test-Mac1 super[19376]: Status: Mac computer with Apple silicon running: macOS Sonoma 14.2-23C64
Tue Dec 19 16:51:36 Test-User's Test-Mac1 super[19376]: Status: Last macOS startup was: 2023-12-19:15:27:00
Tue Dec 19 16:51:36 Test-User's Test-Mac1 super[19376]: Status: No GUI user currently logged in.
Tue Dec 19 16:51:38 Test-User's Test-Mac1 super[19376]: Status: System is managed by Jamf Pro 11.1.3 hosted at: https://.jamfcloud.com/
Tue Dec 19 16:51:38 Test-User's Test-Mac1 super[19376]: Warning: No currently logged in user, unable to the check status of the --auth-ask-user-to-save-password option.
Tue Dec 19 16:51:38 Test-User's Test-Mac1 super[19376]: Warning: Automatic macOS update/upgrade enforcement on Apple Silicon computers requires authentication credentials.
Tue Dec 19 16:51:38 Test-User's Test-Mac1 super[19376]: Auth Error: No current active user to provide local authentication.
Tue Dec 19 16:51:38 Test-User's Test-Mac1 super[19376]: Warning: Configured authentication workflow can not currently install macOS updates/upgrades.
Tue Dec 19 16:51:38 Test-User's Test-Mac1 super[19376]: **** S.U.P.E.R.M.A.N. 4.0.3 - RESTART VALIDATION WORKFLOW ****
Tue Dec 19 16:51:39 Test-User's Test-Mac1 super[19376]: Status: Starting full check for all available system software...
Tue Dec 19 16:51:39 Test-User's Test-Mac1 super[19376]: softwareupdate: Waiting for available Apple software updates...
Tue Dec 19 16:51:43 Test-User's Test-Mac1 super[19376]: Status: A macOS minor update is available: macOS Sonoma 14.2.1-23C71
Tue Dec 19 16:51:43 Test-User's Test-Mac1 super[19376]: Status: No available non-system Apple software updates or they may be deferred via configuration profile.
Tue Dec 19 16:51:43 Test-User's Test-Mac1 super[19376]: mdmclient: Waiting for available macOS major upgrades...
Tue Dec 19 16:51:48 Test-User's Test-Mac1 super[19376]: Status: No available macOS major upgrades or they may be deferred via configuration profile.
Tue Dec 19 16:51:48 Test-User's Test-Mac1 super[19376]: Warning: Some Apple software updates/upgrades did not complete after last restart, continuing workflow.
Tue Dec 19 16:51:48 Test-User's Test-Mac1 super[19376]: Status: Submitting updated inventory to Jamf Pro. Use --verbose-mode or check /var/log/jamf.log for more detail...
Tue Dec 19 16:52:10 Test-User's Test-Mac1 super[19376]: Status: Running Jamf Pro check-in policies. Use --verbose-mode or check /var/log/jamf.log for more detail...
Tue Dec 19 16:52:14 Test-User's Test-Mac1 super[19376]: Workflow Error: Configured authentication workflow is not currently possible, trying again in 60 minutes.
Tue Dec 19 16:52:14 Test-User's Test-Mac1 super[19376]: Exit: super is scheduled to automatically relaunch at: 2023-12-19:17:52:00
Tue Dec 19 16:52:14 Test-User's Test-Mac1 super[19376]: **** S.U.P.E.R.M.A.N. 4.0.3 - CLEAN EXIT ****

Apple Install log

2023-12-19 16:50:55-07 Test-User's Test-Mac1 Installer Progress[19303]: Progress app is running…
2023-12-19 16:51:38-07 Test-User's Test-Mac1 softwareupdated[333]: Adding client SUUpdateServiceClient pid=19819, uid=0, installAuth=NO rights=(), transactions=0 (/usr/libexec/mdmclient)
2023-12-19 16:51:38-07 Test-User's Test-Mac1 softwareupdated[333]: SoftwareUpdate: Fired early. Next check=12/20/23, 12:06‚ÄØAM (interval=86280.000000, A/C=YES)
2023-12-19 16:51:38-07 Test-User's Test-Mac1 softwareupdated[333]: SoftwareUpdate: Fired early. Next check=12/20/23, 12:06‚ÄØAM (interval=86280.000000, A/C=YES)
2023-12-19 16:51:39-07 Test-User's Test-Mac1 softwareupdate[19845]: Starting softwareupdate CLI tool
2023-12-19 16:51:39-07 Test-User's Test-Mac1 softwareupdate[19845]: CLI invoked by parent pid 19842 (/usr/bin/sudo) with arguments: (
	    "/usr/sbin/softwareupdate",
	    "--list"
	)
2023-12-19 16:51:43-07 Test-User's Test-Mac1 softwareupdate[19845]: CLI scan returned: (
	    "<SUOSUProduct: MSU_UPDATE_23C71_patch_14.2.1_minor>"
	)
2023-12-19 16:51:50-07 Test-User's Test-Mac1 softwareupdate[20089]: CLI invoked by parent pid 20057 (/usr/local/jamf/bin/jamf) with arguments: (
	    "/usr/sbin/softwareupdate",
	    "-l"
	)
2023-12-19 16:51:52-07 Test-User's Test-Mac1 softwareupdated[333]: SUOSUServiceDaemon: availableMobileSoftwareUpdates = (
	    "<SUOSUProduct: MSU_UPDATE_23C71_patch_14.2.1_minor>"
	)
2023-12-19 16:51:52-07 Test-User's Test-Mac1 softwareupdated[333]: SUOSUServiceDaemon: Setting availableMobileSoftwareUpdates = (
	    "<SUOSUProduct: MSU_UPDATE_23C71_patch_14.2.1_minor>"
	)
2023-12-19 16:52:31-07 Test-User's Test-Mac1 softwareupdated[333]: SUUpdateServiceDaemon: Rebooting (success = 1, nightInstall = 0, displayAsleep = 0, shutdown = 0)
Dec 19 23:53:47 Test-User's Test-Mac1 Installer Progress[64]: IASGetCurrentInstallPhase: Current phase name is "Software Update Post Logout"
2023-12-19 16:54:26-07 Test-User's Test-Mac1 softwareupdated[739]: softwareupdated: Starting with build 14.2.1 (23C71)
2023-12-19 16:54:33-07 Test-User's Test-Mac1 softwareupdated[739]: Previous System Version : 14.2 (23C64), Current System Version : 14.2.1 (23C71)

Super Workflow Error

Tue Dec 19 17:54:33 Test-User's Test-Mac1 super[1866]: Status: Mac computer with Apple silicon running: macOS Sonoma 14.2.1-23C71
Tue Dec 19 17:54:35 Test-User's Test-Mac1 super[1866]: Workflow Error: Configured authentication workflow is not currently possible, trying again in 60 minutes.
Tue Dec 19 17:54:35 Test-User's Test-Mac1 super[1866]: Exit: super is scheduled to automatically relaunch at: 2023-12-19:18:54:00
Tue Dec 19 19:18:11 Test-User's Test-Mac1 super[2729]: Exit: super is scheduled to automatically relaunch at: 2023-12-19:20:18:00
Wed Dec 20 09:13:08 Test-User's Test-Mac1 super[11980]: **** S.U.P.E.R.M.A.N. 4.0.3 - CHECK SOFTWARE UPDATES/UPGRADE ****
Wed Dec 20 09:13:08 Test-User's Test-Mac1 super[11980]: **** S.U.P.E.R.M.A.N. 4.0.3 - CLEAN EXIT ****

**Comment by Macjutsu** [comment]
So according to those logs... the problem looks like `softwareupdate` is restarting the computer but not applying the update.

Thus, on the restart validation `super` properly recognizing that the system did not apply the update.

Further, looks like you're relying on user-based authentication but no user is logged in... so all `super` can do is try again later.

In other words, there does not appear to be any `super` issue here... this is a sub-process not doing it's job: https://github.com/Macjutsu/super/wiki/Troubleshooting#understanding-sub-process-logs

**Comment by KUSU2** [comment]
16:50:54 - Update workflow completes and an authenticated restart.
16:51:35 - Launchdaemon runs
16:51:38 - RESTART VALIDATION workflow runs
16:51:48 - Update workflow error (update is still running in the background), Inventory is still submitted to Jamf at this point.
16:52:14 - `super` goes into defer error mode (60 minute retry attempts) since it still thinks there as update to try.

Here is the System.log.

16:50:54 - sessionlogoutd
16:50:55 - Software Update Post Logout
16:52:32 - SHUTDOWN_TIME
16:53:43 - BOOT_TIME
16:54:37 - Boot-Time Installation
16:54:39 - loginwindow Boot

According to the system.log there was only one reboot at 16:50:54, so what is even kicking off the launchdaemon at 16:51:35?  This is during the update installation which happened between 16:50:55 and 16:54:39, so the launchdaemon shouldn't even be running until after 16:54:39.

**Comment by Macjutsu** [comment]
Aaaaaand I'm back.

So the LD runs every 60 seconds... but it doesn't directly run `super`... instead it runs `super-starter`... if you look at that there are several conditions that prevent the actual `super` script from running again. One of those conditions is to facilitate the "restart validation". The logic is to look for the "restart validation" file and if the system restart date hasn't changed since that file was made.

The only thing I can guess is that there was a problem with the code used to check on the system restart date/time?

To be clear I've never seen this error.

**Comment by KUSU2** [comment]
Does a network change affect the workflow?  Most of our wireless fleet, if they are at the office are on secure wifi which can drop briefly during a logout/in.  If the network drops would that trick the script into thinking a reboot had happened?

**Comment by KUSU2** [comment]
Just ran through for 14.3 and same behavior, the script is trying to run the restart workflow before the update completes. (Reboot prompt>during reboot process launchdaemon runs for some reason which wrongly hits the restart validation which sits in error state because no current user anymore.  The launchdaemon then goes into the error workflow (60 minute wait) and will eventually run but since restart validation is what flags to run jamf recon, it never uploads inventory.  The 60 minute timer hits and super will detect no updates now and go into rest state.

**Comment by KUSU2** [comment]
Appending a valid "MacLastStartup" date did force the workflow to actually complete, so this looks like a bug with the script pulling startup dates.

**Comment by Macjutsu** [comment]
Please try the latest release of `super` as it may resolve this issue: https://github.com/Macjutsu/super/releases/tag/v4.1.0-beta1

**Comment by Macjutsu** [comment]
There are many updates in https://github.com/Macjutsu/super/releases/tag/v5.0.0-beta2 that may resolve this behavior. Please try it out.

**Comment by Macjutsu** [comment]
There have been so many changes to the latest version of `super` that I'm closing this issue.

https://github.com/Macjutsu/super/releases/tag/v5.0.0-beta3

If you find it persists with the latest builds of `super` please open a new issue.
