### ISSUE TITLE
Intel Based Macs Failing to Update

### ISSUE THREAD

**Issue by JMEngineeringMacOS** [Macjutsu/super#186]
Apple Silicon devices update without issue, but all Intel Based throw the following error using v4.0.3 of super

Software update command failed with an error: 2023-12-22 10:51:52.835 softwareupdate[54885:457369] XType: Using static font registry.

**Comment by Macjutsu** [comment]
That is an error in `softwareupdate` not `super`

To be clear `super` can't "make `softwareupdate` fail less"... `super` can only try again later when `softwareupdate` does fail.

Unless you can provide more context, there isn't anything to fix here. Just another day where the Apple `softwareupdate` process breaks.

**Comment by Macjutsu** [comment]
Please try the latest release of `super` as it may resolve this issue: https://github.com/Macjutsu/super/releases/tag/v4.1.0-beta1

**Comment by Macjutsu** [comment]
There are many updates in https://github.com/Macjutsu/super/releases/tag/v5.0.0-beta2 that may resolve this behavior. Please try it out.

**Comment by Macjutsu** [comment]
There have been so many changes to the latest version of `super` that I'm closing this issue.

https://github.com/Macjutsu/super/releases/tag/v5.0.0-beta3

If you find it persists with the latest builds of `super` please open a new issue.

**Comment by Macjutsu** [comment]
Indeed what does the asu-list.log show?
