### ISSUE TITLE
Recommended way to implement patch days?

### ISSUE THREAD

**Issue by coreservices-ron** [Macjutsu/super#190]
Hi!

We are using SUPER in combination with an MDM system (not JAMF, but similar in function) and using configuration profiles.

A question regarding (recurring) patch days: We would like to have pending updates being announced on a certain weekday only. If there are any updates, users should get a four-days window to apply updates and restart (if necessary). After performing any updates, SUPER should again mute until the next patch day. Currently, I am doing this by manually adjusting the „WorkflowZeroDateManual“ parameter each week in the global config profile for all devices.

I am sure there is a better way doing this — and I am not sure if this parameter is even the best handle ...

I would be happy to get a few ideas how this could be implemented best.

Kind regards,
  Ron.

**Comment by Macjutsu** [comment]
This is partially implemented via the new scheduled installation options in https://github.com/Macjutsu/super/releases/tag/v5.0.0-beta2

Stay tuned...

**Comment by Macjutsu** [comment]
This is now fully implemented in the latest build of `super` with the new `--schedule-workflow-active` option!

https://github.com/Macjutsu/super/releases/tag/v5.0.0-beta3
