### ISSUE TITLE
Typo in word "service" - low priority

### ISSUE THREAD

**Issue by AdrianH-UC** [Macjutsu/super#192]
https://github.com/Macjutsu/super/blob/a3ba601a571466379d858aaf483c0233325b86fc/super#L2517

And L2518 contain `serivce` instead of `service`.

:)

**Comment by Macjutsu** [comment]
Fixed in https://github.com/Macjutsu/super/releases/tag/v5.0.0-beta2 that may resolve this behavior. Thank you!
