### ISSUE TITLE
Question - can super be scheduled to run between a time window?

### ISSUE THREAD

**Issue by ShawnMGiesbrecht** [Macjutsu/super#194]
Hello 

Can super precisely schedule updates to occur within our desired time window (11 PM to 3 AM)?
If no, will there be a issue if we kill the process?

**Comment by Macjutsu** [comment]
This is partially implemented via the new scheduled installation options in https://github.com/Macjutsu/super/releases/tag/v5.0.0-beta2

Stay tuned...

**Comment by KenAlissia** [comment]
I have done something similar for version 4.0.3. Added block window settings. I can share the code if someone needed it.

#  Block Window Options added
#  [--block-window-start-time=hour or hh:mm]  [--block-window-end-time=hour or hh:mm]
#  [--block-window-delete-all]
#  <key>BlockWindowStartTime</key> <string>hour or hh:mm</string>
#  <key>BlockWindowEndTime</key> <string>hour or hh:mm</string>
# "--block-window-start-time" and "--block-window-end-time" option should be both set, value should be an integer range from 0-23 or hh:mm formatted 24-hour time. Or they will be discarded.

**Comment by ofirgalcon** [comment]
Sounds interesting, I need to block updates for 2 days a week. I haven't checked the v5 options yet to see if they will do what I need.

**Comment by Macjutsu** [comment]
This is now fully implemented in the latest build of `super` with the new `--schedule-workflow-active` option!

https://github.com/Macjutsu/super/releases/tag/v5.0.0-beta3
