### ISSUE TITLE
Testing Super on Jamf Connect but cannot get defferals to change

### ISSUE THREAD

**Issue by fpurdie123** [Macjutsu/super#197]
Hello. I'm having an issue with the deferrals not changing on the dialog prompt. I've tried the changes to the script that have been suggested but its still showing the default no deadline date and unlimited deferrals. I've used the script and assigned it to a policy in Jamf.

I tried just running the script manually and its exhibiting the same behaviour.

I've probably missed something really obvious but any suggestions would be appreciated!

Thanks

**Comment by fpurdie123** [comment]
I'm also unable to authorise the updates on apple silicon with the admin local account. I've put this in the policy parameters as instructed. Any help with these two issues would be greatly appreciated.

thanks

**Comment by Macjutsu** [comment]
As you are using Jamf Pro... have you consulted with the documentation? https://github.com/Macjutsu/super/wiki/Jamf-Pro-Deployment#jamf-pro-policy

**Comment by fpurdie123** [comment]
Hi Kevin.

Yes I did have a look at the documentation.

However I am now using the integrated patch management in Jamf Pro which works well out of the box and seems to be quite reliable so far.

Thanks for the reply though its much appreciated.





Kind Regards

Fraser Purdie

IT Support Officer| Information Technology | Glasgow School of Art | 6 Rose Street, Glasgow, G3 6RB | email: ***@***.******@***.***>

***@***.***
