### ISSUE TITLE
Just a question regarding inventory collection in super.

### ISSUE THREAD

**Issue by dansutt** [Macjutsu/super#198]
Im new to super and just setting up and configuring for my company. On the wiki page it states:

"Avoid adding an inventory collection to your super Policy if you have also enabled the "Collect available software updates" option in the Jamf Pro inventory collection settings. This is to prevent an issue where the softwareupdate process hangs when multiple processes (the jamf binary and super) are simultaneously asking for a list of updates."

Is the that WorkflowDisableUpdateCheck switch? I currently have that set as false but we are also doing inventory collection for software updates in Jamf as well. Should that be set to true if so?

My current config has the WorkflowDisableRelaunch set to true. I was then going to set up a policy in Jamf to run once a week on a set day for only machines that have updates available to start super via a smart group to start the update process.

Will this cause conflicts based on that article?

**Comment by hannesgnad** [comment]
WorkflowDisableUpdateCheck has nothing to do with inventory collection, but is some kine of "master switch" to disable super at all - although installed and running in the background, it will NOT check for available macOS updates.

**Comment by dansutt** [comment]
Alright thanks for that information. In my testing I didn't run into any issues, but was using test mode so sample size was only 1 machine, I just recently deployed to a small group of machines for initial live testing.

Everything seems to be working so far, so wanted to double check prior to deploying to the rest of the company in case I configured something wrong and it causes issues.

**Comment by Macjutsu** [comment]
FYI... the contemporary consensus with Jamf Pro you should disable Settings > Inventory Management > Collect available software updates and instead add macOS as a Patch Reporting title. https://learn.jamf.com/en-US/bundle/jamf-pro-documentation-current/page/Patch_Reporting.html
