### ISSUE TITLE
Updated Jamf Pro Custom Schema for super v4.0.3

### ISSUE THREAD

**Issue by swissarmygeek** [Macjutsu/super#200]
I have updated the Jamf Pro Custom Schema for SUPER, for v4.0.3, if you would like to add it.  I am using it in my Jamf configuration profiles, although I haven't tested all the properties.

I started with the existing 'v4.0.0-beta2' but then revised the text for most options (copying text from the wiki) and added all of the missing Config Profile keys (I even extracted key names from super itself to make sure I hadn't missed any)

EDIT: fixed a typo in the description for Deadline Days Focus

[Jamf-Pro-External-Application-Custom-Schema-com.macjutsu.super-v4.0.3.json](https://github.com/Macjutsu/super/files/14949044/Jamf-Pro-External-Application-Custom-Schema-com.macjutsu.super-v4.0.3.json)

**Comment by Macjutsu** [comment]
Thanks... added to v4.03 (main)... note however there is a new branch for v4.1.0-beta1.
