### ISSUE TITLE
"macOS" prefix is not required at the display_string_workflow_title variable

### ISSUE THREAD

**Issue by AshokAmirthalingam** [Macjutsu/super#201]
The "${macos_installer_marketing_name_target}" variable is already capturing the full macOS Title name. Hence, the "macOS" prefix is unnecessary in the "display_string_workflow_title" variable.

https://github.com/Macjutsu/super/blob/a3ba601a571466379d858aaf483c0233325b86fc/super#L7127
![Screenshot 2024-02-28 at 3 28 22 PM](https://github.com/Macjutsu/super/assets/36301670/a46e247f-976c-4275-87cc-3765071de2e5)

**Comment by Macjutsu** [comment]
Please try the latest release of super as it may resolve this issue: https://github.com/Macjutsu/super/releases/tag/v4.1.0-beta1
