### ISSUE TITLE
Apple Software Update Failed

### ISSUE THREAD

**Issue by Sagaroth** [Macjutsu/super#203]
Hi everyone,
I have correctly deployed SUPERMAN and the necessary policies via JAMF Pro.
But during my tests, I get the message "**apple software update failed**" from the notifier.

Do you have any ideas?

Thanks a lot!

**Comment by AshokAmirthalingam** [comment]
A few things to review on your own. 

1. check the super.log: https://github.com/Macjutsu/super/wiki/Troubleshooting#understanding-the-superlog
2. check the asu-list.log: https://github.com/Macjutsu/super/wiki/Troubleshooting#asu-listlog
