### ISSUE TITLE
macOS Sonoma 14.4: launchctl kickstart -k is no longer permitted for critical system processes

### ISSUE THREAD

**Issue by sean-alex** [Macjutsu/super#205]
In the release notes for macOS 14.4 Beta 5, Apple included the following note:

> To improve security and stability, using launchctl kickstart -k is no longer permitted for critical system processes. If a process must be forcefully terminated, it is recommended to use kill instead.

I have no solution how this command will be replaced in super, other than to raise the issue, as I did not see any issues related to this topic, either here in Github or in the #super channel in the MacAdmins slack channel.

**Comment by Macjutsu** [comment]
The latest release of super resolves this issue: https://github.com/Macjutsu/super/releases/tag/v4.1.0-beta1
