### ISSUE TITLE
In macOS 14.4, the "launchctl" "kickstart" command has been deprecated by Apple.

### ISSUE THREAD

**Issue by AshokAmirthalingam** [Macjutsu/super#208]
In macOS 14.4, Apple has deprecated support for various commands, among them `launchctl` `kickstart`.

The `kick_softwareupdated` function on macOS 14.4 is no longer operational for non-system updates.

https://github.com/Macjutsu/super/blob/a3ba601a571466379d858aaf483c0233325b86fc/super#L4380

**Comment by Macjutsu** [comment]
The latest release of super resolves this issue: https://github.com/Macjutsu/super/releases/tag/v4.1.0-beta1
