### ISSUE TITLE
MDM workflow not working for me

### ISSUE THREAD

**Issue by rcybart** [Macjutsu/super#21]
Hello,

I'm Robert.

First: The script is amazing. Thanks you very much for that.

Second: I tried it out with MDM workflow. Unfortunately it did not work for me. That's why I read through the whole script and I think I found a small mistake. In line 2517 the script checks the update.log for phase "COMPLETED" but in the log there is phase "COMPLETED". But there is a phase "COMPLETE". I think this is the reason why the script is not working for me.

I changed it in the script and now it works. Can you please update it?

Thanks in advance.

Kind regards,

Robert

**Comment by Macjutsu** [comment]
Robert,

It's not accurate to only look for "COMPLETE" as there are many instances of that during an update where it's not fully complete. For example, check out this [update.log](https://github.com/Macjutsu/super/blob/main/Example-Logs/update.log). There are roughly 10 instances of "COMPLETE", but they clearly do not indicate the process is done. Only when the log generates a "COMPLETED" are we for sure at the end of the process.

To that end, perhaps I can choose something more clear for the download stage like "(end): phase:PREPARED stalled:NO" and for the install phase like "(end): phase:PREPARED_COMMITTING_STASH stalled:NO"

Kevin

**Comment by rcybart** [comment]
Hi Kevin.

I checked everything again. There is a state COMPLETED now in my logs. Earlier whenever I tried to run super local or deployed via Jamf there was never a state like that.

I will check it again. So changes are not necessary at the moment. My bad.

Kind regards,

Robert

**Comment by Macjutsu** [comment]
This should be resolved with [`super` v3.0b1](https://github.com/Macjutsu/super/releases/tag/v3.0-b1). Thanks!
