### ISSUE TITLE
Upgrade from older OS to latest,  Storage needed

### ISSUE THREAD

**Issue by morrischacs** [Macjutsu/super#211]
Hello,

We are having some clients who are upgrading from 11.6 Big Sur to the latest version of Sonoma and the Superman is saying that we need 49 GB of free disk space.  When we download the the installer, it is only 13 GB and needs about 27 GB of storage when run run manually or from the System Settings(Preferences)  Why does Superman need more than the regular installer?

We've seen this when upgrading from Monterey as well

**Comment by Macjutsu** [comment]
`super` uses "safer" size estimates that are know to always work... but you can change them if you like... 
https://github.com/Macjutsu/super/wiki/Testing-and-Validation#free-storage-space-validation
