### ISSUE TITLE
OS Update Stalled on all devices

### ISSUE THREAD

**Issue by RavenTechPro** [Macjutsu/super#213]
So we're updating our M1-3 systems to 14.4 and Intel to 13.6.5. It's going through the motions of an update is scheduled. Gives users the options to defer. Once install starts it does the whole A required software update will automatically restart this computer in about 5 min. Then the This computer will automatically restart very soon.

The system reboots, Apple logo acts like its installing something for 2-3 min then back to login. Login and check for OS version and nothing has changed and check system and shows the update to 14.4 is still in need of install. It will then prompt the user again. Rinse and repeat for a week now. Not sure what the issue is.
On the back end it shows
Stats: User chose to restart now
MDM service is currently available at: ourjamfsitehere
validated saved credentials for the --auth-jamf-client option.
Preparing update/upgrade default notification showing a 5 min estimate
starting MacOS 14.4 update workflow
The check the log workflow info
The log shows UPDATE MACOS 14.4 VIA MDM START
df software updated comes back reported
Phase ACCEPTED: stalled: NO portionComplete
Df software updated again
phase:PREPARED_COMMITTING_STASH stalled: NO portionComplete

Then says UPDATE/UPGRADE MAC OS VIA MDM COMPLETED 
This is what we get each time, and each time no update actually happens. I'm not sure what I'm missing that is causing the Stalled
I go under the asu-workflow and it shows Finding available software
Downloading macOS Sonoma 14.4
Downloaded: MacOS Sonoma 14.4
Failed to authenticate 
Not sure why it would fail as the user is logged into their Apple account and can go to the App store and download and install applications and updates that way.

**Comment by justintrant** [comment]
How are your updates being authenticated? It looks like you're using the API functionality - is the password good?

**Comment by RavenTechPro** [comment]
They are using API, the password is good. I validated to be sure and reran the update on a device. Same issue. Though I have found on the rare user in my test group that has full admin permissions (most do not) the issue does not occur and the Updates seem to push through without issue. I would assume SUPER shouldn't require all users have full admin rights in order to function.

**Comment by Rusteasy** [comment]
I'm also having this issue, mixed m1-3 environment. Authenticated via local admin. I had one curious outlier, new iMacs that shipped with Ventura worked for the upgrade to Sonoma and continue to work with SuperV4, everything else hangs when it goes to the apple logo and progress bar. The length of the progress bar is different on many units but all hang in the first 1/3 of the progress. Logs don't show anything strange, I even let one of the systems hang for a week. A forced power cycle will continue the install and the update works as planned.  SupermanV3 works fine.

**Comment by Macjutsu** [comment]
Please check out the `super` sub-process logs. https://github.com/Macjutsu/super/wiki/Troubleshooting#understanding-sub-process-logs

**Comment by Macjutsu** [comment]
There have been so many changes to the latest version of `super` that I'm closing this issue.

https://github.com/Macjutsu/super/releases/tag/v5.0.0-beta3

If you find it persists with the latest builds of `super` please open a new issue.
