### ISSUE TITLE
Conflicting super configs when super profile is updated

### ISSUE THREAD

**Issue by aDiedericks** [Macjutsu/super#215]
Hi there,
We manage our super configs using a jamf profile. Behaviour I noticed is that when making an adjustment to the profile i.e change hard counter to soft counter or any change and propagating those changes to all machines. The super execution logs seem to still behave like the old configs are present somewhere. For example even though removing the soft counter key I will still get error:

"You can not use both the --deadline-count-soft and --deadline-count-hard options at the same time. You must pick one deadline count behavior"

To resolve this I run super uninstall and reinstall scripts.

**Comment by Macjutsu** [comment]
Uninstall is never necessary... 

Per the wiki... https://github.com/Macjutsu/super/wiki/Jamf-Pro-Deployment#jamf-pro-deployment-best-practices

"If you make changes to super settings via configuration profile, consider also using the --reset-super option in Policy Script Parameters to clear any locally cached super options that may cause conflicts."
