### ISSUE TITLE
Alternate workflow usage without affecting existing update workflow settings

### ISSUE THREAD

**Issue by tomb-github** [Macjutsu/super#216]
Can we have co-existing deferrals and configuration for multiple workflows, without affecting the existing update workflow?

Example scenario; 
- Update workflow settings delivered with a config profile, which includes types of updates, a time-based deferral setup with multiple deferral options, custom timeouts, etc.
- We would like to use restart prompting from a script (once off).
- We would like to use deferral prompting for app update policy (alternate deferral counts).

**Comment by Macjutsu** [comment]
Not currently...

But it is a good idea for a feature.... something like "ignore config profile for this one run of `super`".

**Comment by Macjutsu** [comment]
This is "effectively" implemented via the new --workflow-reset-super-after-completion option in https://github.com/Macjutsu/super/releases/tag/v5.0.0-beta2

It would be entirely too complicated to have multiple simultaneous workflows... instead you can override your default workflow with a temporary workflow until complete.
