### ISSUE TITLE
Defer selection only works if you click the arrow and not any part of the text

### ISSUE THREAD

**Issue by seanism** [Macjutsu/super#22]
The 15 minutes part is slightly off center and clicking it does nothing.  I must click the down arrow on the side.  Not a big deal but end users may be confused by it.

<img width="709" alt="Screen Shot 2022-09-19 at 4 14 32 PM" src="https://user-images.githubusercontent.com/10472025/191135377-8840337e-8d8f-46d1-9f94-5d7df5566fbd.png">

**Comment by Macjutsu** [comment]
This is a limitation in [IBM Notifier](https://github.com/IBM/mac-ibm-notifications). Nothing I can directly do about this except move to another notification system... which I may do in the future.

**Comment by seanism** [comment]
Thanks.  Appreciate the info.

*Sean Young*

Corporate IT Manager

**Comment by Macjutsu** [comment]
https://github.com/Macjutsu/super/releases/tag/v4.0.0-beta1
