### ISSUE TITLE
4.1.0 - Update Failed Dialog doesn't have the option to close the dialog

### ISSUE THREAD

**Issue by TechTrekkie** [Macjutsu/super#220]
I ran into a scenario where an update failed and the dialog displayed the appropriate info, but the dialog just hangs as if its still trying to do something and doesn't give an option to close. Checked the super.log and the script has already exited. 

<img width="632" alt="image" src="https://github.com/Macjutsu/super/assets/132794591/47af3395-7740-4ede-b363-a1e56f496687">

**Comment by Macjutsu** [comment]
Do you have the new `--display-hide-progress-bar` feature enabled?

**Comment by Macjutsu** [comment]
Arround line 7954... try adding this line:
`unset display_hide_progress_bar_status`

It should look like this in context:
```
set_display_strings_deferral_button
unset display_hide_progress_bar_status
log_super "IBM Notifier: Failure notification."

**Comment by TechTrekkie** [comment]
No I don't have the new `--display-hide-progress-bar feature enabled`. 
I'll try making the change suggested and will report back. Thank you!

**Comment by eumelkind** [comment]
We are seeing the same behaviour with both of these notifications:
![image (1)_2](https://github.com/Macjutsu/super/assets/5698685/2b0ae04c-25b3-45bf-a8bd-92589ee59c68)
![Bildschirmfoto 2024-06-11 um 12 15 00_2](https://github.com/Macjutsu/super/assets/5698685/fa5cf643-5e73-4f2c-8023-2efaa64948d6)

We actually do not want to display these messages at all. How can we prevent them from being displayed?

**Comment by Macjutsu** [comment]
I'm aware... it's a known bug and is addressed in the next beta of `super`.

**Comment by Macjutsu** [comment]
Fixed in https://github.com/Macjutsu/super/releases/tag/v5.0.0-beta2 that may resolve this behavior.
