### ISSUE TITLE
4.1.0 - Status: Deferral restrictions have changed since last super workflow run, full software status check required

### ISSUE THREAD

**Issue by ofirgalcon** [Macjutsu/super#221]
My log shows this for every time the Defer/Restart dialog is displayed

`Status: Deferral restrictions have changed since last super workflow run, full software status check required.`

I have not changed the deferral restrictions (is this referring to Apple MDM profile delay or Super's own settings???)

**Comment by Macjutsu** [comment]
This is in reference to the native Apple MDM configuration profile that contains software update deferral restrictions.

Specifically `super` is detecting changes to this file `/Library/Managed Preferences/com.apple.applicationaccess.plist`. MDM creates that file whenever any restrictions config profile is pushed to the computer. The log entry in `super` indicates that that file is changing every time? Do you think your MDM is pushing a new restrictions profile on a regular basis?

**Comment by Macjutsu** [comment]
There are many updates in https://github.com/Macjutsu/super/releases/tag/v5.0.0-beta2 that may resolve this behavior. Please try it out.

**Comment by Macjutsu** [comment]
There have been so many changes to the latest version of `super` that I'm closing this issue.

https://github.com/Macjutsu/super/releases/tag/v5.0.0-beta3

If you find it persists with the latest builds of `super` please open a new issue.
