### ISSUE TITLE
Superman not going through workflow on m1 Machine

### ISSUE THREAD

**Issue by mikecalbreeeezy** [Macjutsu/super#222]
I'm trying to implement Superman in our update policies. When I deploy the policy it doesn't do anything but shows complete in the logs.

Tue May 21 14:30:42 = Script - (macOS) Superman Updates[36653]: Status: Deleting saved credentials for the --auth-jamf-client option.
Tue May 21 14:30:42 = Script - (macOS) Superman Updates[36653]: Warning: Automatic macOS update/upgrade enforcement on Apple Silicon computers requires authentication credentials.
Tue May 21 14:30:42 Script - (macOS) Superman Updates[36653]: Status: User authentication is required to perform a macOS update/upgrade.
Tue May 21 14:30:42 = Script - (macOS) Superman Updates[36653]: Status: Found that Jamf is installing or is the parent process, restarting via super LaunchDaemon...
Tue May 21 14:30:42 = Script - (macOS) Superman Updates[36653]: **** S.U.P.E.R.M.A.N. 4.0.3 - CLEAN EXIT ****

**Comment by Macjutsu** [comment]
This is the expected workflow when deployed via Jamf Pro... please take some time to explore the `super` wiki before posting issues.

Specifically for your question: https://github.com/Macjutsu/super/wiki/Troubleshooting#understanding-the-superlog
