### ISSUE TITLE
Unable to Successfully Update Major OS feature versions

### ISSUE THREAD

**Issue by dlee-git-user** [Macjutsu/super#223]
Hi, 
I'm using an RMM that has a script to push out updates using this wonderful piece of software. It currently works for the minor upgrades, but when modifying the script to with the switch to include major os upgrades, it doesn't work properly. 

I can provide the full body of the script, but the line where we actually call super to run with the major os upgrade switch is:

`/Library/Management/super/super --install-macos-major-upgrades >> /usr/local/share/CentraStage/Temp/SUPERout.txt

This is basically what happens when running the script on a test macbook from macOS version 11 Big Sur > 12 Monterey on a MacBookAir7,2

![image](https://github.com/Macjutsu/super/assets/173319632/33bec600-a6ce-4b29-a3f0-6788be1d7a26)

**Comment by Macjutsu** [comment]
Please refer to the local super.log when troubleshooting a device.

https://github.com/Macjutsu/super/wiki/Troubleshooting

**Comment by Macjutsu** [comment]
There have been so many changes to the latest version of `super` that I'm closing this issue.

https://github.com/Macjutsu/super/releases/tag/v5.0.0-beta3

If you find it persists with the latest builds of `super` please open a new issue.
