### ISSUE TITLE
Sequoia - 5.0b2- Erroneous Non-system update triggered

### ISSUE THREAD

**Issue by master-vodawagner** [Macjutsu/super#224]
Been dabling with macOS Sequoia and Super V4.1.0b1, post upgrading to Sequoia Super seems to detect a non-system update, attempts to install it and fails.

I cannot see any updates in the logs or softwareupdate --list

```
Thu Jul 11 10:38:33 X2030488 super[2792]: **** S.U.P.E.R.M.A.N. 4.1.0-beta1 - INSTALL NON-SYSTEM UPDATES VIA SOFTWAREUPDATE START ****
Software Update Tool
```

[super.log](https://github.com/user-attachments/files/16175483/super.log)
[msu-workflow.log](https://github.com/user-attachments/files/16175485/msu-workflow.log)
[mdmclient-list.log](https://github.com/user-attachments/files/16175486/mdmclient-list.log)

**Comment by master-vodawagner** [comment]
I've also done a --reset-super argument initiated from jamf Pro and ti still finds an invisible update @Macjutsu

**Comment by Macjutsu** [comment]
Thanks for this.. you'll want to check again when the next beta hits...

**Comment by Macjutsu** [comment]
There are many updates in https://github.com/Macjutsu/super/releases/tag/v5.0.0-beta2 that may resolve this behavior. Please try it out.

**Comment by master-vodawagner** [comment]
> There are many updates in https://github.com/Macjutsu/super/releases/tag/v5.0.0-beta2 that may resolve this behavior. Please try it out.

Hello

Unfortunately not 😩

**Comment by Macjutsu** [comment]
Hrm... I'm using this on my computer running 15.0 Beta (24A5298h) right now... can you please provide a super.log when you get a chance... thanks!

**Comment by master-vodawagner** [comment]
[mdmclient-list.log](https://github.com/user-attachments/files/16397201/mdmclient-list.log)
[msu-list.log](https://github.com/user-attachments/files/16397202/msu-list.log)
[msu-workflow.log](https://github.com/user-attachments/files/16397203/msu-workflow.log)

**Comment by master-vodawagner** [comment]
super.log
```
Fri Jul 26 22:59:38 X2030488 super[3330]: **** S.U.P.E.R.M.A.N. 5.0.0-beta2 - SUPER STARTUP ****\
Fri Jul 26 22:59:38 X2030488 super[3330]: Status: Mac computer with Apple silicon running: macOS  15.0-24A5298h\
Fri Jul 26 22:59:38 X2030488 super[3330]: Status: Last macOS startup was: 2024-07-26:22:50:44\
Fri Jul 26 22:59:38 X2030488 super[3330]: Status: Current active GUI user is: lewis12345 (502)\
Fri Jul 26 22:59:40 X2030488 super[3330]: Status: Managed by Jamf Pro 11.8.0 hosted at: <REDACTED>\
Fri Jul 26 22:59:40 X2030488 super[3330]: Status: Previously scheduled installation workflow active for: 2024-07-27:21:18\
Fri Jul 26 22:59:40 X2030488 super[3330]: Status: macOS update/upgrade workflows automatically authenticated via Jamf Pro API with --auth-mdm-failover-to-user=ALWAYS.\
Fri Jul 26 22:59:40 X2030488 super[3330]: **** S.U.P.E.R.M.A.N. 5.0.0-beta2 - CHECK FOR SOFTWARE UPDATES/UPGRADES ****\
Fri Jul 26 22:59:40 X2030488 super[3330]: Status: Deferral restrictions have changed since last super workflow run, full software status check required.\
Fri Jul 26 22:59:40 X2030488 super[3330]: Status: This system is currently configured with software update deferral restrictions.\
Fri Jul 26 22:59:41 X2030488 super[3330]: mdmclient: Waiting for available updates listing...\
Fri Jul 26 22:59:47 X2030488 super[3330]: softwareupdate: Waiting for available updates listing...\
Fri Jul 26 22:59:58 X2030488 super[3330]: Target: Non-system update 1 of 1 is:  \
Fri Jul 26 22:59:59 X2030488 super[3330]: Status: Resetting automatic zero date.\
Fri Jul 26 22:59:59 X2030488 super[3330]: Status: Resetting all deadline counters.\
Fri Jul 26 22:59:59 X2030488 super[3330]: **** S.U.P.E.R.M.A.N. 5.0.0-beta2 - NON-SYSTEM SOFTWARE UPDATE ****\
Fri Jul 26 22:59:59 X2030488 super[3330]: IBM Notifier: Installing non-system macOS software updates notification.\
Fri Jul 26 22:59:59 X2030488 super[3330]: softwareupdate: Starting non-system macOS software updates installation workflow, check /Library/Management/super/logs/msu-workflow.log for more detail.\
Fri Jul 26 23:00:00 X2030488 super[3330]: Warning: Help button not shown because URL is unreachable: https://support.apple.com/en-gb/HT213895\
Fri Jul 26 23:02:00 X2030488 super[3330]: Error: Installation of non-system macOS software updates failed to start after waiting for 120 seconds.\
Fri Jul 26 23:02:00 X2030488 super[3330]: Warning: Apple no longer allows for restarting of software update services on macOS 14.4 or newer. The system may need to be restarted for software update to function properly.\
Fri Jul 26 23:02:00 X2030488 super[3330]: Status: This system is currently configured with software update deferral restrictions.\
Fri Jul 26 23:02:01 X2030488 super[3330]: mdmclient: Waiting for available updates listing...\
Fri Jul 26 23:02:27 X2030488 super[3330]: softwareupdate: Waiting for available updates listing...\
Fri Jul 26 23:02:56 X2030488 super[3330]: Target: Non-system update 1 of 1 is:  \
Fri Jul 26 23:02:56 X2030488 super[3330]: Warning: Failed to install all non-system macOS software updates, re-trying installation workflow.\
Fri Jul 26 23:02:56 X2030488 super[3330]: softwareupdate: Starting non-system macOS software updates installation workflow, check /Library/Management/super/logs/msu-workflow.log for more detail.\
Fri Jul 26 23:04:56 X2030488 super[3330]: Error: Installation of non-system macOS software updates failed to start after waiting for 120 seconds.\
Fri Jul 26 23:04:56 X2030488 super[3330]: Warning: Apple no longer allows for restarting of software update services on macOS 14.4 or newer. The system may need to be restarted for software update to function properly.\
Fri Jul 26 23:04:56 X2030488 super[3330]: Status: This system is currently configured with software update deferral restrictions.\
Fri Jul 26 23:04:58 X2030488 super[3330]: mdmclient: Waiting for available updates listing...\
Fri Jul 26 23:05:02 X2030488 super[3330]: softwareupdate: Waiting for available updates listing...\
Fri Jul 26 23:05:08 X2030488 super[3330]: Target: Non-system update 1 of 1 is:  \
Fri Jul 26 23:05:08 X2030488 super[3330]: Warning: Some non-system macOS software updates did not complete, trying again in 60 minutes.\
Fri Jul 26 23:05:08 X2030488 super[3330]: IBM Notifier: Failure notification.\
Fri Jul 26 23:05:08 X2030488 super[3330]: Exit: super is scheduled to automatically relaunch at: 2024-07-27:00:05:00\
Fri Jul 26 23:05:08 X2030488 super[3330]: **** S.U.P.E.R.M.A.N. 5.0.0-beta2 - EXIT CLEAN ****\
Fri Jul 26 23:05:08 X2030488 super[3330]: Warning: Help button not shown because URL is unreachable: https://support.apple.com/en-gb/HT213895\
```

**Comment by master-vodawagner** [comment]
I don’t know if this is an issue from upgrading from Sonoma to Sequoia or if it exists on a laptop setup directly to Sequoia yet.

**Comment by master-vodawagner** [comment]
Just tested a straight build to Sequoia best 4 and super V5 has found nothing.

So this is just the scenario of upgrading from Sonoma to Sequoia

**Comment by master-vodawagner** [comment]
@Macjutsu  I think I've found the root cause

Scenario
Previous OS: Sonoma 14.6 23G80
Beta Update channel: macOS Sonoma AppleSeed Beta

Upgrade to macOS Sequoia 24A5298h, once at the Desktop SuperV5 kicks in and finds these random non-OS updates, the Mac is still attached to the Sonoma beta update channel. Once I flipped the mac to the macOS Sequoia AppleSeed Beta channel and ran `super --reset-super` all is well in the world again

**Comment by master-vodawagner** [comment]
Not sure if this is the culprit or not. Decided to try changing the beta update channel to Sequoia before upgrading.

Once at Seqouia super found the invisible updates 😩

**Comment by master-vodawagner** [comment]
This command `/usr/sbin/softwareupdate --background --include-config-data` appears to have worked on 1 test device so far.

We've basically deployed `Super`V5, then triggered the Sequoia upgrade and used an existing launchdaemon called `reconatreboot.sh` which runs a Jamf recon after Sequoia upgrade before finally running the added the above command to run prior to running` super --reset-super`

**Comment by Macjutsu** [comment]
Think you can give the latest build a try?

https://github.com/Macjutsu/super/releases/tag/v5.0.0-beta3

**Comment by master-vodawagner** [comment]
Yes although wouldn’t be until mid October sorry, extended holiday time.

**Comment by Macjutsu** [comment]
I'm gonna close this for now... I have made a bunch of changes and will likley do a lot more in the next few weeks for the release of Sequoia. If you see this again in October on whatever latest version is, please open a new issue.

Thanks!

**Comment by master-vodawagner** [comment]
Based on a chart that in the super slack Chanel, this is so present in beta 3

**Comment by Macjutsu** [comment]
I think I have a fix in the next beta.... soon.

**Comment by Macjutsu** [comment]
Pretty sure I got it this time: https://github.com/Macjutsu/super/releases/tag/v5.0.0-beta4
