### ISSUE TITLE
User Authentication Prompt button says "restart now" when prompted after scheduling restart for later date/time

### ISSUE THREAD

**Issue by TechTrekkie** [Macjutsu/super#228]
I noticed after I scheduled a restart for a later date/time, the user authentication prompt that displayed to enter a password read "restart now" for the button text. I thought it may cause some confusion and  since it won't be restarting until later at the scheduled date/time. Perhaps in that scenario the button could just say "OK" or "Schedule"

**Comment by Macjutsu** [comment]
This was resolved in the latest build... thanks!

https://github.com/Macjutsu/super/releases/tag/v5.0.0-beta3
