### ISSUE TITLE
Super 5.0.0 beta 2: Scheduled Restart asks for password twice: Once when scheduled and again when the scheduled install date passes

### ISSUE THREAD

**Issue by TechTrekkie** [Macjutsu/super#229]
When scheduling a restart, super prompts for a password immediately after scheduling. When the scheduled installation date/time passes, super prompts again for a password.

**Comment by Macjutsu** [comment]
Are you not using any type of saved authentication method?

**Comment by Macjutsu** [comment]
This was resolved in the latest build... thanks!

https://github.com/Macjutsu/super/releases/tag/v5.0.0-beta3
