### ISSUE TITLE
Small Typo in Scheduling dialogue

### ISSUE THREAD

**Issue by hannesgnad** [Macjutsu/super#232]
"* Select a date and time to s**_E_**chedule this event."

<img width="632" alt="Schedule_Restart" src="https://github.com/user-attachments/assets/2002756c-377b-4726-aca4-16d5927fbcf6">

**Comment by Macjutsu** [comment]
Thanks... fixed in next beta.

**Comment by Macjutsu** [comment]
This was resolved in the latest build... thanks!

https://github.com/Macjutsu/super/releases/tag/v5.0.0-beta3
