### ISSUE TITLE
5.0.0beta2 - User auth workflow has countdown timer - Doesn't persist if no password entered

### ISSUE THREAD

**Issue by master-vodawagner** [Macjutsu/super#233]
I'm testing the User Auth workflow on Apple Silicon

When my device reaches the state of max hard days, MDM fails to start the reboot (intended I disabled the network) and presents the User Auth UI ($display_string_user_auth_deadline_days_hard_body) [I've tweaked the text of said variable too].

I get the 2 minute countdown to enter the password, I was under the impression OR at least in Super V4 the UI persists until a password is entered however I'm not getting that.  After 2 minutes the workflow fails and goes to the default 1 hour try again UI.

<img width="513" alt="macOS_Sequoia-Super-08-MDMFailedLocalAuthNeeded-PromptOnly" src="https://github.com/user-attachments/assets/a95a5ebb-8164-447e-9bcc-b837c5e082dd">

**Comment by Macjutsu** [comment]
Depends on your settings.... but if `super` was told there should be a display timeout... it will timeout the auth dialog just like any other. So what settings are you using?

**Comment by master-vodawagner** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>DeferralTimerDefault</key>
    <string>60</string>
    <key>DisplayIconFile</key>
    <string>https://euw2.ics.services.jamfcloud.com/icon/hash_4de3de206fcd90bdf0d616c4c323b11bbab85cedd637ae610a4f52b73c5ddba7</string>
    <key>DisplayIconSize</key>
    <string>90</string>
    <key>DisplayUnmovable</key>
    <string>ALWAYS</string>
    <key>DialogTimeoutDefault</key>
    <string>600</string>
    <key>DeadlineDaysHard</key>
    <string>1</string>
    <key>ScheduledInstallUserChoice</key>
    <true/>
    <key>ScheduledInstallReminder</key>
    <string>60,30,15,5</string>
    <key>AuthJamfComputerID</key>
    <string>$JSSID</string>
    <key>DeferralTimerMenu</key>
    <string>30,60,120,180</string>
    <key>InstallNonSystemUpdatesWithoutRestarting</key>
    <true/>
    <key>SupportContact</key>
    <string>0330 123 5023</string>
    <key>DeferralTimerWorkflowRelaunch</key>
    <string>20</string>
    <key>AuthMDMFailoverToUser</key>
    <string>ALWAYS</string>
    <key>DisplayHelpButtonString</key>
    <string>https://support.apple.com/en-gb/HT213895</string>
    <key>InstallRapidSecurityResponses</key>
    <true/>
    <key>VerboseMode</key>
    <true/>
  </dict>
</plist>

**Comment by master-vodawagner** [comment]
So without DialogTimeoutDefault and we defined the other prompts to timeout but not user auth it would theoretically persist?

**Comment by Macjutsu** [comment]
Yes, that is how it should work.

**Comment by master-vodawagner** [comment]
Yep worked, was an obvious transition to V5 that I overlooked
