### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by wakco** [Macjutsu/super#24]
1. Support for additional dialog systems, I'm currently using [DEPNotify](https://github.com/jamf/DEPNotify), and I'm looking to replace that with [swiftDialog](https://github.com/bartreardon/swiftDialog).

2. Option to supply the Jamf Pro device id, saving the need to check the computers UUID and then bothering the server with then looking up the computers device id. I've noticed that the jamf recon command finishes processing with the computers device id (i.e. <computer_id>1330</computer_id>), so I've started capturing that and storing it on the computer for use in working with the Jamf Pro API like this.

**Comment by Macjutsu** [comment]
1. DEPNofity doesn't allow for the type of dialog boxes that are possible with `super`. However, I have plans to replace IBM Notifier with swiftDialog in a future release. Suffice to say, this is not a trivial lift given how many different types to dynamic dialogs `super` can generate.

2. First, you can supply the [device ID per the instructions] (https://github.com/Macjutsu/super/wiki/Jamf-Pro-API-Credentials#jamf-pro-id-via-mdm-configuration-profile). However, your idea is even better... I didn't even think about stealing from `jamf recon` like that!

**Comment by wakco** [comment]
1. Good to know, and I did suspect DEPNotify might not be an option.
2. Even better, and I really need to take a better look at what Jamf variables are available, and how they can be passed to scripts through either through config. profiles or as command options, so thanks for that.

I'm happy enough with those responses that I'm going to test super on our test/dev system.
