### ISSUE TITLE
Error:  Target: macOS minor update  -FALSE which is a GB download.

### ISSUE THREAD

**Issue by axiomitdavid** [Macjutsu/super#243]
5.0.0-rc1

On multiple Macs, different macOS versions (13.x and 14.x) seeing error when trying to check for updates

Target: macOS minor update  -FALSE which is a GB download.

Here is the entire log showing the sequence

Wed Oct 09 16:14:15 Nicks-MacBook-Pro superupdatemamager.sh[7435]: **** S.U.P.E.R.M.A.N. 5.0.0-rc1 - SUPER INSTALLATION ****
Wed Oct 09 16:14:15 Nicks-MacBook-Pro superupdatemamager.sh[7435]: Installation: Copying super to: /Library/Management/super/super
Wed Oct 09 16:14:15 Nicks-MacBook-Pro superupdatemamager.sh[7435]: Installation: Creating super search path link: /usr/local/bin/super
Wed Oct 09 16:14:15 Nicks-MacBook-Pro superupdatemamager.sh[7435]: Installation: Creating super LaunchDaemon helper: /Library/Management/super/super-starter
Wed Oct 09 16:14:15 Nicks-MacBook-Pro superupdatemamager.sh[7435]: Installation: Creating super LaunchDaemon: /Library/LaunchDaemons/com.macjutsu.super.plist.
Wed Oct 09 16:14:15 Nicks-MacBook-Pro superupdatemamager.sh[7435]: Installation: Setting permissions for installed super items.
Wed Oct 09 16:14:15 Nicks-MacBook-Pro superupdatemamager.sh[7435]: **** S.U.P.E.R.M.A.N. 5.0.0-rc1 - SUPER STARTUP ****
Wed Oct 09 16:14:16 Nicks-MacBook-Pro superupdatemamager.sh[7435]: Status: Mac computer with Intel running: macOS Sonoma 14.1-23B2073
Wed Oct 09 16:14:16 Nicks-MacBook-Pro superupdatemamager.sh[7435]: Status: Last macOS startup was: 2024-10-08:07:52:09
Wed Oct 09 16:14:16 Nicks-MacBook-Pro superupdatemamager.sh[7435]: Status: Current active GUI user is: XXXXXX (501)
Wed Oct 09 16:14:16 Nicks-MacBook-Pro superupdatemamager.sh[7435]: Warning: Automatic download and installation of macOS updates is currently enabled, this can result in updates being installed outside of super workflows.
Wed Oct 09 16:14:18 Nicks-MacBook-Pro superupdatemamager.sh[7435]: Status: Attempting to download and install IBM Notifier.app...
Wed Oct 09 16:14:20 Nicks-MacBook-Pro superupdatemamager.sh[7435]: Status: Attempting to download new requested display icon from URL source...
Wed Oct 09 16:14:20 Nicks-MacBook-Pro superupdatemamager.sh[7435]: Status: Validated new diplay icon for light mode sourced from: https://office365skumap.blob.core.windows.net/intune-assets/axiomittraylogo.png
Wed Oct 09 16:14:20 Nicks-MacBook-Pro superupdatemamager.sh[7435]: Status: Attempting to download new requested display icon from URL source...
Wed Oct 09 16:14:20 Nicks-MacBook-Pro superupdatemamager.sh[7435]: Status: Validated new diplay icon for dark mode sourced from: https://office365skumap.blob.core.windows.net/intune-assets/axiomittraylogo.png
Wed Oct 09 16:14:20 Nicks-MacBook-Pro superupdatemamager.sh[7435]: Status: macOS update/upgrade workflows automatically authenticated via system account (root).
Wed Oct 09 16:14:20 Nicks-MacBook-Pro superupdatemamager.sh[7435]: Status: Found that super is installing, restarting via LaunchDaemon...
Wed Oct 09 16:14:20 Nicks-MacBook-Pro superupdatemamager.sh[7435]: **** S.U.P.E.R.M.A.N. 5.0.0-rc1 - EXIT AND RESTART WORKFLOW ****
Wed Oct 09 16:14:26 Nicks-MacBook-Pro super-starter[8051]: **** S.U.P.E.R.M.A.N. 5.0.0-rc1 - LAUNCHDAEMON ****
Wed Oct 09 16:14:26 Nicks-MacBook-Pro super[8066]: **** S.U.P.E.R.M.A.N. 5.0.0-rc1 - SUPER STARTUP ****
Wed Oct 09 16:14:26 Nicks-MacBook-Pro super[8066]: Status: Mac computer with Apple silicon running: macOS Sonoma 14.1-23B2073
Wed Oct 09 16:14:26 Nicks-MacBook-Pro super[8066]: Status: Last macOS startup was: 2024-10-08:07:52:09
Wed Oct 09 16:14:26 Nicks-MacBook-Pro super[8066]: Status: Current active GUI user is: XXXXX (501)
Wed Oct 09 16:14:26 Nicks-MacBook-Pro super[8066]: Warning: Automatic download and installation of macOS updates is currently enabled, this can result in updates being installed outside of super workflows.
Wed Oct 09 16:14:27 Nicks-MacBook-Pro super[8066]: Warning: Automatic macOS update/upgrade enforcement on Apple Silicon computers requires authentication credentials.
Wed Oct 09 16:14:27 Nicks-MacBook-Pro super[8066]: Status: User authentication is required to perform a macOS update/upgrade.
Wed Oct 09 16:14:27 Nicks-MacBook-Pro super[8066]: **** S.U.P.E.R.M.A.N. 5.0.0-rc1 - CHECK FOR SOFTWARE UPDATES/UPGRADES ****
Wed Oct 09 16:14:27 Nicks-MacBook-Pro super[8066]: Status: No deferral restrictions cache, full software status check required.
Wed Oct 09 16:14:29 Nicks-MacBook-Pro super[8066]: mdmclient: Waiting for available updates listing...
Wed Oct 09 16:14:36 Nicks-MacBook-Pro super[8066]: softwareupdate: Waiting for available updates listing...
Wed Oct 09 16:14:45 Nicks-MacBook-Pro super[8066]: Target: macOS minor update  -FALSE which is a GB download.
Wed Oct 09 16:14:45 Nicks-MacBook-Pro super[8066]: Status: Resetting any workflow dates.
Wed Oct 09 16:14:45 Nicks-MacBook-Pro super[8066]: Status: Resetting any deadline counters.
Wed Oct 09 16:14:45 Nicks-MacBook-Pro super[8066]: Status: Full super workflow complete! The super workflow is scheduled to automatically relaunch in 360 minutes.
Wed Oct 09 16:14:45 Nicks-MacBook-Pro super[8066]: Exit: super is scheduled to automatically relaunch at: 2024-10-09:22:14:00
Wed Oct 09 16:14:45 Nicks-MacBook-Pro super[8066]: **** S.U.P.E.R.M.A.N. 5.0.0-rc1 - EXIT CLEAN ****
bash-3.2#

**Comment by axiomitdavid** [comment]
The logs show complete install and first run.  

Uninstall/re-install does not help in most cases.

**Comment by Macjutsu** [comment]
Could you provide the mdmclient-list.log and msu-list.log examples please?

**Comment by axiomitdavid** [comment]
Attached are the requested logs

Thanks for your attention


​Kind Regards,
​
​David Benet
​​​Senior Engineer
HELPDESK ***@***.***
WEB www.axiomit.com.au
TELEPHONE 
1300 991 992
FOLLOW US LinkedIn | Twitter | Facebook
Liability limited by a scheme approved under Professional Standards Legislation.
Confidentiality: The contents of this e-mail may contain information that is confidential, privileged or commercially valuable and is intended for the named recipient of this e-mail. If you are not the intended recipient you are notified that several Commonwealth Acts of Parliament strictly prohibit any review, re-transmission, disclosure, use or dissemination of this communication. AXIOM IT does not warrant that the contents of any electronically transmitted information will remain confidential. If you receive this e-mail in error, please reply to us immediately and delete this transmission together with any attachments. Viruses: It is the recipient/client's duty to virus scan and otherwise test the information provided before loading onto any computer system. No warranty is made that this material is free from computer virus or any other defect or error. Any loss/damage incurred by using this material is not the sender's responsibility. AXIOM IT entire liability will be limited to resupplying the material.
________________________________

**Comment by Macjutsu** [comment]
There are no attachements in the email... you should respond in the GitHub site.

**Comment by Macjutsu** [comment]
I'm pretty sure this stems from the same error as the other issue you posted, so I think I have it resolved.

**Comment by Macjutsu** [comment]
https://github.com/Macjutsu/super/releases/tag/v5.0.0
