### ISSUE TITLE
Error: Parse error: bad token     <stdin>:1

### ISSUE THREAD

**Issue by axiomitdavid** [Macjutsu/super#244]
Seeing across multiple Macs at different OS versions

Wed Oct 09 16:20:14 Nicks-MacBook-Pro super[9662]: **** S.U.P.E.R.M.A.N. 5.0.0-rc1 - SUPER STARTUP ****
Wed Oct 09 16:20:15 Nicks-MacBook-Pro super[9662]: Status: Mac computer with Intel running: macOS Sonoma 14.1-23B2073
Wed Oct 09 16:20:15 Nicks-MacBook-Pro super[9662]: Status: Last macOS startup was: 2024-10-08:07:52:09
Wed Oct 09 16:20:15 Nicks-MacBook-Pro super[9662]: Status: Current active GUI user is: XXXXXXX (501)
Wed Oct 09 16:20:16 Nicks-MacBook-Pro super[9662]: Warning: Automatic download and installation of macOS updates is currently enabled, this can result in updates being installed outside of super workflows.
Wed Oct 09 16:20:18 Nicks-MacBook-Pro super[9662]: Status: macOS update/upgrade workflows automatically authenticated via system account (root).
Wed Oct 09 16:20:18 Nicks-MacBook-Pro super[9662]: **** S.U.P.E.R.M.A.N. 5.0.0-rc1 - CHECK FOR SOFTWARE UPDATES/UPGRADES ****

Parse error: bad token
    <stdin>:1

Wed Oct 09 16:20:18 Nicks-MacBook-Pro super[9662]: Target: macOS minor update  -FALSE which is a GB download.
Wed Oct 09 16:20:18 Nicks-MacBook-Pro super[9662]: Status: Resetting any workflow dates.
Wed Oct 09 16:20:18 Nicks-MacBook-Pro super[9662]: Status: Resetting any deadline counters.
Wed Oct 09 16:20:18 Nicks-MacBook-Pro super[9662]: Status: Full super workflow complete! The super workflow is scheduled to automatically relaunch in 360 minutes.
Wed Oct 09 16:20:19 Nicks-MacBook-Pro super[9662]: Exit: super is scheduled to automatically relaunch at: 2024-10-09:22:20:00
Wed Oct 09 16:20:19 Nicks-MacBook-Pro super[9662]: **** S.U.P.E.R.M.A.N. 5.0.0-rc1 - EXIT CLEAN ****

**Comment by axiomitdavid** [comment]
Have tried -x option and complete uninstall and reinstall and still have the same issue.

**Comment by Macjutsu** [comment]
Could you check things out in `super --verbose-mode`? You don't have to provide the whole log, just the lines arround that parse error.

**Comment by axiomitdavid** [comment]
Fri Oct 11 09:24:42 Nicks-MBP super[6349]: Verbose Mode: Function workflow_check_software_status: Line 6252: mdmclient_non_system_array is:

Fri Oct 11 09:24:42 Nicks-MBP super[6349]: Verbose Mode: Function workflow_check_software_status: Line 6253: mdmclient_macos_installers_deferred_array is:

Fri Oct 11 09:24:42 Nicks-MBP super[6349]: Verbose Mode: Function workflow_check_software_status: Line 6254: mdmclient_macos_msu_deferred_array is:

Fri Oct 11 09:24:42 Nicks-MBP super[6349]: Verbose Mode: Function workflow_check_software_status: Line 6255: mdmclient_non_system_deferred_array is:

Fri Oct 11 09:24:42 Nicks-MBP super[6349]: Verbose Mode: Function workflow_check_software_status: Line 6256: mdmclient_security_array is:

Fri Oct 11 09:24:42 Nicks-MBP super[6349]: Verbose Mode: Function workflow_check_software_status: Line 6326: mdmclient_macos_msu_item is: Title:macOS Sonoma 14.7,Build:23H124,Version:14.7
Fri Oct 11 09:24:42 Nicks-MBP super[6349]: Verbose Mode: Function workflow_check_software_status: Line 6326: mdmclient_macos_msu_item is: Title:macOS Sonoma 14.6.1,Build:23G93,Version:14.6.1
Fri Oct 11 09:24:42 Nicks-MBP super[6349]: Verbose Mode: Function workflow_check_software_status: Line 6326: mdmclient_macos_msu_item is: Title:macOS Sonoma 14.6,Build:23G80,Version:14.6
Fri Oct 11 09:24:42 Nicks-MBP super[6349]: Verbose Mode: Function workflow_check_software_status: Line 6326: mdmclient_macos_msu_item is: Title:macOS Sonoma 14.5,Build:23F79,Version:14.5
Fri Oct 11 09:24:42 Nicks-MBP super[6349]: Verbose Mode: Function workflow_check_software_status: Line 6330: mdmclient_macos_msu_major_upgrade_array is:

Fri Oct 11 09:24:42 Nicks-MBP super[6349]: Verbose Mode: Function workflow_check_software_status: Line 6331: mdmclient_macos_msu_minor_update_array is:
Title:macOS Sonoma 14.7,Build:23H124,Version:14.7
Title:macOS Sonoma 14.6.1,Build:23G93,Version:14.6.1
Title:macOS Sonoma 14.6,Build:23G80,Version:14.6
Title:macOS Sonoma 14.5,Build:23F79,Version:14.5
Fri Oct 11 09:24:42 Nicks-MBP super[6349]: Verbose Mode: Function workflow_check_software_status: Line 6408: mdmclient_macos_installer_target is: FALSE
Fri Oct 11 09:24:42 Nicks-MBP super[6349]: Verbose Mode: Function workflow_check_software_status: Line 6409: mdmclient_macos_msu_major_upgrade_target is: FALSE
Fri Oct 11 09:24:42 Nicks-MBP super[6349]: Verbose Mode: Function workflow_check_software_status: Line 6410: macos_major_upgrade_latest is: FALSE
Fri Oct 11 09:24:42 Nicks-MBP super[6349]: Verbose Mode: Function workflow_check_software_status: Line 6443: mdmclient_macos_msu_minor_update_target is: Title:macOS Sonoma 14.7,Build:23H124,Version:14.7
Fri Oct 11 09:24:42 Nicks-MBP super[6349]: Verbose Mode: Function workflow_check_software_status: Line 6444: macos_minor_update_latest is: TRUE
Fri Oct 11 09:24:42 Nicks-MBP super[6349]: Verbose Mode: Function workflow_check_software_status: Line 6540: msu_sanitized_list is:
Label:macOS Sonoma 14.6-23G80,Title:macOS Sonoma 14.6,Version:14.6,Size:4040138KiB,Recommended:YES,Action:restart,
Fri Oct 11 09:24:42 Nicks-MBP super[6349]: Verbose Mode: Function workflow_check_software_status: Line 6544: macos_msu_array is:
Label:macOS Sonoma 14.6-23G80,Title:macOS Sonoma 14.6,Size:4040138KiB,Version:14.6
Fri Oct 11 09:24:42 Nicks-MBP super[6349]: Verbose Mode: Function workflow_check_software_status: Line 6545: non_system_msu_array is:

Fri Oct 11 09:24:42 Nicks-MBP super[6349]: Verbose Mode: Function workflow_check_software_status: Line 6584: macos_msu_item is: Label:macOS Sonoma 14.6-23G80,Title:macOS Sonoma 14.6,Size:4040138KiB,Version:14.6
Fri Oct 11 09:24:42 Nicks-MBP super[6349]: Verbose Mode: Function workflow_check_software_status: Line 6590: macos_msu_minor_update_target is: FALSE

Parse error: bad token
   <stdin>:1

Fri Oct 11 09:24:42 Nicks-MBP super[6349]: Target: macOS minor update  -FALSE which is a GB download.
Fri Oct 11 09:24:42 Nicks-MBP super[6349]: Verbose Mode: Function workflow_check_software_status: Line 6601: macos_msu_label is: FALSE
Fri Oct 11 09:24:42 Nicks-MBP super[6349]: Verbose Mode: Function check_macos_downloads: Line 6682: macos_installer_download_required is: FALSE
Fri Oct 11 09:24:42 Nicks-MBP super[6349]: Verbose Mode: Function check_macos_downloads: Line 6741: macos_msu_download_required is: FALSE
Fri Oct 11 09:24:42 Nicks-MBP super[6349]: Verbose Mode: Function main: Line 10440: Setting new workflow_time_epoch to: 1728599082
Fri Oct 11 09:24:42 Nicks-MBP super[6349]: Verbose Mode: Function main: Line 10481: macos_installer_target is: FALSE
Fri Oct 11 09:24:43 Nicks-MBP super[6349]: Verbose Mode: Function main: Line 10482: macos_msu_major_upgrade_target is: FALSE
Fri Oct 11 09:24:43 Nicks-MBP super[6349]: Verbose Mode: Function main: Line 10483: macos_msu_minor_update_target is: FALSE
Fri Oct 11 09:24:43 Nicks-MBP super[6349]: Verbose Mode: Function main: Line 10484: non_system_msu_targets is: FALSE
Fri Oct 11 09:24:43 Nicks-MBP super[6349]: Verbose Mode: Function main: Line 10485: workflow_restart_without_updates_option is: FALSE
Fri Oct 11 09:24:43 Nicks-MBP super[6349]: Verbose Mode: Function main: Line 10486: install_jamf_policy_triggers_without_restarting_option is: FALSE
Fri Oct 11 09:24:43 Nicks-MBP super[6349]: Verbose Mode: Function delete_unneeded_macos_installers: Line 6804: mdfind_macos_installers_array is:




​Kind Regards,
​
​David Benet
​​​Senior Engineer
HELPDESK ***@***.***
WEB www.axiomit.com.au
TELEPHONE 
1300 991 992
FOLLOW US LinkedIn | Twitter | Facebook
Liability limited by a scheme approved under Professional Standards Legislation.
Confidentiality: The contents of this e-mail may contain information that is confidential, privileged or commercially valuable and is intended for the named recipient of this e-mail. If you are not the intended recipient you are notified that several Commonwealth Acts of Parliament strictly prohibit any review, re-transmission, disclosure, use or dissemination of this communication. AXIOM IT does not warrant that the contents of any electronically transmitted information will remain confidential. If you receive this e-mail in error, please reply to us immediately and delete this transmission together with any attachments. Viruses: It is the recipient/client's duty to virus scan and otherwise test the information provided before loading onto any computer system. No warranty is made that this material is free from computer virus or any other defect or error. Any loss/damage incurred by using this material is not the sender's responsibility. AXIOM IT entire liability will be limited to resupplying the material.
________________________________

**Comment by Macjutsu** [comment]
This will be resolved in the next build of `super`.

**Comment by Macjutsu** [comment]
https://github.com/Macjutsu/super/releases/tag/v5.0.0
