### ISSUE TITLE
mist-cli not found and super not installing

### ISSUE THREAD

**Issue by Luke-From-IT** [Macjutsu/super#251]
Hi,

I have a device on macOS 13.4 which is running super 5.0.0, it is failing on

mist-cli Error: macOS installers listing failed, check /Library/Management/super/logs/macos-installers-list.log for more detail. but mist-cli is not present or installed.

/Library/Management/super/logs/macos-installers-list.log
`/Library/Management/super/super: line 6084: /usr/local/bin/mist: No such file or directory
`

/Library/Management/super/logs/super.log
`
Wed Nov 06 12:12:16 forename-surname Super v5.0.0[67471]: **** S.U.P.E.R.M.A.N. 5.0.0 - SUPER INSTALLATION ****
Wed Nov 06 12:12:16 forename-surname Super v5.0.0[67471]: Installation: Copying super to: /Library/Management/super/super
Wed Nov 06 12:12:16 forename-surname Super v5.0.0[67471]: Installation: Creating super search path link: /usr/local/bin/super
Wed Nov 06 12:12:16 forename-surname Super v5.0.0[67471]: Installation: Creating super LaunchDaemon helper: /Library/Management/super/super-starter
Wed Nov 06 12:12:16 forename-surname Super v5.0.0[67471]: Installation: Removing previous super LaunchDaemon: /Library/LaunchDaemons/com.macjutsu.super.plist
Wed Nov 06 12:12:16 forename-surname Super v5.0.0[67471]: Installation: Creating super LaunchDaemon: /Library/LaunchDaemons/com.macjutsu.super.plist.
Wed Nov 06 12:12:16 forename-surname Super v5.0.0[67471]: Installation: Setting permissions for installed super items.
Wed Nov 06 12:12:16 forename-surname Super v5.0.0[67471]: **** S.U.P.E.R.M.A.N. 5.0.0 - SUPER STARTUP ****
Wed Nov 06 12:12:17 forename-surname Super v5.0.0[67471]: Status: Mac computer with Apple silicon running: macOS Ventura 13.4-22F66
Wed Nov 06 12:12:17 forename-surname Super v5.0.0[67471]: Status: Last macOS startup was: 2024-08-01:11:56:34
Wed Nov 06 12:12:17 forename-surname Super v5.0.0[67471]: Status: Current active GUI user is: forename.surname@randomorg.co.uk (503)
Wed Nov 06 12:12:18 forename-surname Super v5.0.0[67471]: Warning: Automatic download and installation of macOS updates is currently enabled, this can result in updates being installed outside of super workflows.
Wed Nov 06 12:12:18 forename-surname Super v5.0.0[67471]: Status: Deleting all local (non-managed and non-authentication) preferences.
Wed Nov 06 12:12:20 forename-surname Super v5.0.0[67471]: Status: Managed by Jamf Pro 11.10.2 hosted at: https://randomorg.jamfcloud.com/
Wed Nov 06 12:12:20 forename-surname Super v5.0.0[67471]: Warning: IBM Notifier at path: /Library/Management/super/IBM Notifier.app is version 3.1.0, this does not match target version 3.2.1.
Wed Nov 06 12:12:21 forename-surname Super v5.0.0[67471]: Status: Removing previously installed IBM Notifier.app.
Wed Nov 06 12:12:21 forename-surname Super v5.0.0[67471]: Status: Attempting to download and install IBM Notifier.app...
Wed Nov 06 12:12:23 forename-surname Super v5.0.0[67471]: Status: Attempting to download new requested display icon from URL source...
Wed Nov 06 12:12:23 forename-surname Super v5.0.0[67471]: Status: Validated new diplay icon for light mode sourced from: https://storage.googleapis.com/email-assets-randomorg/brandingimage.png
Wed Nov 06 12:12:23 forename-surname Super v5.0.0[67471]: Status: Attempting to download new requested display icon from URL source...
Wed Nov 06 12:12:23 forename-surname Super v5.0.0[67471]: Status: Validated new diplay icon for dark mode sourced from: https://storage.googleapis.com/email-assets-randomorg/brandingimage.png
Wed Nov 06 12:12:23 forename-surname Super v5.0.0[67471]: Warning: Restart without updates workflow is enabled, this computer will restart even if there is no macOS update or upgrade available.
Wed Nov 06 12:12:24 forename-surname Super v5.0.0[67471]: Status: Deleting saved credentials for the --auth-jamf-client option.
Wed Nov 06 12:12:24 forename-surname Super v5.0.0[67471]: Status: A new automatic authentication password will be saved the next time a valid user succesfully authenticates.
Wed Nov 06 12:12:24 forename-surname Super v5.0.0[67471]: Status: Found that Jamf is installing or is the parent process, restarting via LaunchDaemon...
Wed Nov 06 12:12:24 forename-surname Super v5.0.0[67471]: **** S.U.P.E.R.M.A.N. 5.0.0 - EXIT AND RESTART WORKFLOW ****
Wed Nov 06 12:12:29 forename-surname super-starter[69529]: **** S.U.P.E.R.M.A.N. 5.0.0 - LAUNCHDAEMON ****
Wed Nov 06 12:12:29 forename-surname super[69579]: **** S.U.P.E.R.M.A.N. 5.0.0 - SUPER STARTUP ****
Wed Nov 06 12:12:29 forename-surname super[69579]: Status: Mac computer with Apple silicon running: macOS Ventura 13.4-22F66
Wed Nov 06 12:12:29 forename-surname super[69579]: Status: Last macOS startup was: 2024-08-01:11:56:34
Wed Nov 06 12:12:29 forename-surname super[69579]: Status: Current active GUI user is: forename.surname@randomorg.co.uk (503)
Wed Nov 06 12:12:30 forename-surname super[69579]: Warning: Automatic download and installation of macOS updates is currently enabled, this can result in updates being installed outside of super workflows.
Wed Nov 06 12:12:32 forename-surname super[69579]: Status: Managed by Jamf Pro 11.10.2 hosted at: https://randomorg.jamfcloud.com/
Wed Nov 06 12:12:32 forename-surname super[69579]: Warning: Restart without updates workflow is enabled, this computer will restart even if there is no macOS update or upgrade available.
Wed Nov 06 12:12:32 forename-surname super[69579]: Status: A new automatic authentication password will be saved the next time a valid user succesfully authenticates.
Wed Nov 06 12:12:32 forename-surname super[69579]: **** S.U.P.E.R.M.A.N. 5.0.0 - NOT CHECKING FOR SOFTWARE UPDATES/UPGRADES ****
Wed Nov 06 12:12:32 forename-surname super[69579]: Status: Setting new automatic zero date based on the Restart Without Updates workflow start date of 2024-11-06:12:12.
Wed Nov 06 12:12:32 forename-surname super[69579]: **** S.U.P.E.R.M.A.N. 5.0.0 - RESTART WITHOUT UPDATES/UPGRADES ****
Wed Nov 06 12:12:32 forename-surname super[69579]: Status: Hard maximum deferral count of 3 not passed with 3 remaining.
Wed Nov 06 12:12:32 forename-surname super[69579]: IBM Notifier: User choice dialog with no timeout.
Wed Nov 06 12:12:34 forename-surname super[69579]: Status: Resetting any workflow dates.
Wed Nov 06 12:12:34 forename-surname super[69579]: Status: Resetting any deadline counters.
Wed Nov 06 12:12:34 forename-surname super[69579]: Status: Full super workflow complete! The super workflow is scheduled to automatically relaunch in 360 minutes.
Wed Nov 06 12:12:34 forename-surname super[69579]: Exit: super is scheduled to automatically relaunch at: 2024-11-06:18:12:00
Wed Nov 06 12:12:34 forename-surname super[69579]: **** S.U.P.E.R.M.A.N. 5.0.0 - EXIT CLEAN ****
Wed Nov 06 15:02:50 forename-surname Super v5.0.0[7034]: **** S.U.P.E.R.M.A.N. 5.0.0 - SUPER INSTALLATION ****
Wed Nov 06 15:02:50 forename-surname Super v5.0.0[7034]: Installation: Copying super to: /Library/Management/super/super
Wed Nov 06 15:02:50 forename-surname Super v5.0.0[7034]: Installation: Creating super search path link: /usr/local/bin/super
Wed Nov 06 15:02:50 forename-surname Super v5.0.0[7034]: Installation: Creating super LaunchDaemon helper: /Library/Management/super/super-starter
Wed Nov 06 15:02:50 forename-surname Super v5.0.0[7034]: Installation: Removing previous super LaunchDaemon: /Library/LaunchDaemons/com.macjutsu.super.plist
Wed Nov 06 15:02:50 forename-surname Super v5.0.0[7034]: Installation: Creating super LaunchDaemon: /Library/LaunchDaemons/com.macjutsu.super.plist.
Wed Nov 06 15:02:50 forename-surname Super v5.0.0[7034]: Installation: Setting permissions for installed super items.
Wed Nov 06 15:02:51 forename-surname Super v5.0.0[7034]: **** S.U.P.E.R.M.A.N. 5.0.0 - SUPER STARTUP ****
Wed Nov 06 15:02:51 forename-surname Super v5.0.0[7034]: Status: Mac computer with Apple silicon running: macOS Ventura 13.4-22F66
Wed Nov 06 15:02:51 forename-surname Super v5.0.0[7034]: Status: Last macOS startup was: 2024-11-06:13:41:33
Wed Nov 06 15:02:51 forename-surname Super v5.0.0[7034]: Status: Current active GUI user is: forename.surname@randomorg.co.uk (503)
Wed Nov 06 15:02:53 forename-surname Super v5.0.0[7034]: Warning: Automatic download and installation of macOS updates is currently enabled, this can result in updates being installed outside of super workflows.
Wed Nov 06 15:02:53 forename-surname Super v5.0.0[7034]: Status: Deleting all local (non-managed and non-authentication) preferences.
Wed Nov 06 15:02:55 forename-surname Super v5.0.0[7034]: Status: Managed by Jamf Pro 11.10.2 hosted at: https://randomorg.jamfcloud.com/
Wed Nov 06 15:02:56 forename-surname Super v5.0.0[7034]: Status: Attempting to download new requested display icon from URL source...
Wed Nov 06 15:02:56 forename-surname Super v5.0.0[7034]: Status: Validated new diplay icon for light mode sourced from: https://storage.googleapis.com/email-assets-randomorg/brandingimage.png
Wed Nov 06 15:02:56 forename-surname Super v5.0.0[7034]: Status: Attempting to download new requested display icon from URL source...
Wed Nov 06 15:02:56 forename-surname Super v5.0.0[7034]: Status: Validated new diplay icon for dark mode sourced from: https://storage.googleapis.com/email-assets-randomorg/brandingimage.png
Wed Nov 06 15:02:57 forename-surname Super v5.0.0[7034]: Status: A new automatic authentication password will be saved the next time a valid user succesfully authenticates.
Wed Nov 06 15:02:57 forename-surname Super v5.0.0[7034]: Warning: Automatic macOS update/upgrade enforcement on Apple Silicon computers requires authentication credentials.
Wed Nov 06 15:02:57 forename-surname Super v5.0.0[7034]: Status: User authentication is required to perform a macOS update/upgrade.
Wed Nov 06 15:02:57 forename-surname Super v5.0.0[7034]: Status: Found that Jamf is installing or is the parent process, restarting via LaunchDaemon...
Wed Nov 06 15:02:57 forename-surname Super v5.0.0[7034]: **** S.U.P.E.R.M.A.N. 5.0.0 - EXIT AND RESTART WORKFLOW ****
Wed Nov 06 15:02:57 forename-surname Super v5.0.0[7747]: **** S.U.P.E.R.M.A.N. 5.0.0 - SUPER INSTALLATION ****
Wed Nov 06 15:02:57 forename-surname Super v5.0.0[7747]: Installation: Copying super to: /Library/Management/super/super
Wed Nov 06 15:02:57 forename-surname Super v5.0.0[7747]: Installation: Creating super search path link: /usr/local/bin/super
Wed Nov 06 15:02:57 forename-surname Super v5.0.0[7747]: Installation: Creating super LaunchDaemon helper: /Library/Management/super/super-starter
Wed Nov 06 15:02:57 forename-surname Super v5.0.0[7747]: Installation: Removing previous super LaunchDaemon: /Library/LaunchDaemons/com.macjutsu.super.plist
Wed Nov 06 15:02:57 forename-surname Super v5.0.0[7747]: Installation: Creating super LaunchDaemon: /Library/LaunchDaemons/com.macjutsu.super.plist.
Wed Nov 06 15:02:57 forename-surname Super v5.0.0[7747]: Installation: Setting permissions for installed super items.
Wed Nov 06 15:02:57 forename-surname Super v5.0.0[7747]: **** S.U.P.E.R.M.A.N. 5.0.0 - SUPER STARTUP ****
Wed Nov 06 15:02:58 forename-surname Super v5.0.0[7747]: Status: Mac computer with Apple silicon running: macOS Ventura 13.4-22F66
Wed Nov 06 15:02:58 forename-surname Super v5.0.0[7747]: Status: Last macOS startup was: 2024-11-06:13:41:33
Wed Nov 06 15:02:58 forename-surname Super v5.0.0[7747]: Status: Current active GUI user is: forename.surname@randomorg.co.uk (503)
Wed Nov 06 15:02:58 forename-surname Super v5.0.0[7747]: Warning: Automatic download and installation of macOS updates is currently enabled, this can result in updates being installed outside of super workflows.
Wed Nov 06 15:03:00 forename-surname Super v5.0.0[7747]: Status: Managed by Jamf Pro 11.10.2 hosted at: https://randomorg.jamfcloud.com/
Wed Nov 06 15:03:01 forename-surname Super v5.0.0[7747]: Auth Warning: The --auth-ask-user-to-save-password option overrides all other Apple silicon authentication methods.
Wed Nov 06 15:03:01 forename-surname Super v5.0.0[7747]: Auth Warning: Ignoring the --auth-jamf-client option.
Wed Nov 06 15:03:01 forename-surname Super v5.0.0[7747]: Status: A new automatic authentication password will be saved the next time a valid user succesfully authenticates.
Wed Nov 06 15:03:01 forename-surname Super v5.0.0[7747]: Warning: Automatic macOS update/upgrade enforcement on Apple Silicon computers requires authentication credentials.
Wed Nov 06 15:03:01 forename-surname Super v5.0.0[7747]: Status: User authentication is required to perform a macOS update/upgrade.
Wed Nov 06 15:03:01 forename-surname Super v5.0.0[7747]: Status: Found that Jamf is installing or is the parent process, restarting via LaunchDaemon...
Wed Nov 06 15:03:01 forename-surname Super v5.0.0[7747]: **** S.U.P.E.R.M.A.N. 5.0.0 - EXIT AND RESTART WORKFLOW ****
Wed Nov 06 15:03:02 forename-surname super-starter[8419]: **** S.U.P.E.R.M.A.N. 5.0.0 - LAUNCHDAEMON ****
Wed Nov 06 15:03:02 forename-surname super[8442]: **** S.U.P.E.R.M.A.N. 5.0.0 - SUPER STARTUP ****
Wed Nov 06 15:03:02 forename-surname super[8442]: Status: Mac computer with Apple silicon running: macOS Ventura 13.4-22F66
Wed Nov 06 15:03:02 forename-surname super[8442]: Status: Last macOS startup was: 2024-11-06:13:41:33
Wed Nov 06 15:03:02 forename-surname super[8442]: Status: Current active GUI user is: forename.surname@randomorg.co.uk (503)
Wed Nov 06 15:03:03 forename-surname super[8442]: Warning: Automatic download and installation of macOS updates is currently enabled, this can result in updates being installed outside of super workflows.
Wed Nov 06 15:03:05 forename-surname super[8442]: Status: Managed by Jamf Pro 11.10.2 hosted at: https://randomorg.jamfcloud.com/
Wed Nov 06 15:03:05 forename-surname super[8442]: Status: A new automatic authentication password will be saved the next time a valid user succesfully authenticates.
Wed Nov 06 15:03:05 forename-surname super[8442]: Warning: Automatic macOS update/upgrade enforcement on Apple Silicon computers requires authentication credentials.
Wed Nov 06 15:03:05 forename-surname super[8442]: Status: User authentication is required to perform a macOS update/upgrade.
Wed Nov 06 15:03:05 forename-surname super[8442]: **** S.U.P.E.R.M.A.N. 5.0.0 - CHECK FOR SOFTWARE UPDATES/UPGRADES ****
Wed Nov 06 15:03:06 forename-surname super[8442]: Status: Deferral restrictions have changed since last super workflow run, full software status check required.
Wed Nov 06 15:03:06 forename-surname super[8442]: Status: Restrictions configuration profile is deferring macOS major upgrades for 30 days.
Wed Nov 06 15:03:07 forename-surname super[8442]: mdmclient: Waiting for available updates listing...
Wed Nov 06 15:03:24 forename-surname super[8442]: Status: Some updates are deferred due to a restrictions deferral configuration profile.
Wed Nov 06 15:03:24 forename-surname super[8442]: Warning: Some updates are inaccurately reporting as deferred even though restrictions deferral configuration is not enabled. As such, these updates will still be considered for installation.
Wed Nov 06 15:03:24 forename-surname super[8442]: Restrictions Deferral: macOS major upgrade installer 1 of 3 is: DeferredUntil:2024-11-27 15:29:53,Title:macOS Sequoia,Version:15.1
Wed Nov 06 15:03:24 forename-surname super[8442]: Restrictions Deferral: macOS major upgrade installer 2 of 3 is: DeferredUntil:2024-11-20 19:01:19,Title:macOS Sequoia,Version:15.0.1
Wed Nov 06 15:03:24 forename-surname super[8442]: Restrictions Deferral: macOS major upgrade installer 3 of 3 is: DeferredUntil:2024-11-27 07:00:00,Title:macOS Sonoma,Version:14.7.1
Wed Nov 06 15:03:24 forename-surname super[8442]: Restrictions Deferral: macOS major upgrade 1 of 1 is: DeferredUntil:2024-12-04 00:00:00,Title:macOS Sequoia 15.1,Build:24B83,Version:15.1
Wed Nov 06 15:05:24 forename-surname super[8442]: mist-cli Error: macOS installers listing failed, check /Library/Management/super/logs/macos-installers-list.log for more detail.
Wed Nov 06 15:05:24 forename-surname super[8442]: mist-cli Error: macOS installers listing failed to complete, as indicated by no progress after waiting for 120 seconds.
Wed Nov 06 15:05:24 forename-surname super[8442]: Warning: Re-starting check for macOS installers...
Wed Nov 06 15:07:25 forename-surname super[8442]: mist-cli Error: macOS installers listing failed, check /Library/Management/super/logs/macos-installers-list.log for more detail.
Wed Nov 06 15:07:25 forename-surname super[8442]: mist-cli Error: macOS installers listing failed to complete, as indicated by no progress after waiting for 120 seconds.
Wed Nov 06 15:07:25 forename-surname super[8442]: Error: Checking for macOS installers listing did not return any available installers.
Wed Nov 06 15:07:25 forename-surname super[8442]: Error: Checking for macOS software status workflow failed, trying again in 60 minutes.
Wed Nov 06 15:07:25 forename-surname super[8442]: Exit: super is scheduled to automatically relaunch at: 2024-11-06:16:07:00
Wed Nov 06 15:07:25 forename-surname super[8442]: **** S.U.P.E.R.M.A.N. 5.0.0 - EXIT CLEAN ****
Wed Nov 06 15:32:11 forename-surname Super v5.0.0[15601]: **** S.U.P.E.R.M.A.N. 5.0.0 - SUPER INSTALLATION ****
Wed Nov 06 15:32:11 forename-surname Super v5.0.0[15601]: Installation: Copying super to: /Library/Management/super/super
Wed Nov 06 15:32:11 forename-surname Super v5.0.0[15601]: Installation: Creating super search path link: /usr/local/bin/super
Wed Nov 06 15:32:11 forename-surname Super v5.0.0[15601]: Installation: Creating super LaunchDaemon helper: /Library/Management/super/super-starter
Wed Nov 06 15:32:11 forename-surname Super v5.0.0[15601]: Installation: Removing previous super LaunchDaemon: /Library/LaunchDaemons/com.macjutsu.super.plist
Wed Nov 06 15:32:11 forename-surname Super v5.0.0[15601]: Installation: Creating super LaunchDaemon: /Library/LaunchDaemons/com.macjutsu.super.plist.
Wed Nov 06 15:32:11 forename-surname Super v5.0.0[15601]: Installation: Setting permissions for installed super items.
Wed Nov 06 15:32:11 forename-surname Super v5.0.0[15601]: **** S.U.P.E.R.M.A.N. 5.0.0 - SUPER STARTUP ****
Wed Nov 06 15:32:12 forename-surname Super v5.0.0[15601]: Status: Mac computer with Apple silicon running: macOS Ventura 13.4-22F66
Wed Nov 06 15:32:12 forename-surname Super v5.0.0[15601]: Status: Last macOS startup was: 2024-11-06:13:41:33
Wed Nov 06 15:32:12 forename-surname Super v5.0.0[15601]: Status: Current active GUI user is: forename.surname@randomorg.co.uk (503)
Wed Nov 06 15:32:12 forename-surname Super v5.0.0[15601]: Warning: Automatic download and installation of macOS updates is currently enabled, this can result in updates being installed outside of super workflows.
Wed Nov 06 15:32:12 forename-surname Super v5.0.0[15601]: Status: Deleting all local (non-managed and non-authentication) preferences.
Wed Nov 06 15:32:14 forename-surname Super v5.0.0[15601]: Status: Managed by Jamf Pro 11.10.2 hosted at: https://randomorg.jamfcloud.com/
Wed Nov 06 15:32:14 forename-surname Super v5.0.0[15601]: Status: Attempting to download new requested display icon from URL source...
Wed Nov 06 15:32:14 forename-surname Super v5.0.0[15601]: Status: Validated new diplay icon for light mode sourced from: https://storage.googleapis.com/email-assets-randomorg/brandingimage.png
Wed Nov 06 15:32:14 forename-surname Super v5.0.0[15601]: Status: Attempting to download new requested display icon from URL source...
Wed Nov 06 15:32:15 forename-surname Super v5.0.0[15601]: Status: Validated new diplay icon for dark mode sourced from: https://storage.googleapis.com/email-assets-randomorg/brandingimage.png
Wed Nov 06 15:32:15 forename-surname Super v5.0.0[15601]: Status: A new automatic authentication password will be saved the next time a valid user succesfully authenticates.
Wed Nov 06 15:32:15 forename-surname Super v5.0.0[15601]: Warning: Automatic macOS update/upgrade enforcement on Apple Silicon computers requires authentication credentials.
Wed Nov 06 15:32:15 forename-surname Super v5.0.0[15601]: Status: User authentication is required to perform a macOS update/upgrade.
Wed Nov 06 15:32:15 forename-surname Super v5.0.0[15601]: Status: Found that Jamf is installing or is the parent process, restarting via LaunchDaemon...
Wed Nov 06 15:32:15 forename-surname Super v5.0.0[15601]: **** S.U.P.E.R.M.A.N. 5.0.0 - EXIT AND RESTART WORKFLOW ****
Wed Nov 06 15:32:15 forename-surname Super v5.0.0[16352]: **** S.U.P.E.R.M.A.N. 5.0.0 - SUPER INSTALLATION ****
Wed Nov 06 15:32:15 forename-surname Super v5.0.0[16352]: Installation: Copying super to: /Library/Management/super/super
Wed Nov 06 15:32:15 forename-surname Super v5.0.0[16352]: Installation: Creating super search path link: /usr/local/bin/super
Wed Nov 06 15:32:15 forename-surname Super v5.0.0[16352]: Installation: Creating super LaunchDaemon helper: /Library/Management/super/super-starter
Wed Nov 06 15:32:15 forename-surname Super v5.0.0[16352]: Installation: Removing previous super LaunchDaemon: /Library/LaunchDaemons/com.macjutsu.super.plist
Wed Nov 06 15:32:15 forename-surname Super v5.0.0[16352]: Installation: Creating super LaunchDaemon: /Library/LaunchDaemons/com.macjutsu.super.plist.
Wed Nov 06 15:32:15 forename-surname Super v5.0.0[16352]: Installation: Setting permissions for installed super items.
Wed Nov 06 15:32:15 forename-surname Super v5.0.0[16352]: **** S.U.P.E.R.M.A.N. 5.0.0 - SUPER STARTUP ****
Wed Nov 06 15:32:16 forename-surname Super v5.0.0[16352]: Status: Mac computer with Apple silicon running: macOS Ventura 13.4-22F66
Wed Nov 06 15:32:16 forename-surname Super v5.0.0[16352]: Status: Last macOS startup was: 2024-11-06:13:41:33
Wed Nov 06 15:32:16 forename-surname Super v5.0.0[16352]: Status: Current active GUI user is: forename.surname@randomorg.co.uk (503)
Wed Nov 06 15:32:16 forename-surname Super v5.0.0[16352]: Warning: Automatic download and installation of macOS updates is currently enabled, this can result in updates being installed outside of super workflows.
Wed Nov 06 15:32:17 forename-surname Super v5.0.0[16352]: Status: Managed by Jamf Pro 11.10.2 hosted at: https://randomorg.jamfcloud.com/
Wed Nov 06 15:32:18 forename-surname Super v5.0.0[16352]: Auth Warning: The --auth-ask-user-to-save-password option overrides all other Apple silicon authentication methods.
Wed Nov 06 15:32:18 forename-surname Super v5.0.0[16352]: Auth Warning: Ignoring the --auth-jamf-client option.
Wed Nov 06 15:32:18 forename-surname Super v5.0.0[16352]: Status: A new automatic authentication password will be saved the next time a valid user succesfully authenticates.
Wed Nov 06 15:32:18 forename-surname Super v5.0.0[16352]: Warning: Automatic macOS update/upgrade enforcement on Apple Silicon computers requires authentication credentials.
Wed Nov 06 15:32:18 forename-surname Super v5.0.0[16352]: Status: User authentication is required to perform a macOS update/upgrade.
Wed Nov 06 15:32:18 forename-surname Super v5.0.0[16352]: Status: Found that Jamf is installing or is the parent process, restarting via LaunchDaemon...
Wed Nov 06 15:32:18 forename-surname Super v5.0.0[16352]: **** S.U.P.E.R.M.A.N. 5.0.0 - EXIT AND RESTART WORKFLOW ****
Wed Nov 06 15:32:20 forename-surname super-starter[17227]: **** S.U.P.E.R.M.A.N. 5.0.0 - LAUNCHDAEMON ****
Wed Nov 06 15:32:20 forename-surname super[17250]: **** S.U.P.E.R.M.A.N. 5.0.0 - SUPER STARTUP ****
Wed Nov 06 15:32:20 forename-surname super[17250]: Status: Mac computer with Apple silicon running: macOS Ventura 13.4-22F66
Wed Nov 06 15:32:20 forename-surname super[17250]: Status: Last macOS startup was: 2024-11-06:13:41:33
Wed Nov 06 15:32:20 forename-surname super[17250]: Status: Current active GUI user is: forename.surname@randomorg.co.uk (503)
Wed Nov 06 15:32:21 forename-surname super[17250]: Warning: Automatic download and installation of macOS updates is currently enabled, this can result in updates being installed outside of super workflows.
Wed Nov 06 15:32:23 forename-surname super[17250]: Status: Managed by Jamf Pro 11.10.2 hosted at: https://randomorg.jamfcloud.com/
Wed Nov 06 15:32:24 forename-surname super[17250]: Status: A new automatic authentication password will be saved the next time a valid user succesfully authenticates.
Wed Nov 06 15:32:24 forename-surname super[17250]: Warning: Automatic macOS update/upgrade enforcement on Apple Silicon computers requires authentication credentials.
Wed Nov 06 15:32:24 forename-surname super[17250]: Status: User authentication is required to perform a macOS update/upgrade.
Wed Nov 06 15:32:24 forename-surname super[17250]: **** S.U.P.E.R.M.A.N. 5.0.0 - CHECK FOR SOFTWARE UPDATES/UPGRADES ****
Wed Nov 06 15:32:24 forename-surname super[17250]: Status: Deferral restrictions have changed since last super workflow run, full software status check required.
Wed Nov 06 15:32:24 forename-surname super[17250]: Status: Restrictions configuration profile is deferring macOS major upgrades for 30 days.
Wed Nov 06 15:32:25 forename-surname super[17250]: mdmclient: Waiting for available updates listing...
Wed Nov 06 15:32:41 forename-surname super[17250]: Status: Some updates are deferred due to a restrictions deferral configuration profile.
Wed Nov 06 15:32:41 forename-surname super[17250]: Warning: Some updates are inaccurately reporting as deferred even though restrictions deferral configuration is not enabled. As such, these updates will still be considered for installation.
Wed Nov 06 15:32:41 forename-surname super[17250]: Restrictions Deferral: macOS major upgrade installer 1 of 3 is: DeferredUntil:2024-11-27 15:29:53,Title:macOS Sequoia,Version:15.1
Wed Nov 06 15:32:41 forename-surname super[17250]: Restrictions Deferral: macOS major upgrade installer 2 of 3 is: DeferredUntil:2024-11-20 19:01:19,Title:macOS Sequoia,Version:15.0.1
Wed Nov 06 15:32:41 forename-surname super[17250]: Restrictions Deferral: macOS major upgrade installer 3 of 3 is: DeferredUntil:2024-11-27 07:00:00,Title:macOS Sonoma,Version:14.7.1
Wed Nov 06 15:32:41 forename-surname super[17250]: Restrictions Deferral: macOS major upgrade 1 of 1 is: DeferredUntil:2024-12-04 00:00:00,Title:macOS Sequoia 15.1,Build:24B83,Version:15.1
Wed Nov 06 15:34:41 forename-surname super[17250]: mist-cli Error: macOS installers listing failed, check /Library/Management/super/logs/macos-installers-list.log for more detail.
Wed Nov 06 15:34:41 forename-surname super[17250]: mist-cli Error: macOS installers listing failed to complete, as indicated by no progress after waiting for 120 seconds.
Wed Nov 06 15:34:41 forename-surname super[17250]: Warning: Re-starting check for macOS installers...
Wed Nov 06 15:36:42 forename-surname super[17250]: mist-cli Error: macOS installers listing failed, check /Library/Management/super/logs/macos-installers-list.log for more detail.
Wed Nov 06 15:36:42 forename-surname super[17250]: mist-cli Error: macOS installers listing failed to complete, as indicated by no progress after waiting for 120 seconds.
Wed Nov 06 15:36:42 forename-surname super[17250]: Error: Checking for macOS installers listing did not return any available installers.
Wed Nov 06 15:36:42 forename-surname super[17250]: Error: Checking for macOS software status workflow failed, trying again in 60 minutes.
Wed Nov 06 15:36:42 forename-surname super[17250]: Exit: super is scheduled to automatically relaunch at: 2024-11-06:16:36:00
Wed Nov 06 15:36:42 forename-surname super[17250]: **** S.U.P.E.R.M.A.N. 5.0.0 - EXIT CLEAN ****
`

**Comment by Macjutsu** [comment]
First, you should edit your post... there is risky identifiable information about your organization that you just posted for the world to see.

Second, the last lines in the log you posted are literally telling you what to look at next.

```
mist-cli Error: macOS installers listing failed, check /Library/Management/super/logs/macos-installers-list.log for more detail.
```

https://github.com/Macjutsu/super/wiki/Troubleshooting#understanding-sub-process-logs

**Comment by Luke-From-IT** [comment]
Hi, I have posted the result of that in the orignal post already. mist-cli no such file or directory, super is meant to install this, no?

/Library/Management/super/logs/macos-installers-list.log
/Library/Management/super/super: line 6084: /usr/local/bin/mist: No such file or directory

**Comment by Macjutsu** [comment]
`super` is supposed to install both automatically. 

Try a `--reset-super` on that device... if it persists... the next troubleshooting step is to run `super` with `--verbose-mode` enabled and look for log lines specifically generated from the following functions: `manage_helpers` `check_mist_cli` and `get_mist_cli`

**Comment by Luke-From-IT** [comment]
Will try that when the client is back online. Thank you Kevin

**Comment by Luke-From-IT** [comment]
Doing a --reset-super and then re-running the workflow worked.

Thanks.
