### ISSUE TITLE
Soft and Hard Dates not showing up

### ISSUE THREAD

**Issue by monstar3** [Macjutsu/super#253]
I am implementing super and I can't get my soft and hard dates to appear in the dialogue box. Here is my script, I must be missing something.

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>JamfProID</key>
<string>$JSSID</string>
<key>InstallMacOSMajorUpgrades</key>
	<true/>
	<key>InstallMacOSMajorVersionTarget</key>
	<string>15</string>
	<key>InstallRapidSecurityResponses</key>
	<true/>
	<key>InstallNonSystemUpdatesWithoutRestarting</key>
	<true/>
        <key>DeferralTimerDefault</key>
        <string>60</string>
        <true/>
         <key>SoftDate</key>
         <string>2024-11-12:17:00</string>
        <key>HardDate</key>
        <string>2024-11-13:14:00</string>
        <key>DisplayHelpButtonString</key>
        <string>For assistance please contact helpdesk at extension 4357</string>
</dict>
</plist>

**Comment by Macjutsu** [comment]
The example text you posted for "my script" is not formated as a script... it almost looks similar to the format for a configuration profile... but even that isn't correct syntax in your example...  as such your question doesn't make sense to me.

Unless you can show an example of your settings in the proper syntax of the command line or a configuration profile... then I can't help you.

**Comment by monstar3** [comment]
Yes it is a config profile, I made a plist based of your config profile commands on the wiki. I have attached what I have in the config. It is working but I set hard and soft dates and they are not popping up in the update pop box. It say's not dates or deferrals have been set. 
[Config profile.txt](https://github.com/user-attachments/files/17722465/Config.profile.txt)

**Comment by Macjutsu** [comment]
The configuration profile keys should be `DeadlineDateHard` and `DeadlineDateSoft`... looks like you referenced some typos on the Wiki... I've updated the Wiki with the correct keys.

https://github.com/Macjutsu/super/wiki/Date-Deadlines
