### ISSUE TITLE
"Over-The-Air" macOS Major Upgrade Is Available But Not Allowed

### ISSUE THREAD

**Issue by TechGeekMac** [Macjutsu/super#262]
Got an odd issue with some Macs, that it is failing to run the "over-the-air" macOS major upgrades due to it being "not allowed".

The upgrade it is failing to run is 15.1.1 and I've got the deferral to be 14 days, and 15.1.1 is now older than that.

Any idea on what the issue is here? Any clues?

I've included the log output for reference...

> Mon Dec 09 03:43:38 ◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼ super-starter[41698]: **** S.U.P.E.R.M.A.N. 5.0.0 - LAUNCHDAEMON ****
Mon Dec 09 03:43:39 ◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼ super[41713]: **** S.U.P.E.R.M.A.N. 5.0.0 - SUPER STARTUP ****
Mon Dec 09 03:43:39 ◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼ super[41713]: Status: Mac computer with Intel running: macOS Sonoma 14.7.1-23H222
Mon Dec 09 03:43:39 ◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼ super[41713]: Status: Last macOS startup was: 2024-12-05:15:27:41
Mon Dec 09 03:43:39 ◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼ super[41713]: Status: Current active GUI user is: ◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼ (◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼)
Mon Dec 09 03:43:44 ◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼ super[41713]: Status: Managed by Jamf Pro 11.11.1 hosted at: https://◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼/
Mon Dec 09 03:43:44 ◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼ super[41713]: Status: macOS update/upgrade workflows automatically authenticated via system account (root).
Mon Dec 09 03:43:44 ◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼ super[41713]: **** S.U.P.E.R.M.A.N. 5.0.0 - CHECK FOR SOFTWARE UPDATES/UPGRADES ****
Mon Dec 09 03:43:44 ◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼ super[41713]: Status: Last macOS software update check was more than 6 hours ago, full software status check required.
Mon Dec 09 03:43:44 ◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼ super[41713]: Status: Restrictions configuration profile is deferring macOS major upgrades for 14 days.
Mon Dec 09 03:43:44 ◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼ super[41713]: Status: Restrictions configuration profile is deferring macOS minor updates for 14 days.
Mon Dec 09 03:43:44 ◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼ super[41713]: Status: Restrictions configuration profile is deferring non-system updates for 14 days.
Mon Dec 09 03:43:55 ◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼ super[41713]: mdmclient: Waiting for available updates listing...
Mon Dec 09 03:43:59 ◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼ super[41713]: Status: Some updates are deferred due to a restrictions deferral configuration profile.
Mon Dec 09 03:43:59 ◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼ super[41713]: Restrictions Deferral: Non-system update 1 of 1 is: DeferredUntil:2024-12-16 21:12:36,Title:Safari,Version:18.1.1
Mon Dec 09 03:43:59 ◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼ super[41713]: Disallowed: The following "over-the-air" macOS major upgrades are available but not allowed:
Mon Dec 09 03:43:59 ◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼ super[41713]: Disallowed: macOS major upgrade 1 of 1 is: Title:macOS Sequoia 15.1.1,Build:24B91,Version:15.1.1
Mon Dec 09 03:43:59 ◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼ super[41713]: softwareupdate: Waiting for available updates listing...
Mon Dec 09 03:44:06 ◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼ super[41713]: Status: Resetting any workflow dates.
Mon Dec 09 03:44:06 ◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼ super[41713]: Status: Resetting any deadline counters.
Mon Dec 09 03:44:06 ◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼ super[41713]: Status: Full super workflow complete! The super workflow is scheduled to automatically relaunch in 360 minutes.
Mon Dec 09 03:44:06 ◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼ super[41713]: Exit: super is scheduled to automatically relaunch at: 2024-12-09:09:44:00
Mon Dec 09 03:44:06 ◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼︎◼ super[41713]: **** S.U.P.E.R.M.A.N. 5.0.0 - EXIT CLEAN ****

Many thanks.

**Comment by chriskeavey-kkl** [comment]
Have you checked the target version in your configuration profile?

    <key>InstallMacOSMajorVersionTarget</key>
    <string>15</string>
    
   The default from the example provided in the repo is 14.

**Comment by TechGeekMac** [comment]
Thanks @chriskeavey-kkl, that wasn't the exact key but did see that I mistakenly forgot to change the value for `<key>InstallMacOSMajorUpgrades</key>`

I have several super configs covering different areas of the business and forgot to change this key in this particular config!

My own fault. Cheers.
