### ISSUE TITLE
Uninstalling?

### ISSUE THREAD

**Issue by magnusviri** [Macjutsu/super#27]
Since super installs itself, is it plausible to add the ability to uninstall itself?

**Comment by Macjutsu** [comment]
I don't know that I need to write a full-blown feature... A very simple script will suffice.

```
#!/bin/bash
rm -Rf /Library/Management/super
rm -Rf /Library/LaunchDaemons/com.macjutsu.super.plist
exit 0

```
I may make something more formal and stick it in the wiki... so I'll keep this open as a reminder.

**Comment by Macjutsu** [comment]
Please check out this [new script](https://github.com/Macjutsu/super/blob/3.0b1/Super-Friends/Remove-super.sh) I posted with the release of [`super` v3.0b1](https://github.com/Macjutsu/super/releases/tag/v3.0-b1).
