### ISSUE TITLE
software update connectivity

### ISSUE THREAD

**Issue by jamesdurler** [Macjutsu/super#28]
In our environment we tunnel all connectivity through a VPN. The machines will pass the check that a connection is valid as the wifi is enabled and active , however there can be the instance where the VPN has not established and therefore we have no connectivity out to apple.

From my testing with super in the above scenario the logs exit with error code 1 with the line "Unable to parse Apple softwareupdate results".

The issue I'm seeing is after this point no launchdaemon is recreated so super never runs again. I had a look at the script and this appears to be happening at line 2240 to 2244 - If you add the function call 'makeLaunchDaemonCalendar' to line 2243 - just before sending S.U.P.E.R.M.A.N EXIT to the logs it resolves the issue

The other thing you could do is have a connectivity check out to apple at the same point you check the network interfaces but I think the above is easier

**Comment by Macjutsu** [comment]
This should be resolved with [`super` v3.0b1](https://github.com/Macjutsu/super/releases/tag/v3.0-b1). Thanks!
