### ISSUE TITLE
custom API Variable

### ISSUE THREAD

**Issue by tranziq** [Macjutsu/super#29]
Need a variable to customize what server the API request gets pointed to.   we have a dedicated api node to offload all the API traffic from our other nodes and would love to point super’s API calls other than using the local config.

**Comment by Macjutsu** [comment]
This is a good idea. I'll try to squeeze it into one of the 3.0 releases.

**Comment by Macjutsu** [comment]
https://github.com/Macjutsu/super/releases/tag/v4.0.0-beta1
