### ISSUE TITLE
3.0b1 - Timeout function killing process during prepare step

### ISSUE THREAD

**Issue by iDrewbs** [Macjutsu/super#33]
During the update prepare step, the process is killed after 300 seconds preventing it from completing. The log indicates the timeout was for the download step, but that step was already completed. 
I tried to re-run the process and had the same result on each of four attempts.
Here are the two lines from the log. I've also attached the complete log files if needed (it will be the most recent run attempt starting Sat Oct 22 10:03:02)

`Sat Oct 22 10:18:41 ZG13088 super[35311]: Status: Download complete, now preparing system update/upgrade, should be done in a few minutes...
Sat Oct 22 10:25:51 ZG13088 super[35311]: Error: Download of system update/upgrade via MDM push command timed out after 300 seconds, trying again in 3599 seconds.
`

[super.log](https://github.com/Macjutsu/super/files/9844953/super.log)
[update.log](https://github.com/Macjutsu/super/files/9844955/update.log)
[asu.log](https://github.com/Macjutsu/super/files/9844958/asu.log)
[mdm.log](https://github.com/Macjutsu/super/files/9844957/mdm.log)

**Comment by Macjutsu** [comment]
First, the "download" workflow is actually two steps, download followed by a prepare. In my testing, the prepare log entries were slower to respond than the download log entries, but never more than five minutes between updates.

However, it looks like in your testing repair. Log entries are returning slower than five minutes apart. Feel free to modify the '$defaultTimeoutSECONDS' variable for a longer time out.

If that was successful for you, please provide feedback as to what your longest log entry delay time was.

**Comment by iDrewbs** [comment]
Ah ok, I understand now. The timeout isn't based on the total time for the prepare to complete; it's based on the time between the log entries posted in the update.log during the prepare. 
You're right; 5 minutes seems like a long time between entries. I set it for 7 minutes to test, and It looks like the longest gap between entries was 5 minutes and 30 seconds.

**Comment by iDrewbs** [comment]
It looks like several more testers are running into this same issue. I think if it’s increased to 360 seconds that should cover the longest gap I’ve been seeing.
