### ISSUE TITLE
Feature request: Different Defer time for errors

### ISSUE THREAD

**Issue by wakco** [Macjutsu/super#34]
I just noticed what happens when an error occurs, in that super uses the DefaultDefer setting to check again later. Problem is, there is no feedback to the user when that happens if super was manually started.

What I would like to see is the option to set a much shorter automated defer on errors such as "Error: Download of system update/upgrade via MDM push command timed out after 300 seconds, trying again in 86400 seconds", and something to identify when such an error has occurred from a manual (i.e. jamf self service start) to report to the user an error occurred and that it will try again automatically after the error timeout.

With this is mind, I'm thinking settings like:
```
--ErrorDefer=<secondcount>
--ErrorCount=<max number of retries separated by ErrorDefer>
--NotifyErrorOn (and matching super's settings style:) --NotifyErrorOff
```
The first two can be Config Profile options as well, while the 3rd should be command line only. NotifyError can be stored and automatically removed either upon successful update or ErrorCount exceeded along with a final notification. These should only apply to actual errors, such as the timeout example above.

**Comment by Macjutsu** [comment]
First issue is really that there needs to be different timeouts for each "phase" of the update. This is something I plan to implement in a future 3.0 release. Though I will likely not expose the timings as an individual options, but instead as a series of default parameters internal to the script.

In general, `super` needs a "Self Service" mode with the assumption that a user would benefit from persistent dialogs during the entire download/prepare/update workflow. This is something I plan to implement in the future, but probably not in the 3.0 timeline. The reasoning is that I plan to replace the notification system with SwiftDialog and at that point I will re-evaluate other dialog workflows... like a "Self Service" mode.

**Comment by Macjutsu** [comment]
Done! These don't need to be options though... they can just be variables in the script as they shouldn't need to be changed too often.

https://github.com/Macjutsu/super/releases/tag/v3.0-b3
