### ISSUE TITLE
Issue: API - Computers Create and Read Removed - Super doesnt run

### ISSUE THREAD

**Issue by blakeusblade** [Macjutsu/super#36]
Using the API method here.

While the documentation and logging says to remove Create, and Read computer object permission in Jamf Pro, doing so causes super to not run with the following.

Error: Unable to request Blank Push via Jamf Pro API account "INSERT_API_ACCOUNT". Verify this account has has the privileges " Jamf Pro Server Objects > Computers > Create & Read".

Enabling this this resolves the problem however exposes our jamf pro server to risk.

**Comment by blakeusblade** [comment]
FYI... I created this FR on ideas.jamfcom for this
https://ideas.jamf.com/ideas/JN-I-26489

**Comment by iDrewbs** [comment]
Mine works without those permissions. I believe the last I saw that error message is when the config profile to grab the computer ID wasn’t scoped properly, and another is when I had the password for the API account entered incorrectly. It should work without Create & Read permissions

**Comment by Macjutsu** [comment]
[Per the wiki](https://github.com/Macjutsu/super/wiki/Jamf-Pro-API-Credentials#jamf-pro-id-via-mdm-configuration-profile) the "Computers Read" permission is not required.

Further, there is nothing I can do in `super` to harden the Jamf Pro API requirements. This is Jamf's problem.
