### ISSUE TITLE
Issue: Creating a PPPC setting without the binary being signed

### ISSUE THREAD

**Issue by blakeusblade** [Macjutsu/super#38]
It appears that the super and super-starter binary isn't signed and therefore can't make a PPPC setting.

Unless I'm missing something

**Comment by Macjutsu** [comment]
[Per the wiki](https://github.com/Macjutsu/super/wiki/Local-Update-Credentials#pppc-requirements-to-create-the-super-service-account), a PPPC config profile is only required when you have `super` create a local service account. Even then, you don't allow `super` itself, instead you allow the process that starts/installs `super` the very first time. For example, when deploying via Jamf Pro, you would need a PPPC for the local jamf items. [Again per the wiki](https://github.com/Macjutsu/super/wiki/Jamf-Pro-Deployment#jamf-pro-configuration-profile-payloads).
