### ISSUE TITLE
Feature Request - Safari Updates - Notify user that Safari will be closed

### ISSUE THREAD

**Issue by iDrewbs** [Macjutsu/super#41]
One of the complaints I've received is when there's an update to Safari, it will just close without any notification to the user. It would be helpful in V5 with SwiftDialog to have the option to display a notification to the user that Safari will quit if there's an update for it. 
If that's not feasible then perhaps an option added to ignore updates to Safari, but that wouldnt be the most ideal scenario.

**Comment by Macjutsu** [comment]
I think maybe the easiest/cleanest solution here is an option to push the "non-system" updates like Safari to after the system restarts. Then we wouldn't even need more dialogs.

**Comment by iDrewbs** [comment]
Yeah I think that would work. The only question would be how to handle cases where only "non-system" updates are available

**Comment by Macjutsu** [comment]
Yeah... then we would need a new dialog.... yeah... that might need to wait until v5

**Comment by Macjutsu** [comment]
Please check out the `super` [v3.0b4](https://github.com/Macjutsu/super/releases/tag/v3.0-b4). All recommended (non-macOS) updates install after the system restart.
