### ISSUE TITLE
Feature Request: Add static option to run jamf policy after update has applied

### ISSUE THREAD

**Issue by blakeusblade** [Macjutsu/super#42]
Add the option to run a jamf policy after the update has applied.

Such as or example
--postupdatereboot-runjamfpolicy

Adds into the configuration
`<key>RunJamfPolicyAfterUpdateReboot</key>`
`<true/>`

Which runs any policy with the Custom Trigger of "SupermanRunAfterUpdateReboot" after the machine has rebooted. Assuming there are policies set with that custom trigger.

Customers would only need to put policies in with that trigger.

**Comment by Macjutsu** [comment]
This would be a good addition... but more likely to add in v4.0 timeframe.

**Comment by Macjutsu** [comment]
I've decided to re-organize the workflow so all non-restart updates are going to happen after the restart as a default behavior... so you got luck and this one is moving to v3.0.
