### ISSUE TITLE
Feature request: Check and UI message for low hard drive space

### ISSUE THREAD

**Issue by mauriciope** [Macjutsu/super#44]
We know that Apple is moving to a smaller upgrade solution but we may still have the cases of lack of hard drive space to do the job.
I know via Jamf Pro we could run some pre-checks and warn end users to clean up before pushing SUPER out, but still the script is local and could handle the check there and then.

**Comment by Macjutsu** [comment]
This is already planned for v4.

**Comment by mauriciope** [comment]
Thank you
