### ISSUE TITLE
Defer menu not working corectly from profile (Jamf)

### ISSUE THREAD

**Issue by kalaklanar** [Macjutsu/super#47]
I've got everything working as I'd like using command line configuration options, but when I convert them to a Configuration Profile and put it in jamf, deferring thorough the notification menu is failing in a weird way. It adds 2 hours to whatever is selected by the client to defer. Specifically, I've tested 5 and 15 minutes out of the selection with the menu set to `<key>MenuDefer</key><string>300,900,3600,7200,14400,28800</string>`. I'm attaching a log as well - [super.log](https://github.com/Macjutsu/super/files/9981061/super.log) - with the notable events starting at Tue Nov 08 11:05:41. Attached is the profile file as well. [super.plist.txt](https://github.com/Macjutsu/super/files/9981087/super.plist.txt)

**Comment by kalaklanar** [comment]
My mistake - the 15 minute selection seems to be going longer than 2:15, with it being 3:15 for the second deferment box.

**Comment by Macjutsu** [comment]
I'll eventually look into this... currently trying to put out the dumpster-fire that is the macOS 13 update/upgrade process. If I can confirm this bug then I will get it fixed in the v3.0 timeframe.

**Comment by dorminyk** [comment]
This may or may not help;
I'm utilizing Jamf and have an Extension Attribute with the following... This helps me determine what version that we're working with on certain machines.

> #!/bin/bash
if [[ -d /Library/Management/Super ]]; then
superVer=$( cat /Library/Management/super/super | grep "# Version" |awk '{print $3}' )
echo <result> $superVer</result>
else
echo <result>Not installed</result>"
fi

**Comment by Macjutsu** [comment]
I can't replicate this issue. In my testing, using your exact same `<string>` the LaunchDaemon is being created properly. 

Can you send an example LaunchDaemon showing an incorrect time being generated by `super`? You can also do this directly from `super` with `--verbose-mode`.

**Comment by kalaklanar** [comment]
I had this happening on 2 different machines, but I can't get it to happen now.
