### ISSUE TITLE
FR / Bug: 3.0-b3 - majorUpgradeNAMES and majorUpgradeNAME variables blank

### ISSUE THREAD

**Issue by master-vodawagner** [Macjutsu/super#49]
This could be a either a FR or bug depending on things

As the below example isn't a MAJOR update, 

Should the majorUpgradeNAMES and majorUpgradeNAME variables be blank or perhaps fill with "No Major version detected" ?

Fri Dec 02 14:24:10 X2102825 super[29857]: Verbose Mode: Function checkAllAvailableSoftware: availableOSUPDATES is: === OS Update Item ===
Product Key:               MSU_UPDATE_22C5059b_patch_13.1_minor
Title:                     macOS Ventura 13.1 Beta 4
Version:                   13.1 <Build: 22C5059b> <PMV: 13.1>
Deferred:                  no  (Date: )
Tags:                      (null)
MacOSUpdate:               YES
MSU:                       YES  (Major: no  Full: no  DL: no  label: macOS Ventura 13.1 Beta 4-22C5059b)
Splat:                     no  <(null)> (Revoked: no)
IsMacOSUpdate():           YES
IsMajorOSUpdateViaIA():    no
Available updates (install debug profile for more details): (
        {
        AllowsInstallLater = 1;
        AppIdentifiersToClose =         (
        );
        Build = 22C5059b;
        DownloadSize = 1135939717;
        HumanReadableName = "macOS Ventura 13.1 Beta 4";
        HumanReadableNameLocale = "en-GB";
        IsConfigDataUpdate = 0;
        IsCritical = 0;
        IsFirmwareUpdate = 0;
        IsSecurityResponse = 0;
        ProductKey = "MSU_UPDATE_22C5059b_patch_13.1_minor";
        RequiresBootstrapToken = 1;
        RestartRequired = 1;
        SupplementalBuildVersion = 22C5059b;
        Version = "13.1";
    }
)
Fri Dec 02 14:24:10 X2102825 super[29857]: Verbose Mode: Function checkAllAvailableSoftware: majorUpgradeNAMES is: 
Fri Dec 02 14:24:10 X2102825 super[29857]: Status: No available major system upgrade. May be deferred via MDM.
Fri Dec 02 14:24:10 X2102825 super[29857]: Verbose Mode: Function checkAllAvailableSoftware: majorUpgradeVERSION is: FALSE
Fri Dec 02 14:24:10 X2102825 super[29857]: Verbose Mode: Function checkAllAvailableSoftware: majorUpgradeNAME is:

**Comment by Macjutsu** [comment]
This whole thing is being rewritten next beta will be soon to resolve this issue and many more.

**Comment by Macjutsu** [comment]
Please check out the `super` [v3.0b4](https://github.com/Macjutsu/super/releases/tag/v3.0-b4) as it has a completely rearchitected download workflow.
