### ISSUE TITLE
Deferrals not working on some users. Skipped Straight to restart

### ISSUE THREAD

**Issue by agrantdrs** [Macjutsu/super#50]
It is working great for the most part! But I had a user come to me with an issue where they did not get a deferral option. It gave them the "you have deferred the maximum number of 5 times. A required software updated will automatically restart this computer in about 5 minutes." Which unfortunately came at an inopportune time. I have included the log with the notable events starting at 14:57 :[mysuper.log](https://github.com/Macjutsu/super/files/10229880/mysuper.log)

and the deferment plist: 
<dict>
	<key>JamfProID</key>
	<string>$JSSID</string>
	<key>MenuDefer</key>
	<string>300,1800,3600,7200</string>
	<key>FocusCount</key>
	<string>5</string>
        <key>HardCount</key>
        <string>5</string>
	<key>FocusDays</key>
	<string>2</string>
	<key>DisplayRedraw</key>
	<string>10800</string>
	<key>DisplayIcon</key>
        <string>/private/var/tmp/icon_for_superman/icon.icns</string>
	<key>IconSizeIbm</key>
	<string>128</string>
	<key>IconSizeJamf</key>
	<string>128</string>
        <key>ForceRestart</key>
        <false/> 
</dict>

**Comment by Macjutsu** [comment]
You shouldn't be running `super` v2 on that system... please see the latest release notes... https://github.com/Macjutsu/super/releases
