### ISSUE TITLE
Feature Request: allow non is updates but defer all is updates

### ISSUE THREAD

**Issue by bigSteve2001** [Macjutsu/super#51]
If this is possible it would be very helpful to have a defer any OS update but still install items like Safari and Xcode

**Comment by Macjutsu** [comment]
Two problems here... one fixable with code... the other would have to be an Apple fix.

1. Assuming the apps that need updates are running... there would have to be a flow in `super` to accommodate for this and provide another entire layer of dialogs with deferrals and deadlines... that would be adding significant complications.

2. In testing I found that installing non-macOS updates first is a reliable method to break the `softwareupdate --list` function... thus breaking the ability to install macOS updates/upgrades.
