### ISSUE TITLE
Super will need to have its logic updated to handle Rapid Security Responses patches

### ISSUE THREAD

**Issue by master-vodawagner** [Macjutsu/super#52]
More of a heads up as I know the posture on macOS beta support atm

I'm guessing super's OS logic will need to be updated to factor in RSR updates that add on a letter on to the build number of an OS

"Error: Downloaded macOS update version of 13.2 doesn't match expected version 13.2 (a), trying again in 120 seconds."

**Comment by master-vodawagner** [comment]
Looks like the logic will need the following extra argument in the /System/Volumes/Update/Update update-asset-attributes 

ProductVersionExtra

For the first RSR test, this is my result.....

ProductVersionExtra = "(a)"

**Comment by Macjutsu** [comment]
Also, to be clear at this point betas are not supported either... but this is yet another monkeywrench in the mess that is `softwareupdate`.

**Comment by Macjutsu** [comment]
So while I have a new build with betas working properly now... I'm not sure what to do with the rapid security responses yet.

I though the whole point was they did NOT require a restart... yet here we are with these results in my software update list...

`* Label: macOS Security Response 13.2 (a)-22D7750270d
	Title: macOS Security Response 13.2 (a), Version: 13.2 (a), Size: 117241K, Recommended: YES, Action: restart,`

**Comment by master-vodawagner** [comment]
If you want more eyes on your test code I’m happy to help try it in my dedicated DEV environment

**Comment by master-vodawagner** [comment]
I think RSRs always needed a restart but it doesn’t take as long to install vs a minor patching

**Comment by Macjutsu** [comment]
Good news... latest release supports beta seeds... bad news... there are other things going on in 13.2 that break `super`... but as soon as those are resolved I'll get to work on supporting RSR updates.

https://github.com/Macjutsu/super/releases/tag/v3.0-b6

**Comment by Macjutsu** [comment]
Just an update here... there are still not RSR updates in the wild to actually test... so nothing I can do at this point.

**Comment by croaker-1** [comment]
There is one today: 13.3.1 (a)

**Comment by croaker-1** [comment]
Here is what I am seeing with the RSR 13.3.1 (a) update:
```
Tue May 02 17:37:09 ZMHXXFQM9W super[95840]: Verbose Mode: Function downloadMacOSSoftwareUpdate: softwareUpdateLabelTARGET[] is:
macOS Security Response 13.3.1 (a)-22E772610a
Tue May 02 17:37:09 ZMHXXFQM9W super[95840]: Verbose Mode: Function downloadMacOSSoftwareUpdate: workflowTimeoutSECONDS is: 120
Tue May 02 17:37:14 ZMHXXFQM9W super[95840]: softwareupdate: macOS Security Response 13.3.1 (a) is downloading...
Tue May 02 17:37:14 ZMHXXFQM9W super[95840]: Verbose Mode: Function downloadMacOSSoftwareUpdate: workflowTimeoutSECONDS is: 1200
Tue May 02 17:37:14 ZMHXXFQM9W super[95840]: softwareupdate: macOS Security Response 13.3.1 (a) download and preparation complete.
Tue May 02 17:37:14 ZMHXXFQM9W super[95840]: Verbose Mode: Function downloadMacOSSoftwareUpdate: softwareUpdateTitleTARGET is: macOS Security Response 13.3.1 (a)
Tue May 02 17:37:14 ZMHXXFQM9W super[95840]: Verbose Mode: Function downloadMacOSSoftwareUpdate: ```
softwareUpdateDownloadTITLE is: macOS Security Response 13.3.1 (a)
Tue May 02 17:37:14 ZMHXXFQM9W super[95840]: Verbose Mode: Function downloadMacOSSoftwareUpdate: preparedMacOSVERSION is: 13.3.1
Tue May 02 17:37:14 ZMHXXFQM9W super[95840]: Verbose Mode: Function downloadMacOSSoftwareUpdate: macOSUpgradeVersionTARGET is: FALSE
Tue May 02 17:37:14 ZMHXXFQM9W super[95840]: Verbose Mode: Function downloadMacOSSoftwareUpdate: macOSSoftwareUpdateVERSION is: 13.3.1 (a)
Tue May 02 17:37:14 ZMHXXFQM9W super[95840]: Error: Downloaded macOS update version of 13.3.1 doesn't match expected version 13.3.1 (a), trying again in 900 seconds.
```

It looks like `macOSSoftwareUpdateVERSION` picks up the "(a)" but `preparedMacOSVERSION` does not.
To allow `preparedMacOSVERSION` to capture the extra version information, I replaced: 
`preparedMacOSVERSION=$(defaults read /System/Volumes/Update/Update update-asset-attributes 2> /dev/null | grep -w 'OSVersion' | sed -e 's/    OSVersion = "//' -e 's/";//')`
on lines 4103 & 4325 with
`preparedMacOSVERSION=$(defaults read /System/Volumes/Update/Update update-asset-attributes 2> /dev/null | grep -w 'OSVersion' | sed -e 's/    OSVersion = "//' -e 's/";/ /' | tr -d '\012'; defaults read /System/Volumes/Update/Update update-asset-attributes 2> /dev/null | grep -w 'ProductVersionExtra' | sed -e 's/    ProductVersionExtra = "//' -e 's/";//')`

This allowed the update to download and install.

```
Tue May 02 21:42:32 ZMHXXFQM9W super[33763]: Verbose Mode: Function downloadMacOSSoftwareUpdate: softwareUpdateLabelTARGET[] is:
macOS Security Response 13.3.1 (a)-22E772610a
Tue May 02 21:42:32 ZMHXXFQM9W super[33763]: Verbose Mode: Function downloadMacOSSoftwareUpdate: workflowTimeoutSECONDS is: 120
Tue May 02 21:42:37 ZMHXXFQM9W super[33763]: softwareupdate: macOS Security Response 13.3.1 (a) is downloading...
Tue May 02 21:42:37 ZMHXXFQM9W super[33763]: Verbose Mode: Function downloadMacOSSoftwareUpdate: workflowTimeoutSECONDS is: 1200
Tue May 02 21:42:37 ZMHXXFQM9W super[33763]: softwareupdate: macOS Security Response 13.3.1 (a) download and preparation complete.
Tue May 02 21:42:37 ZMHXXFQM9W super[33763]: Verbose Mode: Function downloadMacOSSoftwareUpdate: softwareUpdateTitleTARGET is: macOS Security Response 13.3.1 (a)
Tue May 02 21:42:37 ZMHXXFQM9W super[33763]: Verbose Mode: Function downloadMacOSSoftwareUpdate: softwareUpdateDownloadTITLE is: macOS Security Response 13.3.1 (a)
Tue May 02 21:42:37 ZMHXXFQM9W super[33763]: Verbose Mode: Function downloadMacOSSoftwareUpdate: preparedMacOSVERSION is: 13.3.1 (a)
Tue May 02 21:42:37 ZMHXXFQM9W super[33763]: Verbose Mode: Function downloadMacOSSoftwareUpdate: macOSUpgradeVersionTARGET is: FALSE
Tue May 02 21:42:37 ZMHXXFQM9W super[33763]: Verbose Mode: Function downloadMacOSSoftwareUpdate: macOSSoftwareUpdateVERSION is: 13.3.1 (a)
Tue May 02 21:42:37 ZMHXXFQM9W super[33763]: Verbose Mode: Function setDisplayLanguage: titleWorkflowDISPLAY is: macOS 13.3.1 (a) Update
Tue May 02 21:42:37 ZMHXXFQM9W super[33763]: IBM Notifier: Ask for restart or defer dialog with a 900 second timeout.
```

**Comment by Macjutsu** [comment]
I'm aware... next release will support RSRs.

**Comment by Macjutsu** [comment]
https://github.com/Macjutsu/super/releases/tag/v3.0-b11
