### ISSUE TITLE
Error code: Unable to reach Apple Software Update server, trying again in xxx seconds.

### ISSUE THREAD

**Issue by ozzyvanbrunschot** [Macjutsu/super#53]
When checking the logs , something is not working prop..

Super starts, it reading the proper prefs, it finds the update, its validating the bootstrap.
It sometimes start to download the actual updater, buts it always stalls on:
Error code: Unable to reach Apple Software Update server, trying again in xxx seconds.

Details:
MacBook Pro 14"  - macOS 13.0.1 (22A400) Same issues with a macbook air 2018 on macos 12.1
Superman v3.0-b4 (attached used config profile)

There are no other software updates deferal profiles or restrictions.

Tested on different geo locations
Tested on different MacBooks
Tested on different macOS versions

Latest super version 2.0 was working great!

Jamf Pro kicks-off the run command for super once a day per computer with the following command:
/Library/Management/super/super --jamf-account=apiuser --jamf-password=securepasswd

<img width="463" alt="Screenshot 2022-12-20 at 20 23 11" src="https://user-images.githubusercontent.com/49714558/208750001-4db32514-e85e-41be-a466-417df8223d84.png">
<img width="653" alt="Screenshot 2022-12-20 at 20 23 18" src="https://user-images.githubusercontent.com/49714558/208750005-fdc7e94c-0e9d-4ed7-84b5-4f6cab6ba91a.png">
<img width="565" alt="Screenshot 2022-12-20 at 20 23 28" src="https://user-images.githubusercontent.com/49714558/208750007-f39c7022-b97a-404b-a596-2e9475eaeaed.png">
<img width="798" alt="Screenshot 2022-12-20 at 20 23 39" src="https://user-images.githubusercontent.com/49714558/208750010-0b91053e-6aef-449d-82a1-fc1141221804.png">
<img width="758" alt="Screenshot 2022-12-20 at 20 23 51" src="https://user-images.githubusercontent.com/49714558/208750011-bc8a98aa-99e3-4e4d-8799-884e06d9cf60.png">
<img width="663" alt="Screenshot 2022-12-20 at 20 24 50" src="https://user-images.githubusercontent.com/49714558/208750015-7779aefe-0ff4-41ca-941f-fdc926aa0d6f.png">
<img width="582" alt="Screenshot 2022-12-20 at 20 25 08" src="https://user-images.githubusercontent.com/49714558/208750017-7e1e5411-d1ca-4b72-85a6-82a00ab5eae7.png">

**Comment by Macjutsu** [comment]
Last screenshot... Files and Processes... don't do that.

Check the Wiki.... https://github.com/Macjutsu/super/wiki/Jamf-Pro-Deployment#jamf-pro-policy

However, I am working on squashing bugs like you've seen in the next beta so I'll leave this open.

**Comment by ozzyvanbrunschot** [comment]
> Last screenshot... Files and Processes... don't do that.
> 
> Check the Wiki.... https://github.com/Macjutsu/super/wiki/Jamf-Pro-Deployment#jamf-pro-policy
> 
> However, I am working on squashing bugs like you've seen in the next beta so I'll leave this open.

Ok, I'll do that

**Comment by ozzyvanbrunschot** [comment]
Just checked, same result
Checking the content of asu.log

Tue Dec 20 21:17:49 MacBook super[67113]: **** S.U.P.E.R.M.A.N. MACOS 13.1 DOWNLOAD ASU START ****
: No such update
No updates are available.
Software Update Tool

Finding available software

Tue Dec 20 21:18:09 MacBook super[67113]: **** S.U.P.E.R.M.A.N. DOWNLOAD ASU FAILED ****

Tue Dec 20 21:18:09 MacBook super[67113]: Error: Unable to reach Apple Software Update server, trying again in 3600 seconds.

I'll wait to the next beta.

**Comment by Macjutsu** [comment]
This should be resolved in the latest build of [`super` v3.0b5](https://github.com/Macjutsu/super/releases/tag/v3.0-b5).
