### ISSUE TITLE
Display the actual update/upgrade components to be updated?

### ISSUE THREAD

**Issue by spikehed** [Macjutsu/super#54]
Would love for the dialogs to display the actual updates that are to be installed for the end user. 
Case would be, if end user inadvertently received an update/upgrade notification to defer, et. al., they would, in the least, know whats to be updated/upgraded. Safari, Security Update, Major OS Upgrade, etc.

**Comment by Macjutsu** [comment]
The good news is the latest release now shows the macOS update/upgrade version in the dialog and notification dialogs... check out [`super` v3.0b5](https://github.com/Macjutsu/super/releases/tag/v3.0-b5).

The bad news is that `jamfHelper` is so limited in it's dialog and notification abilities that I will not be adding any more complexity to dialogs and notifications until [`super` v5](https://github.com/Macjutsu/super/milestones). At that point I will be dropping support for older versions of macOS so new dialogs and notifications can be created based on [SwiftDialog](https://github.com/bartreardon/swiftDialog).
