### ISSUE TITLE
Feature Request : Version readout in Logs

### ISSUE THREAD

**Issue by tranziq** [Macjutsu/super#55]
In the Super.log   in the Status,  it would be really helpful to put a  Status : Super Version x.xbx 

It would be helpful to know the current version of Super that is running.    With all the great beta releases,  its hard to keep track in the logs on what version did what.

**Comment by Macjutsu** [comment]
This will be in the next beta... good idea.

**Comment by dorminyk** [comment]
This may or may not help;
I'm utilizing Jamf and have an Extension Attribute with the following... This helps me determine what version that we're working with on certain machines.

#!/bin/bash
if [[ -d /Library/Management/Super ]]; then
superVer=$( cat /Library/Management/super/super | grep "# Version" | awk '{print $3}' )
echo <result>$superVer</result>
else
echo <result>Not installed</result>"
fi

**Comment by Macjutsu** [comment]
I'll take your feature request... implement it... and raise you with an extra Jamf Pro EA script!

https://github.com/Macjutsu/super/releases/tag/v3.0-b6

https://github.com/Macjutsu/super/blob/main/Super-Friends/super-Installed-Version-Jamf-Pro-EA.sh
