### ISSUE TITLE
Allow External dependencies to be installed via policy instead of downloading over Internet

### ISSUE THREAD

**Issue by tranziq** [Macjutsu/super#56]
In Secure environments,   access to GitHub could be blocked (as it is in my secure space).

The request is to allow Erase-install.pkg, MovablePython3 ,IBM Notify, etc to be installed via policy and pulled from our available Jamf Repositories.

**Comment by Macjutsu** [comment]
This issue implies that `super` doesn't "allow" those items to be installed. To be clear, `super` doesn't care how the dependencies got there, it just checks that they are validly installed in the expected locations.

In other words, there is nothing to prevent you from doing just what you asked. Use a Jamf Policy to install the dependencies before running `super` and then `super` won't have to install the items via GitHub.

Further, if you want to change how `super` locates or validates those items, this can be accomplished by modifying the clearly named variables in the `setDefaults()` function.
