### ISSUE TITLE
FR - Logic Check - Super if executed inside defer window to end script during validation?

### ISSUE THREAD

**Issue by master-vodawagner** [Macjutsu/super#61]
I think this is a niche scenario and only limited to companies where their estate shutdowns Macs / Standby and delete FV2 key etc.

I want a way to trigger super to run at key times of the day (say 0900 1200 1500 1800) to ensure it loads itself after a cold start whilst still respecting any User deferment time period.

The only way I can see this working is whereby super checks on initial execution if an existing deferment window is in place and kills itself

**Comment by master-vodawagner** [comment]
I've potentially come up with a solution, I'm not an expert at bash and this is your software so I'm sure there are better methods, better variable names etc.

Add to LN612	        `SuperPendingPROPERTY=$(defaults read "$superPLIST" SuperPending 2> /dev/null)`
Add to LN613	        `SuperStatusPROPERTY=$(defaults read "$superPLIST" SuperStatus 2> /dev/null)`

Remove LN1863 	`sendToStatus "Running: Startup workflow..."`
Remove LN1864	`sendToPending "Currently running."`

Add to LN1869	
```
# Checking if existing super deferrment window in-place.
sendToLog "Startup: Checking if existing deferrment window in-place"
currentDateTime=$(date "+%Y-%m-%d %H:%M:%S")
SuperPendingDateTime=$SuperPendingPROPERTY
SuperStatusMinusDate=$(echo $SuperStatusPROPERTY | awk -F':' '{ print $5 }')
SuperStatusDeferInSeconds=$(echo $SuperStatusPROPERTY | awk -F',' '{ print $2 }' | grep -Eo "[0-9]+")

sendToLog "Current Date/Time is "$currentDateTime
sendToLog "Super Pending Property is "$SuperPendingDateTime
#sendToLog "Super Status Property is "$SuperStatusPROPERTY
#sendToLog "Super Status without date is "$SuperStatusMinusDate
#sendToLog "Super Status defer in seconds "$SuperStatusDeferInSeconds

if [[ "$SuperStatusMinusDate" == *"User chose to defer, trying again in"* ]] && [[ "$currentDateTime" < "$SuperPendingDateTime" ]]; then
	sendToLog "Startup: Existing deferment window in-place of $SuperStatusDeferInSeconds seconds and is due to expire on $SuperPendingDateTime"
	sendToLog "**** S.U.P.E.R.M.A.N. $superVERSION EXIT ****"
	exit 0
else
	sendToLog "Startup: No deferment window in-place, continuing with super"
	sendToStatus "Running: Startup workflow..."
	sendToPending "Currently running."
fi
```

Remove LN4579 	`<key>LaunchOnlyOnce</key>`
Remove LN4580	`<true/>`

Add LN4589 		`<key>StartInterval</key>`
Add LN4590   	`<integer>1200</integer>`

**Comment by master-vodawagner** [comment]
example super.log when no deferment window

Wed Jan 11 19:26:06 X2206623 Super[7090]: **** S.U.P.E.R.M.A.N. 3.0b6 STARTUP ****
Wed Jan 11 19:26:07 X2206623 Super[7090]: Startup: Checking if existing deferment window in-place
Wed Jan 11 19:26:07 X2206623 Super[7090]: Current Date/Time is 2023-01-11 19:26:07
Wed Jan 11 19:26:07 X2206623 Super[7090]: Super Pending Property is 2023-01-11 11:43:14
Wed Jan 11 19:26:07 X2206623 Super[7090]: Startup: No deferment window in-place, continuing with super
Wed Jan 11 19:26:07 X2206623 Super[7090]: Startup: Removing previous LaunchDaemon com.macjutsu.super.plist.
Wed Jan 11 19:26:07 X2206623 Super[7090]: Startup: Verbose mode enabled.
Wed Jan 11 19:26:07 X2206623 Super[7090]: Startup: Uptime: 19:26  up 26 mins, 1 user, load averages: 3.55 2.92 3.45

example super.log with a deferment window
Wed Jan 11 16:30:26 X2102825 super[70036]: **** S.U.P.E.R.M.A.N. 3.0b6 STARTUP ****
Wed Jan 11 16:30:26 X2102825 super[70036]: Startup: Checking if existing deferment window in-place
Wed Jan 11 16:30:26 X2102825 super[70036]: Current Date/Time is 2023-01-11 16:30:26
Wed Jan 11 16:30:26 X2102825 super[70036]: Super Pending Property is 2023-01-11 16:59:59
Wed Jan 11 16:30:26 X2102825 super[70036]: Startup: Existing deferment window in-place of 1800 seconds and is due to expire on 2023-01-11 16:59:59
Wed Jan 11 16:30:26 X2102825 super[70036]: **** S.U.P.E.R.M.A.N. 3.0b6 EXIT ****

**Comment by Macjutsu** [comment]
So... this feature is ultimately a good idea.

However, I don't think trying to fix it within the current scheduling mechanism is a good idea. Instead I plan to rewrite the scheduling mechanism in v4. In short, `super` v4 will behave similarly to the jamf agent where we have a persistent LD that runs on a regular basis, but only starts the workflow when necessary based on schedule/options/etc.

**Comment by Macjutsu** [comment]
Please try to replicate in https://github.com/Macjutsu/super/releases/tag/v4.0.0-rc1.

If you can't replicate this by the release of v4.0.0 later this week, I'll be closing this issue.

**Comment by Macjutsu** [comment]
https://github.com/Macjutsu/super/releases/tag/v4.0.0
