### ISSUE TITLE
Hard-coded install path /Library/Management.  Consider giving advice in wiki on changing it.

### ISSUE THREAD

**Issue by bradtchapman** [Macjutsu/super#64]
https://github.com/Macjutsu/super/blob/6d1e5be599563b29f6e9134d992373a6b2f7fb49/super#L144

Some customers install their corporate in-house tools in a special directory.  Example: /Library/PretendCo, or /private/etc/pretendco/.  Currently this path is hard-coded in the `super` script to the path: `/Library/Management`.  There's no explicit suggestion to admins in the wiki that they can (or should) change it, and for some admins the prospect of breaking open a 6,000+ line script may be overwhelming, or entirely outside the scope of the implementer (i.e.: 3rd party contractors, MSPs, etc).

Please add a note to the Wiki article about changing this path.  The best place would probably be the "Deployment" section, since it's not intended for most users, but for expert admins who need to customize this for their environments.

Alternatively, consider implementing a custom install path with a new switch `-i|--install-path` in `getOptions` and adjust `setDefaults` accordingly.

**Comment by Macjutsu** [comment]
Updating documentation is a valid short-term goal...

However, an option to change the install path via a command switch is not.

**Comment by Macjutsu** [comment]
In new v3.0 wiki... https://github.com/Macjutsu/super/wiki/Configure-Settings#configure-via-command-line-or-script
