### ISSUE TITLE
The Wiki link to "Test Mode" on the Update Options page is broken.

### ISSUE THREAD

**Issue by bradtchapman** [Macjutsu/super#66]
https://github.com/Macjutsu/super/wiki/Update-Options

`This option is especially useful when used along with --test-mode or if no restart required system updates are available but you still want to force a system restart. Detailed documentation regarding --test-mode can be [found here](https://github.com/Macjutsu/super/wiki/Test_Mode).`

The correct link is: https://github.com/Macjutsu/super/wiki/Test-Mode

**Comment by Macjutsu** [comment]
Good find... thanks... fixed.
