### ISSUE TITLE
Allow admins to disable the alert sound.

### ISSUE THREAD

**Issue by bradtchapman** [Macjutsu/super#67]
Super currently plays the system default alert sound when redrawing the window.  

Please add an option to disable this sound.  In some production environments, such as news rooms and filming soundstages, sounds may be highly disruptive and cause production delays or impact to on-air broadcasts.

**Comment by bradtchapman** [comment]
Even if this is a function of IBM Notifier, and not `super`, many of your parameters for IBM Notifier and jamfHelper in the `super` script are hard-coded, so it's difficult to tell which is responsible.

**Comment by Macjutsu** [comment]
Good suggestion... though it would appear that only IBM Notifier can be silenced.

**Comment by Macjutsu** [comment]
This feature has been implemented in the latest beta: https://github.com/Macjutsu/super/releases/tag/v3.0-b8
