### ISSUE TITLE
macOS 13.2 Upgrade Failed

### ISSUE THREAD

**Issue by LeoNz95** [Macjutsu/super#68]
Minor update from 12.2 to 12.6 worked.
Failing to install major update (13.2):
![image](https://user-images.githubusercontent.com/123066223/216052597-8fc71afa-0c48-4997-b694-b45c525d579e.png)
Attaching logs as well:
[super.log](https://github.com/Macjutsu/super/files/10557348/super.log)
[mdmWorkflow.log](https://github.com/Macjutsu/super/files/10557350/mdmWorkflow.log)

**Comment by Macjutsu** [comment]
Try increasing the following two variables to 900 seconds...

mdmTimeoutSECONDS=900
mdmWorkflowTimeoutSECONDS=600

**Comment by LeoNz95** [comment]
> mdmTimeoutSECONDS

Thanks for your fast reply.
I don't see these variables in the SUPER plist file.
Where exactly do I need to edit them?

**Comment by Macjutsu** [comment]
I don't plan to ever put timeouts in the plist.... the plist is already too complicated.

Just look for those two strings in the `super` script and change them.

**Comment by LeoNz95** [comment]
Unfortunately, it's still not working.
Attaching new logs.

[super.log](https://github.com/Macjutsu/super/files/10675580/super.log)
[mdmWorkflow.log](https://github.com/Macjutsu/super/files/10675581/mdmWorkflow.log)

**Comment by Macjutsu** [comment]
So... looks like your computer is exceptionally slow to progress...

Try increasing the mdmWorkflowTimeoutSECONDS=3600.

Again, to be clear, `super` is just waiting on the system to update. In your last example it got to about 29% and then didn't report any progress for... well 15 minutes... so `super` makes the assumption that the upgrade has hung. In other words, we are literally waiting on the system to do it's thing... I've never seen it take this long... but I also test on fairly lean systems.

If your systems continue to hang after an hour... there isn't anything `super` can do about that... you have a system issue.

**Comment by LeoNz95** [comment]
It worked!
Thanks a lot for all your help 😁
