### ISSUE TITLE
Option --display-icon \"/local/path or URL\"

### ISSUE THREAD

**Issue by nonos456** [Macjutsu/super#7]
Hello, thank you for your script!
I would like to change the icon with the --display-icon \"/local/path or URL\" option but I can't get the desired result. In the log file, I have each time "Unable to locate specified icon from". For the tests I have the image on my desktop, I entered -display-icon " /User/Myname/Desktop/Logo.png. 
Do I need the format of the icns image? 
Did I enter it correctly?

**Comment by Macjutsu** [comment]
Assuming your text example is verbatim you have at least three entry errors; there should be two dashes in front of display-icon, there is an extra space after the first quote, and there is no ending quote.

**Comment by nonos456** [comment]
Thank you very much! I corrected it and it works
