### ISSUE TITLE
Unable to install Safari Updates

### ISSUE THREAD

**Issue by DarthMJH** [Macjutsu/super#70]
We are running Super 3.0b6 and are having issues with Safari updates on Monterey.   This is especially perternant now as Apple have just released an update to Safari yesterday 13/2/23.  But we saw this with the previous Safari update.

If we have safari open and we run super, we are prompted to close safari.  When we close safari, it fails to update. with the : Error: "Download of software udpates failed to start after 120 seconds, trying again in 14400 seconds."

In the Super log we see

Tue Feb 14 09:17:09 Hostname super[10227]: **** S.U.P.E.R.M.A.N. 3.0b6 DOWNLOAD RECOMMENDED SOFTWAREUPDATE ****
Tue Feb 14 09:17:09 Hostname super[10227]: softwareupdate: Starting download of all available updates, check /Library/Management/super/asu.log for more detail.
Tue Feb 14 09:17:31 Hostname super[10227]: softwareupdate: Safari download and preparation complete.
Tue Feb 14 09:17:31 Hostname super[10227]: Error: Download of software udpates failed to start after 120 seconds, trying again in 14400 seconds.
Tue Feb 14 09:17:31 Hostname super[10227]: Status: Restarting various softwareupdate daemon processes...
Tue Feb 14 09:17:31 Hostname super[10227]: Status: Removing previous LaunchDaemon com.macjutsu.super.plist.
Tue Feb 14 09:17:31 Hostname super[10227]: Exit: LaunchDaemon com.macjutsu.super.plist is scheduled to start at 13:17 on 02/14.

In the asu.log we see:

Tue Feb 14 09:17:09 Hostname super[10227]: **** S.U.P.E.R.M.A.N. 3.0b6 DOWNLOAD ALL SOFTWAREUPDATE START ****
Software Update Tool
Finding available software
Attempting to quit apps: (
    "com.apple.Safari.SafariQuickLookPreview",
    "com.apple.Safari"
)
Waiting for user to quit any relevant apps
Successfully quit all apps
Downloaded Safari
Done.
Tue Feb 14 09:17:31 Hostname super[10227]: **** TIMESTAMP ****
Tue Feb 14 09:17:31 Hostname super[10227]: **** S.U.P.E.R.M.A.N. 3.0b6 DOWNLOAD SOFTWAREUPDATE FAILED ****
Tue Feb 14 09:17:31 Hostname super[10227]: Error: Download of software udpates failed to start after 120 seconds, trying again in 14400 seconds.

In the asu.log it says 'Downloaded Safari' and 'Done' but Super shows failed to download.

If I run the update via System Preferences the prompt to close Safari appears, I then close the app and the download then starts and once complete installs successfully.  Not sure why super does not?  Maybe after close it does not have aenough time to download ?

We had this issue when Monterey and Safari was released.  Monterey update was fine but Safari did not update.

and one minor thinf updates is spelt wrong
Download of software _udpates_ failed to start after 120 seconds, trying again in 14400 seconds.

Have you seen this behaviour ?

Many thanks

**Comment by Macjutsu** [comment]
I'm aware... will be resolved in the next beta.

**Comment by Macjutsu** [comment]
Resolved in latest beta: https://github.com/Macjutsu/super/releases/tag/v3.0-b7

**Comment by DarthMJH** [comment]
Thank you.  I will see if we can find a host to test this on.  We rolled out safari as a package to get it installed.

Any issues with b7 I'll let you know.

Again only minor typo's you might want to do a search and replace.
![Super_Typo](https://user-images.githubusercontent.com/122112672/219457419-e24ff136-e42a-4c55-8c47-48364531caed.jpg)

Also on your release notes the SHA version is incorrect should say 7 rather than 6

![SuperB6Typo](https://user-images.githubusercontent.com/122112672/219457704-5a5f576a-9479-42e0-bd7b-a1dcae5d2786.jpg)

**Comment by Macjutsu** [comment]
Haha... thanks.

I do a spell check pass during the RCs... so this would have been caught then... but I'll go ahead and fix it for the next beta release... also the notes.
