### ISSUE TITLE
checkMacOSUpgrades is not sorting correctly

### ISSUE THREAD

**Issue by marcelpogorzelski** [Macjutsu/super#71]
https://github.com/Macjutsu/super/blob/6d1e5be599563b29f6e9134d992373a6b2f7fb49/super#L2966

This is sorting the version number incorrectly.

Here are some interesting verbose log lines
Before erase-install:
`Thu Feb 16 10:28:16 uit-mac-773 super[12182]: Verbose Mode: Function listMacOSUpgrades: macOSUPGRADE is: macOS Ventura:13.2.1
Thu Feb 16 10:28:16 uit-mac-773 super[12182]: Verbose Mode: Function listMacOSUpgrades: macOSUpgradeNAME is: macOS Ventura
Thu Feb 16 10:28:16 uit-mac-773 super[12182]: Verbose Mode: Function listMacOSUpgrades: macOSUpgradeVERSION is: 13.2.1
Thu Feb 16 10:28:16 uit-mac-773 super[12182]: Verbose Mode: Function listMacOSUpgrades: macOSUpgradeMajorVERSION is: 13
Thu Feb 16 10:28:16 uit-mac-773 super[12182]: Verbose Mode: Function listMacOSUpgrades: macOSUpgradeAVAILABLE is: TRUE
Thu Feb 16 10:28:16 uit-mac-773 super[12182]: erase-install.sh: Waiting for macOS installer list...
Thu Feb 16 10:28:28 uit-mac-773 super[12182]: Verbose Mode: Function checkMacOSUpgrades: macOSSoftwareUpdateVERSIONS[] is:
13.2.1
12.6.3
Thu Feb 16 10:28:28 uit-mac-773 super[12182]: Verbose Mode: Function checkMacOSUpgrades: macOSSoftwareUpgradeLABEL is: macOS Ventura 13.2.1-22D68
Thu Feb 16 10:28:28 uit-mac-773 super[12182]: Verbose Mode: Function checkMacOSUpgrades: macOSSoftwareUpgradeTITLE is: macOS Ventura 13.2.1
Thu Feb 16 10:28:28 uit-mac-773 super[12182]: Verbose Mode: Function checkMacOSUpgrades: macOSSoftwareUpgradeVERSION is: 13.2.1
Thu Feb 16 10:28:28 uit-mac-773 super[12182]: Verbose Mode: Function checkMacOSUpgrades: macOSUpgradeAVAILABLE is: TRUE
Thu Feb 16 10:28:28 uit-mac-773 super[12182]: Verbose Mode: Function checkMacOSUpgrades: macOSInstallerLIST is:`

and after erase-install:
`Thu Feb 16 10:28:28 uit-mac-773 super[12182]: Verbose Mode: Function checkMacOSUpgrades: macOSInstallersARRAY is:
27:032-35706:13.2:22D49:2023-01-23:macOS Ventura:
30:032-48342:13.2.1:22D68:2023-02-13:macOS Ventura:
24:012-60271:13.1:22C65:2023-01-11:macOS Ventura:
23:012-93766:13.0.1:22A400:2022-11-09:macOS Ventura:
29:032-33828:12.6.3:21G419:2023-01-31:macOS Monterey:
25:032-12843:12.6.2:21G320:2023-01-11:macOS Monterey:
21:012-90254:12.6.1:21G217:2022-10-24:macOS Monterey:
Thu Feb 16 10:28:28 uit-mac-773 super[12182]: Verbose Mode: Function checkMacOSUpgrades: macOSInstallerNAMES is:
macOS Ventura
macOS Ventura
macOS Ventura
macOS Ventura
macOS Monterey
macOS Monterey
macOS Monterey
Thu Feb 16 10:28:28 uit-mac-773 super[12182]: Verbose Mode: Function checkMacOSUpgrades: macOSInstallerVERSIONS is:
13.2
13.2.1
13.1
13.0.1
12.6.3
12.6.2
12.6.1
Thu Feb 16 10:28:28 uit-mac-773 super[12182]: Verbose Mode: Function checkMacOSUpgrades: macOSInstallerBUILDS is:
22D49
22D68
22C65
22A400
21G419
21G320
21G217
Thu Feb 16 10:28:28 uit-mac-773 super[12182]: Status: macOS upgrade available via installer: macOS Ventura 13.2-22D49`

**Comment by marcelpogorzelski** [comment]
`macOSInstallersARRAY=($(sort -t: -k3 -r -g <<<"${macOSInstallerCompatibleLIST[*]}")) `

this solved it in my case.
-g, --general-numeric-sort, --sort=general-numeric
instead of version sort.

**Comment by Macjutsu** [comment]
Thanks... I found this one earlier in the week and have changed to sorting via the Build number instead. Not sure why 13.2.1 breaks the `sort -v` function... but here we are. New build out soon.... got to test test test first.

**Comment by Macjutsu** [comment]
Resolved in latest beta: https://github.com/Macjutsu/super/releases/tag/v3.0-b7
