### ISSUE TITLE
mdmWorkflowTYPE == "INSTALLER" timeout logic fail?

### ISSUE THREAD

**Issue by marcelpogorzelski** [Macjutsu/super#73]
https://github.com/Macjutsu/super/blob/7b699e33baa5a28c456571d749c739f50d8b18aa/super#L4209

The notifications in this else block don't check things timeouts. I get the restartnotify after the following timeouts:
https://github.com/Macjutsu/super/blob/7b699e33baa5a28c456571d749c739f50d8b18aa/super#L4239

**Comment by Macjutsu** [comment]
Thanks for finding this! This will be fixed in the next beta... very soon.

**Comment by Macjutsu** [comment]
This issue is resolved in the latest beta: https://github.com/Macjutsu/super/releases/tag/v3.0-b8
