### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by DarthMJH** [Macjutsu/super#74]
Hi,
Thanks for the updates in 3.0b8.  Testing is going well so far. The Safari update is now coming down.

When the 12.6.3 update and the Safari 16.3 update are available Super downloads both updates successfully, it reboots and the 12.6.3 update gets installed, but the Safari update is still available, we have to run Super again for that to install and it installs fine.

I suspect it's because we use JAMF to kick off super.  Super kicks off downloads the O/S and Safari update, reboots installs the 12.6.3 update.  Then Super is actice as 'Recheck deferral is inactive.'  We then have to kick off super via JAMF to install the Safari update.

Is it possible to code in when 2 updates are available after one is installed super runs again after a reboot ?

Maybe using this --enforce-all-updates will resolve it, but to be honest I still don't understand this option, as Super installs all updates anyway?

The other possible enhancement is when we see messages like this:
Pending: Unable to validate Jamf Pro user account, trying again in 14400 seconds.
Pending: Download of software updates failed to start after 120 seconds, trying again in 14400 seconds.
Pending: Installation of macOS update/upgrade timed out after 300 seconds, trying again in 14400 seconds.

We have set our $defaultDeferSECONDS to 14400, but when there is an error\problem we would like Super to try again quicker than 4 hours.

Could there be a different variable for $defaultErrorSECONDS as we want Super to keep trying if it fails.  For example we have seen a download get to 58% then fail.  If left it wouldn't try again for another 4 hours, we would like it to try again is say 5 minutes or a time of choice.

**Comment by DarthMJH** [comment]
Thanks for the prompt response.   I should be able to get the log file next week.

Sorry for the --enforce-all-updates silly question, I did read the changelog, but I am not 100% sure what a recommended update is.  I didn't know if that was a Safari update.

**Comment by Macjutsu** [comment]
"Recommended" is the terminology Apple uses to describe all non-macOS updates in `softwareupdate`.

**Comment by DarthMJH** [comment]
Thanks for the clarirfication.
Apologies for the delay.  Here are the files as requested
[asu.log](https://github.com/Macjutsu/super/files/10868140/asu.log)
[super (1).log](https://github.com/Macjutsu/super/files/10868141/super.1.log)
