### ISSUE TITLE
Missing $ character in script - Line 5066

### ISSUE THREAD

**Issue by homert83** [Macjutsu/super#75]
Hi,
I wanted the default defer time to be 1 day, so set --default-defer=seconds to 86400.
When the IBM Notifier message appears the button said deferForButtonDISPLAY 1 day.
I looked into the script and at line 5066 it has
`deferButtonDISPLAY="deferForButtonDISPLAY 1 $dialogAskForUpdateDayDISPLAY"`
I believe this is missing a $ and should be
`deferButtonDISPLAY="$deferForButtonDISPLAY 1 $dialogAskForUpdateDayDISPLAY"`
When I added the dollar sign in the button appeared as expected in the IBM Notifier.

Your script has been great for me to roll out minor updates without doing major updates until I am ready.
The behind the scenes prep work is fantastic so when a user clicks restart it pretty much gets on with it and doesn't sit there looking like nothing is happening.

**Comment by Macjutsu** [comment]
Thanks, someone in the #super MacAdmins Slack already found this one and it will be fixed in the next beta.

**Comment by Macjutsu** [comment]
Fixed in `super` v3.0b9.
