### ISSUE TITLE
 IBM Notifier option display-accessory-type=TEXTBOX not working properly

### ISSUE THREAD

**Issue by TuJaxit** [Macjutsu/super#78]
Hi,

Is it possible, that the option display-accessory-type=TEXTBOX for IBM Notifier is not working properly? 
I want to display a short text in the notification but no text appears. If I use the type HTML (like in the All-Options-Sample) it is working as expected.

From the config:

```
<key>DisplayAccessoryType</key>
<string>TEXTBOX</string>
<key>DisplayAccessoryContent</key>
<string>"Test accessory view"</string>
```

Thanks and regards

**Comment by Macjutsu** [comment]
Nope. Per instructions in the release notes...

The --display-accessory-content=/local/path or URL option `can accept a local path or a web URL`. If the specified local path or URL can not be found then the custom display accessory will not be shown.
