### ISSUE TITLE
Super does not recognize Jamf as the parent process when super is called via command line from another script

### ISSUE THREAD

**Issue by iDrewbs** [Macjutsu/super#81]
When super is being run via command line within a script that a Jamf policy executes, super does not recognize Jamf as the parent process and properly release the jamf policy, causing some policies to run for an extended period of time if a notification is displayed and the user doesn't close it.
When I ran the line of code current used to detect jamf as the parent process from a script being executed by a jamf policy, the code shows the parent process as "sh".

This issue might be rare, but an example where I ran into it is where I'm using a script to pull the LAPS password for the local admin account to use for the local auth workflow in super. 

I was able to accommodate for this by changing this line of code:
`if [[ $1 == "/" ]] || [[ $(ps -p "$PPID" | awk '{print $4;}' | grep -c 'jamf') -gt 0 ]]; then`

to this:
`if [[ $1 == "/" ]] || [[ $(ps -p "$PPID" | awk '{print $4;}' | grep -c -i 'jamf') -gt 0 ]] || [[ $(ps -p "$PPID" | awk '{print $6;}' | grep -c -i 'jamf') -gt 0 ]]; then`

I had to add another AWK search for the 6th position, but I've noticed some cases where "JAMF" will be all caps or all lowercase, so I also needed to add a "-i" to make the grep case insensitive

**Comment by Macjutsu** [comment]
Thanks for this discovery... I'll resolve in next build.

**Comment by Macjutsu** [comment]
Please try latest release: https://github.com/Macjutsu/super/releases/tag/v3.0-b11
