### ISSUE TITLE
Wrong value in validation of softDisplayTimeoutOPTION

### ISSUE THREAD

**Issue by gzilla13** [Macjutsu/super#84]
There is a mistake in the # Validate $softDisplayTimeoutOPTION and if valid set $softDisplayTimeoutSECONDS.

 Validate $softDisplayTimeoutOPTION and if valid set $softDisplayTimeoutSECONDS.
if [[ "$softDisplayTimeoutOPTION" == "X" ]]; then
	sendToLog "Startup: Deleting local preference for soft deadline display timeout."
	defaults delete "$superPLIST" DeferDisplayTimeout 2> /dev/null
elif [[ -n $softDisplayTimeoutOPTION ]] && [[ $softDisplayTimeoutOPTION =~ $regexNUMBER ]]; then
	if [[ $softDisplayTimeoutOPTION -lt 60 ]]; then
		sendToLog "Warning: Specified soft deadline display timeout of $softDisplayTimeoutOPTION seconds is too low, rounding up to 60 seconds."
		softDisplayTimeoutSECONDS=60
	elif [[ $softDisplayTimeoutOPTION -gt 86400 ]]; then
		sendToLog "Warning: Specified soft deadline display timeout of $softDisplayTimeoutOPTION seconds is too high, rounding down to 86400 seconds (1 day)."
		softDisplayTimeoutSECONDS=86400
	else
		softDisplayTimeoutSECONDS=$softDisplayTimeoutOPTION
	fi
	defaults write "$superPLIST" DeferDisplayTimeout -string "$softDisplayTimeoutSECONDS"
elif [[ -n $softDisplayTimeoutOPTION ]] && ! [[ $softDisplayTimeoutOPTION =~ $regexNUMBER ]]; then
	sendToLog "Parameter Error: The soft deadline display timeout must only be a number."; parameterERROR="TRUE"
fi
if [[ "$parameterERROR" != "TRUE" ]] && [[ -n $softDisplayTimeoutSECONDS ]] && [[ -n $displayRedrawSECONDS ]]; then
	displayMinimumTIMEOUT=$((displayRedrawSECONDS * 3))
	if [[ $softDisplayTimeoutSECONDS -lt $displayMinimumTIMEOUT ]];then
		sendToLog "Warning: Specified soft deadline display timeout of $softDisplayTimeoutSECONDS seconds is too low given a display redraw of $displayRedrawSECONDS seconds, changing soft deadline display timeout to $displayMinimumTIMEOUT seconds."
		softDisplayTimeoutSECONDS=$displayMinimumTIMEOUT
		defaults write "$superPLIST" DeferDisplayTimeout -string "$softDisplayTimeoutSECONDS"
	fi
fi

defaults write "$superPLIST" DeferDisplayTimeout -string "$softDisplayTimeoutSECONDS" should be 
defaults write "$superPLIST" SoftDisplayTimeout -string "$softDisplayTimeoutSECONDS"

also

defaults delete "$superPLIST" DeferDisplayTimeout 2> /dev/null should be 
defaults delete "$superPLIST" SoftDisplayTimeout 2> /dev/null

**Comment by Macjutsu** [comment]
Thanks! Fixed in the next release.

**Comment by Macjutsu** [comment]
Please try latest release: https://github.com/Macjutsu/super/releases/tag/v3.0-b11
