### ISSUE TITLE
Getting a Software Update CMD Failed Message

### ISSUE THREAD

**Issue by taymoorkhan** [Macjutsu/super#85]
Hey I'm using Jamf to deploy Superman and am getting an error message of -

"software update command failed with an error the operation could not be completed subprocess.subprocesserror 0.1 macjutsu superman"

I've added a config profile containing my $JSSID and pushed the super script using a policy.

When the script is pushed the error occurs. Any ideas?

**Comment by Macjutsu** [comment]
You'll need to provide more detail. Specifically the logs found in /Library/Management/super.

**Comment by taymoorkhan** [comment]
Mon May 08 14:05:51 AB-FVFHL038Q05P Super Test[71864]: Verbose Mode: Function logParameters: userAuthMDMFailoverOPTION is: HARD,INSTALLNOW,BOOTSTRAP
Mon May 08 14:05:51 AB-FVFHL038Q05P Super Test[71864]: Verbose Mode: Function logParameters: userAuthMDMFAILOVER is: FALSE
Mon May 08 14:05:51 AB-FVFHL038Q05P Super Test[71864]: Verbose Mode: Function logParameters: userAuthMDMFailoverHARD is: TRUE
Mon May 08 14:05:51 AB-FVFHL038Q05P Super Test[71864]: Verbose Mode: Function logParameters: userAuthMDMFailoverINSTALLNOW is: TRUE
Mon May 08 14:05:51 AB-FVFHL038Q05P Super Test[71864]: Verbose Mode: Function logParameters: userAuthMDMFailoverBOOTSTRAP is: TRUE
Mon May 08 14:05:51 AB-FVFHL038Q05P Super Test[71864]: Exit: Startup validation failed.
