### ISSUE TITLE
Drive space calculation error while executing no user logged in updating

### ISSUE THREAD

**Issue by gzilla13** [Macjutsu/super#87]
We are seeing an error with how the drive space is being calculated when a machine has no user logged in on some machines. The super log shows.
Mon Apr 24 09:32:20: Inactive Error: Current available storage is at 0 GBs which is below the 17 GBs that is required for download. No active user is logged in so trying again in 3600 seconds

These machine do have the space needed to update.

**Comment by Macjutsu** [comment]
I'm aware... will be fixed in next build.

**Comment by Macjutsu** [comment]
Please try latest release: https://github.com/Macjutsu/super/releases/tag/v3.0-b11
