### ISSUE TITLE
Improper calculation of macOS update sizes in non-USA regions

### ISSUE THREAD

**Issue by davidjimenezm** [Macjutsu/super#88]
Hi! Sorry, but I think the problem is still there. Add a sed command for remove "," before dividing it doesnt work because in non-USA regions we use the character "," for float numbers, like you use "." The command "awk '{print $1/1000000}'" still produces float numbers, so "awk -F '.' '{print $1+1}'" converts, for example, 10,324 Gb into 10325 Gb.

The most elegant solution I found is using bc command instead awk for operations, like this:

macOSSoftwareUpdateGB=$(echo "$softwareUpdateLIST" | grep 'Title: macOS' | awk -F ': ' '{print $4}' | grep -o -E '[0-9]+' | **awk '{print $1"/1000000 +1"}' | bc**)

It's working for me and I think it still work for USA nomenclature.

**Comment by davidjimenezm** [comment]
Well, if you divide with `bc`, for default the result is always an integer. So, if you have and update which size is, for example, 12532453KiB, and you want to round it up to GB, it would be:

```
> echo "12532453KiB, Recommended" | grep -o -E '[0-9]+'
12532453

> echo "12532453KiB, Recommended" | grep -o -E '[0-9]+' | awk '{print $1"/1024000 +1"}'
12532453/1024000 +1
```
and finally
```
> echo "12532453KiB, Recommended" | grep -o -E '[0-9]+' | awk '{print $1"/1024000 +1"}' | bc
13
```

**Comment by Macjutsu** [comment]
Wow... thanks for the solution... this will be in the next build!

**Comment by Macjutsu** [comment]
Thanks again!

https://github.com/Macjutsu/super/releases/tag/v3.0-RC1
