### ISSUE TITLE
Suggestion for updating super automatically

### ISSUE THREAD

**Issue by jelockwood** [Macjutsu/super#91]
I have previously used Nudge to 'nag' users to update but Super looks like it might be more effective and currently my own feeling and comments from other users is that MDM frameworks and scripts are currently inadequate.

So I am interested in trying Super but I see an issue I would like to discuss and how it might be solved. Super seems to be purely a script with config and control information via a profile. Installation is by running the script. (After manually downloading it.)

This is a fairly simple process but as is, seems to mean that if an admin downloads the script, adds it to e.g. Jamf and pushes the script out nothing will handle updating the script as and when the developer makes changes. If it was an installer package in the project releases page then it would be possible to monitor for a new version and add the newer pkg and then use the newer installer pkg containing the newer script.

I think it should be possible to do something like the following -
```
curl script-from-github 
save to /private/var/tmp/super.sh
run /private/var/tmp/super.sh
```
The issue is knowing the right URL to curl and using a URL that will always get the latest version. This is initially beyond my GitHub knowledge. A likely easier option would be to use git to get the latest one but this would require installing git on all Macs which is not desirable.

So, does @Macjutsu have any suggestions on how best to 'solve' this?

Note: With Nudge being an executable with an installer pkg I merely set things up to find and download the latest release pkg and deploy this.

**Comment by Macjutsu** [comment]
First GitHub URLs are fairly uniform... here is the direct download for the "main" build of `super`: https://raw.githubusercontent.com/Macjutsu/super/main/super

Second, I would not recommend any automated method for upgrading `super` from the source because I often make significant changes between versions that break compatibility with previous settings.

Even though I created and use `super` every day... I still treat it like any powerful tool... if used improperly it can do some damage... so I would never just blindly deploy the latest version every time without evaluating/testing the changes first.

**Comment by Macjutsu** [comment]
An example for a specific branch of `super` would be a safer approach... for example: https://raw.githubusercontent.com/Macjutsu/super/3.0b12/super

**Comment by jelockwood** [comment]
@Macjutsu 
I hear your comment about auto updating, when I am doing this with installers using AutoPkg and Munki I can add them initially to a test branch so it only gets deployed to testers and then I add it to the production branch after testing.

AutoPkg can download newer releases from Github but in this case it would be seeing the entire Zip file not the shell script.

For what it is worth I have now found the following curl command works and a small modification would do it for a specific release as per your second answer.

```curl --silent -o /private/tmp/super.sh -L -O https://github.com/Macjutsu/super/raw/main/super```

As you may already be aware there are some example articles on how to use curl, sed and/or grep to find the latest release number and then use that to build a URL to download that latest release number

If you did include the shell script file as an individual file in each Github release then I could build an AutoPkg recipe to download it, add it to Munki as a test update and Munki would know the version number from the release tag info.

**Comment by Macjutsu** [comment]
First, `super` actually contains two functions that download content from GitHub. Specifically the `getIbmNotifier()` and the `getEraseInstall()` functions both download/install items from GitHub. You can look to those as examples.

Second, you don't need a separate file in the release as you can just look at the URLs provided earlier. I keep "main" as the latest and then specific older versions via the "branch" example.
