### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by jelockwood** [Macjutsu/super#92]
@Macjutsu 
In the form of paying back 😃 and a request.

I can see you support using a mobileconfig/profile and give an example and discuss using this with Jamf. However as I am sure you are aware it is possible to define a manifest in JSON format which can be uploaded to Jamf which allows Jamf to then display a friendly form view of available settings for apps and in this case it would of course be Super.

I have therefore done an initial version of such a manifest although I could not find enough information in your Wiki to be sure I have done as much as could be possible. This is the first time I have created such a manifest although I have used several before.

What may therefore help and here is my request is to add to your Wiki definitions of all possible preferences.

Here it is, have a play with it and see if you can suggest improvements. Feel free to make it available as part of your offering.

[com.macjutsu.super.json](https://github.com/Macjutsu/super/files/11509543/com.macjutsu.super.json.txt)

You will need to remove the .txt file extension so it is a .json file extension

**Comment by Macjutsu** [comment]
The Wiki has been updated for v3.0... with full details... please lemme know if anything is missing.
