### ISSUE TITLE
Running Super in testmode more than once not working

### ISSUE THREAD

**Issue by jelockwood** [Macjutsu/super#93]
I was able to run Super once in test mode on a Mac and get it to display the dialogs and deferral messages and automatically progress through the stages _as the test mode is intended for!_

What I can't get it to do is to on a second or subsequent run do the same. On subsequent runs it goes straight to the final stage of saying "Required Apple software updates are now installing."

As a result I cannot do multiple tests to check changes I am making to settings.

I have tried re-running the super install script, I have tried running the already installed script with the commands to reset all settings and then reinstall Super. I have also tried rebooting the Mac.

How do I 'flush' Super so I can run the full test cycle again without erasing the entire Mac or finding yet another test Mac.

Note: The Mac has NOT been updated because Super is in test mode so I can confirm an update is still available.

**Comment by jelockwood** [comment]
As part of trying to clear any stored settings I had deleted the contents of /Library/Management/super fortunately I had not emptied the bin.

I was able to find the recorded preferences when it worked and I have restored EXACTLY those settings and it is now showing the dialogs as before. I will try now adjusting a single setting at a time to see where I went wrong.

Thanks for your help, that log file was helpful.

**Comment by jelockwood** [comment]
Ah ha!

@Macjutsu It looks like adding EnforceNonSystemUpdates = 1 (true) is the culprit.

Yep, just turned it off and re-run and it works, tried it again and it fails.

Any ideas? I was hoping to enforce Safari, Xcode, etc. updates as well,

**Comment by Macjutsu** [comment]
Those items are only updated by `super` after the macOS update restart. This is due to a bug in `softwareupdate` that renders the macOS update process unreliable if you attempt to install non-macOS updates first.
