### ISSUE TITLE
Question - automating upgrades vs updates

### ISSUE THREAD

**Issue by jelockwood** [Macjutsu/super#95]
I have now successfully got Super to provide its dialogs and options for deploying updates. It therefore showed the availability with the desired data and defer counts and as I was using the Soft options, defer and restart buttons. When I used Restart it did download, restart and install without the logged in user having to enter a password - as desired.
<img width="709" alt="Screenshot 2023-05-26 at 10 55 38" src="https://github.com/Macjutsu/super/assets/4300786/41fd7a5e-6dbb-470c-9de0-e14dec5068f0">
Arguably the above dialog is incorrectly showing the message as an upgrade when it was merely an update to 11.7.7.

Note: I am using computers linked to Jamf Pro 10.46.1.

I have now turned on the AllowUpgrade option so that instead of just in this case offering a Big Sur update, it now flags a fullblown upgrade to Ventura.
<img width="709" alt="Screenshot 2023-05-26 at 14 23 36" src="https://github.com/Macjutsu/super/assets/4300786/5f539f75-5486-477f-be97-95dcd45c556d">
Here as you can see unlike when I did the update it is asking for a user password even though it is the same computer and still linked to Jamf Pro.

I could not find any mention in your wiki, will upgrades always require a user to type the password in? If not any ideas why this is happening?

Here are the logs.
[asu.log](https://github.com/Macjutsu/super/files/11575992/asu.log)
[asuList.log](https://github.com/Macjutsu/super/files/11575994/asuList.log)
[installer.log](https://github.com/Macjutsu/super/files/11575995/installer.log)
[installerList.log](https://github.com/Macjutsu/super/files/11575996/installerList.log)
[mdmCommand.log](https://github.com/Macjutsu/super/files/11575997/mdmCommand.log)
[mdmCommandDebug.log](https://github.com/Macjutsu/super/files/11575998/mdmCommandDebug.log)
[mdmWorkflow.log](https://github.com/Macjutsu/super/files/11575999/mdmWorkflow.log)
[mdmWorkflowDebug.log](https://github.com/Macjutsu/super/files/11576000/mdmWorkflowDebug.log)
[super.log](https://github.com/Macjutsu/super/files/11576001/super.log)

**Comment by Macjutsu** [comment]
For the first dialog, according to the super.log... you were in test mode.

`Fri May 26 10:55:24 ladmins-MacBook-Air super[33119]: Test Mode: Simulating macOS 11 upgrade workflow.`

Test mode simulates dialogs, not full workflow logic... thus it was showing you what the upgrade dialogs would look like but the version number was obviously inaccurate. This is the intended outcome because otherwise `super` would actually have to check for updates/upgrades which would be actively doing something outside of just testing dialogs.

For the second dialog, according to the super.log... it looks like you specified the option to delete the Jamf API credentials per these log entires:

`Fri May 26 14:08:19 ladmins-MacBook-Air super[15231]: Startup: Deleting saved credentials for Jamf Pro API account "superapi".
Fri May 26 14:08:20 ladmins-MacBook-Air super[15231]: Startup: Apple Silicon Mac computer running macOS 11.7.7-20G1345.
Fri May 26 14:08:20 ladmins-MacBook-Air super[15231]: Startup: Last macOS startup was Fri May 26 12:48.
Fri May 26 14:08:20 ladmins-MacBook-Air super[15231]: Warning: Automatic macOS update/upgrade enforcement on Apple Silicon computers requires authentication credentials.
Fri May 26 14:08:20 ladmins-MacBook-Air super[15231]: Startup: User authentication will be required to perform a macOS update/upgrade.
`

**Comment by jelockwood** [comment]
@Macjutsu 
Thank you for your help. The update process is working fully but as mentioned the upgrade process is not. I did not believe I had set anything to delete the Jamf credentials however as I am still working my way through this I could have made a mistake. I did try this on two different computers with the same results.

What setting would be responsible for this, and what should it be set to to avoid this?

**Comment by Macjutsu** [comment]
You have specified the `--delete-accounts` option.

`Fri May 26 14:08:20 ladmins-MacBook-Air super[15231]: Verbose Mode: Function logParameters: deleteACCOUNTS is: TRUE`

https://github.com/Macjutsu/super/wiki/Jamf-Pro-API-Credentials#delete-all-update-credentials

**Comment by jelockwood** [comment]
@Macjutsu 
Thank you for your continued assistance.

I had included the --delete-accounts when resetting/stopping/removing a version and then getting Jamf to reinstall during testing so you are right on that front.

Note: This seems to work best I later discovered if combined with temporarily excluding the MDM profile from the Mac and then re-adding the profile and then reinstalling.

However having since got progress and achieved successful _updates_ via Super and now trying to do upgrades I do not believe this is now the problem. I am attaching a fresh copy of the super.log

This time, it did an 11.7.7 updates successfully, then downloaded the Ventura upgrade but failed to install the upgrade although the dialog worked as it should with the correct defer and restart options and NO password request.

I can say that when I looked in the /Applications folder during this the icon for the Ventura installer was marked with a no-entry symbol consistent with it not being valid for this Mac model, e.g. if the wrong version or for a different processor type. For what it's worth the Mac is an M1 MacBook Pro 13" and does have Rosetta2 installed.

Here is the new copy of the log. I see it says 'upgrades are not allowed' if you look in the log you can see the MDM setting is correctly set to ALLOW upgrades. I think therefore this message is down the upgrade having been a bad installer app as evidenced by the no-entry symbol. It has now removed it and scheduled another run - hopefully it will work this time. In the meantime here is a copy of the log.

[super.log](https://github.com/Macjutsu/super/files/11600037/super.log)

The Super dialogs did say it had downloaded and was installing 13.4 which is correct latest version and I see only one build of that available which is for all models. As an M1 Mac it is supported.

**Comment by Macjutsu** [comment]
Quick look at the log... you may have found an actual bug there... I'll have to take a deeper look at this one.

**Comment by jelockwood** [comment]
@Macjutsu 
Let me know if you need any additional information or a repeat run.

**Comment by jelockwood** [comment]
@Macjutsu 
FYI - I see a mention in the Super log that there are no available updates/upgrades or it may be deferred via configuration profile.

It is true there are no updates as it is on 11.7.7 the last version of Big Sur but there should be an available Ventura upgrade and as discussed it did initially download and try to run this.

As a precaution I have checked and there is no configuration profile restricting updates _or_ upgrades. (This is defined in com.apple.applicationaccess.plist which in Jamf is in the Restrictions/Functionality section of a profile.)

**Comment by jelockwood** [comment]
Completely cleared out Super and installed 3.0rc2 but got the same results in that it downloaded Ventura, showed the dialogs allowed me to select restart, said it would take 25-30 mins and I could see various log entries whilst the dialog was shown and got a notification that an MDM command had been sent. 

When it eventually got to the install phase it failed as before. ☹️

**Comment by Macjutsu** [comment]
https://github.com/Macjutsu/super/releases/tag/v3.0

**Comment by jelockwood** [comment]
@Macjutsu 
I have removed Super RC1/RC2 to make it a clean Mac, rebooted, and installed 3.0 official.

Unfortunately it is still failing. I am attaching the log from the latest run. I think therefore your closing this bug is premature and it needs to be reopened.

[super.log](https://github.com/Macjutsu/super/files/11634290/super.log)

It is a but different this time, previously the macOS Installer would be deleted from the Applications folder, this time it is still there. Furthermore previously I would get a notification show up saying an MDM command had been queued, this time it did not. I therefore suspect that this time it simply did not run whereas previously it ran but failed.

**Comment by Macjutsu** [comment]
This is a completely different and unrelated error.

Fri Jun 02 11:06:10 G4-0001257 super[1322]: Error: Installation of macOS update/upgrade timed out after 600 seconds, trying again in 120 seconds.

So the installer started but timed out, this is an issue that is documented in the Wiki: https://github.com/Macjutsu/super/wiki/Troubleshooting#adjusting-workflow-timeouts

Specifically increase the `mdmWorkflowTimeoutSECONDS=600`

**Comment by jelockwood** [comment]
@Macjutsu 
I had a look at that article and I changed the timeout in the script from 600 seconds to 1000 seconds and it is still failing. Would it really take longer than this? No messages are happening during this phase. This time I did get the notification I was expecting although I see that when the process fails the notification is removed so maybe it was shown before and I missed it.

I am enclosing all the logs this time and a screen capture from shortly before it timed out.

[asu.log](https://github.com/Macjutsu/super/files/11636376/asu.log)
[asuList.log](https://github.com/Macjutsu/super/files/11636377/asuList.log)
[installer.log](https://github.com/Macjutsu/super/files/11636378/installer.log)
[installerList.log](https://github.com/Macjutsu/super/files/11636379/installerList.log)
[mdmCommand.log](https://github.com/Macjutsu/super/files/11636380/mdmCommand.log)
[mdmCommandDebug.log](https://github.com/Macjutsu/super/files/11636381/mdmCommandDebug.log)
[mdmWorkflow.log](https://github.com/Macjutsu/super/files/11636382/mdmWorkflow.log)
[mdmWorkflowDebug.log](https://github.com/Macjutsu/super/files/11636383/mdmWorkflowDebug.log)
[super.log](https://github.com/Macjutsu/super/files/11636384/super.log)
<img width="954" alt="Screenshot 2023-06-02 at 15 32 20" src="https://github.com/Macjutsu/super/assets/4300786/397ab43d-373e-43f8-8b29-1a6b369aea1c">

**Comment by Macjutsu** [comment]
You are experiencing something that unfortunately all too common.... `super` is doing its job... Jamf Pro is doing its job... macOS is failing. This is why the developers of `nudge` aren't even attempting to enforce via MDM push... it's just not reliable.

The proof is in the mdmWorkflow.log, your system starts the upgrade workflow but it never completes. Compare your mdmWorkflow.log to this [example of a mdmWorkflow.log showing a successful MDM macOS upgrade](https://github.com/Macjutsu/super/blob/main/Example-Logs/12.3-%3E13.3.1-Apple-Silicon-Jamf-Pro-MDM/mdmWorkflow.log).

You'll see it's fairly obvious that your system never starts preparing the upgrade, or specifically in the log, `phase:PREPARING_UPDATE`. In this case `super` is doing it's job... it's accurately detecting that the installation has not progressed. Also in this case, increasing the timeout only made it take longer for `super` to give up and declare failure. At this point, there isn't anything we can do but try again later or switch to a workflow that uses local authentication instead of the unreliable MDM method.

**Comment by jelockwood** [comment]
@Macjutsu 
I agree with you about MDM workflows. Sadly this is part of the many things Apple have and are changing which make enterprise management of Macs harder and harder.

I therefore have explored the option of setting Super and Jamf up so the deployment of Super by Jamf includes a local admin credential as part of the script parameters so it can create a backup service account on the laptop.

This appears to have worked. However I would be grateful if you could examine the logs to confirm what method it used, to clarify whether it did use the local account or happened to have a successfully MDM workflow.

[asu.log](https://github.com/Macjutsu/super/files/11650985/asu.log)
[asuList.log](https://github.com/Macjutsu/super/files/11650986/asuList.log)
[installer.log](https://github.com/Macjutsu/super/files/11650987/installer.log)
[installerList.log](https://github.com/Macjutsu/super/files/11650988/installerList.log)
[mdmCommand.log](https://github.com/Macjutsu/super/files/11650989/mdmCommand.log)
[mdmWorkflow.log](https://github.com/Macjutsu/super/files/11650990/mdmWorkflow.log)
[super.log](https://github.com/Macjutsu/super/files/11650991/super.log)

For your information my (new) org currently has the same password on all devices but I intend to implement a LAPS solution. Therefore see my comment to the following issue.

https://github.com/Macjutsu/super/issues/86

**Comment by Macjutsu** [comment]
It's right there in the super.log...

`Mon Jun 05 10:09:24 G4-0001257 Super[20945]: Startup: macOS update/upgrade workflows authenticated via super service account.`

**Comment by wander0r** [comment]
Hey @jelockwood I'd highly recommend you remove all the logs you've just posted as it contains your organization's JAMF Pro endpoint and API tokens.  Best practice going forward is to redact sensitive variables in log samples provided for troubleshooting efforts.
