### ISSUE TITLE
Feature Request (sort of) - MDM Workflow should log the Jamf Pro/Cloud server version

### ISSUE THREAD

**Issue by wakco** [Macjutsu/super#97]
To help with debugging, if the MDM workflow is being used, super should also log the Jamf Pro/Cloud server version, the version of the `jamf` command and/or the **Self Service** app. This should make it easier to identify if the issue in an MDM workflow is a known issue with the Jamf Pro/Cloud version (and reduce the need to ask for the version in the slack channel).

The `jamf` command, and **Self Service** should always match the server version, unless the server was just updated, but even then, the on computer version should self update within a day of the server updating.

It should also be possible to gather the server version through the connection to the server when sending the MDM commands.

**Comment by Macjutsu** [comment]
https://github.com/Macjutsu/super/releases/tag/v3.0
